// Auto-generated by story_graph.py — do not edit by hand
const STORY_DATA = {
  "nodes": {
    "start": {
      "title": "A Peculiar Afternoon",
      "text": "Theodore Ernest O'Hare -- Theo to everyone who knows him -- is seventeen, restless, and supposed to be reading a chapter about a medieval Italian writer named Boccaccio. The textbook is open on his desk to a painting of young people in a garden, telling stories while the plague rages beyond the walls.\n\n'One hundred tales,' the caption reads. 'Told over ten days.'\n\nTheo's eyelids are heavy. The afternoon light turns golden, then amber, then impossibly warm -- warm like a Tuscan afternoon, warm like bread from a stone oven, warm like a world that hasn't learned yet that it's about to end.\n\nWhen Theo opens his eyes, the desk is gone. The textbook is gone. He is sitting on a marble bench in a church so vast that the ceiling vanishes into shadow. The air reeks of incense and something worse -- something sweet and terrible that he can't name. A bell is tolling. Outside, through the open doors, he can see a city of terracotta rooftops under a pitiless blue sky.\n\nA young woman in a green dress approaches him. She has dark eyes, a sharp chin, and an expression that suggests she has already decided he is either useful or amusing.\n\n'You look lost,' she says. 'Are you here for the service? There's hardly anyone left to attend.' She pauses. 'I'm **Pampinea**. My friends and I are leaving the city today -- the **pestilence** is everywhere. We have a villa in the hills.' She studies him. 'You could come with us. Or you could stay here and take your chances with the dead-carts.'",
      "choices": [
        {
          "text": "Go with Pampinea and her friends to the villa",
          "target": "act1_plague_join_brigata"
        },
        {
          "text": "Stay in Florence -- there must be people who need help",
          "target": "act1_plague_stay_florence"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "frame",
      "vocabulary": [
        {
          "term": "Pampinea",
          "definition": "The eldest and most commanding of the seven young women in the Decameron's brigata. She proposes the plan to flee Florence and is elected queen of the first day."
        },
        {
          "term": "Pestilence",
          "definition": "The plague -- specifically the Black Death of 1348, which killed roughly a third of Europe's population. Boccaccio's own father may have died in it."
        }
      ],
      "figures": [
        "Pampinea"
      ],
      "tags": [
        "entry",
        "frame_story",
        "arrival"
      ]
    },
    "act1_plague_join_brigata": {
      "title": "The Company of Ten",
      "text": "They gather in the church -- seven young women and three young men. Pampinea has organized everything: horses, provisions, servants. The women are sharp and literate; the men are poets and wits. Theo counts them: **Filomena**, quiet and observant. **Neifile**, who laughs easily. **Filostrato**, who broods. **Dioneo**, who makes jokes about everything, even the corpses piled by the baptistery.\n\nAs they ride out through the gate, Theo sees things he will not forget: a mother sitting in a doorway, rocking an empty cradle. A dog nosing at a shape in the gutter. Two men in bird-beak masks carrying a stretcher. The city is dying.\n\nThe road climbs into the hills. Olive trees. Cypresses. The air sweetens. After an hour they reach a villa with a walled garden, a fountain, and lemon trees heavy with fruit.\n\nPampinea gathers them in the garden. 'We cannot simply wait for death,' she says. 'We need order. I propose that each day, one of us shall be queen or king and set a theme. And we shall each tell a tale -- one hundred tales over ten days. Stories to keep us human.'\n\nThe others agree. Pampinea is elected queen of the first day.\n\nShe turns to Theo. 'And you, stranger -- will you tell a tale, or only listen?'",
      "choices": [
        {
          "text": "'I'll tell a tale.' (Join the storytelling)",
          "target": "act2_day1_tell_tale"
        },
        {
          "text": "'I'd rather listen and learn.' (Observe quietly)",
          "target": "act2_day1_listen"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "plague",
      "vocabulary": [
        {
          "term": "Filomena",
          "definition": "One of the seven young women. Her name means 'lover of song.' She is thoughtful and perceptive, often chosen to tell tales about wisdom and moral complexity."
        },
        {
          "term": "Neifile",
          "definition": "One of the seven young women. Her name may mean 'new to love.' She tells tales of clever women and happy endings."
        },
        {
          "term": "Filostrato",
          "definition": "One of the three young men. His name means 'struck down by love.' He is melancholic and chooses tragic love as the theme for Day Four."
        },
        {
          "term": "Dioneo",
          "definition": "The most irreverent of the three young men. He always tells the last tale of the day and has a special privilege: his tale need not follow the day's theme. He often tells bawdy or subversive stories."
        }
      ],
      "figures": [
        "Pampinea",
        "Filomena",
        "Neifile",
        "Filostrato",
        "Dioneo"
      ],
      "tags": [
        "plague",
        "brigata_assembly",
        "key_decision"
      ]
    },
    "act1_plague_stay_florence": {
      "title": "The City of the Dead",
      "text": "Theo watches Pampinea leave with a shrug. He's not going to run away. Someone should do something.\n\nHe walks into the streets. It's worse than he imagined. The **Black Death** has turned Florence into a charnel house. Shops are shuttered. Churches overflow. The gravediggers work in shifts and still can't keep up. He passes a palazzo where a feast is happening -- music, laughter, wine -- because some Florentines have decided that if they're going to die, they might as well die drunk.\n\nNear the Arno, he finds an old friar distributing bread to a line of hollow-eyed survivors. The friar looks up. 'Another pair of hands. Good. Take the basket.'\n\nFor three days Theo helps -- carrying bread, fetching water, holding the hands of the dying. He learns more about courage and suffering than any textbook could teach. But on the fourth morning, he wakes with a headache and a terrible chill.\n\nA woman checks his forehead. 'It may be nothing,' she says, not meeting his eyes. 'Or it may be the sickness. You should leave the city while you still can.'\n\nHe remembers Pampinea's invitation. A villa in the hills.",
      "choices": [
        {
          "text": "Flee to the hills and find the brigata",
          "target": "act1_plague_late_arrival"
        },
        {
          "text": "Stay and keep helping -- someone has to",
          "target": "end_plague_courage"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "plague",
      "vocabulary": [
        {
          "term": "Black Death",
          "definition": "The bubonic plague pandemic that swept through Europe from 1347-1353, killing an estimated 25-50 million people -- roughly one-third of the continent's population."
        }
      ],
      "figures": [],
      "tags": [
        "plague",
        "florence",
        "courage"
      ]
    },
    "act1_plague_late_arrival": {
      "title": "A Late Addition",
      "text": "Theo drags himself up the hill road. His head pounds, but by evening the fever breaks -- it was exhaustion, not plague. He arrives at the villa as the **brigata** is finishing dinner.\n\nDioneo spots him first. 'Look! The city threw one back!'\n\nPampinea raises an eyebrow. 'You changed your mind.'\n\n'I learned something down there,' Theo says. 'About what happens when there are no stories. People lose their minds. They drink until they can't feel, or they pray until they can't think, or they just sit in doorways waiting. Stories are the only thing that still makes sense.'\n\nPampinea smiles. 'Then you've already understood the first lesson. Sit down. Tomorrow we begin.'",
      "choices": [
        {
          "text": "Tell the brigata what you saw in the city",
          "target": "act2_day1_tell_tale"
        },
        {
          "text": "Sit quietly and listen to the first day's tales",
          "target": "act2_day1_listen"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "plague",
      "vocabulary": [
        {
          "term": "Brigata",
          "definition": "The 'company' or 'brigade' -- the group of ten young people who flee Florence and tell the tales of the Decameron. The word suggests both friendship and shared purpose."
        }
      ],
      "figures": [
        "Pampinea",
        "Dioneo"
      ],
      "tags": [
        "brigata",
        "late_arrival",
        "convergence"
      ]
    },
    "act2_day1_tell_tale": {
      "title": "The First Day: Your Turn",
      "text": "The morning is bright. They sit in the garden under a pergola heavy with jasmine. Pampinea declares the first day open: no set theme -- speak on any subject you please.\n\nThe tales begin. **Panfilo** tells of **Ser Ciappelletto**, a wicked man who makes such a convincing false confession on his deathbed that the friar actually canonizes him. The brigata laughs, but nervously -- the tale asks whether we can ever truly know another person.\n\nThen Neifile tells the tale of **Melchisedech and the Three Rings**: when Saladin asks a Jewish merchant which of the three great religions is the true one, Melchisedech answers with a parable about three identical rings -- no one can tell the original from the copies. It's the most elegant dodge Theo has ever heard.\n\nNow it's Theo's turn. Pampinea looks at him expectantly.\n\nHe doesn't know a medieval tale. But he knows stories.",
      "choices": [
        {
          "text": "Tell a story about someone whose words saved them (like Melchisedech)",
          "target": "act2_day1_wit_tale"
        },
        {
          "text": "Tell an honest story about what you saw in the plague city",
          "target": "act2_day1_plague_tale"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day1_wit",
      "vocabulary": [
        {
          "term": "Panfilo",
          "definition": "One of the three young men. His name means 'all love.' He tells the first tale of the Decameron -- the story of Ser Ciappelletto."
        },
        {
          "term": "Ser Ciappelletto",
          "definition": "The subject of the very first tale: a notoriously wicked man who deceives a friar with a false deathbed confession so convincing that he is venerated as a saint after death."
        },
        {
          "term": "Melchisedech and the Three Rings",
          "definition": "Novel I.3 -- a Jewish merchant avoids Saladin's trap by telling a parable about three identical rings, each representing one of the great religions. The tale is one of the most famous statements of religious tolerance in medieval literature."
        }
      ],
      "figures": [
        "Panfilo",
        "Ser Ciappelletto",
        "Melchisedech",
        "Saladin"
      ],
      "tags": [
        "day1",
        "storytelling",
        "key_decision"
      ]
    },
    "act2_day1_listen": {
      "title": "The First Day: Listening",
      "text": "Theo sits at the edge of the circle and listens. The tales wash over him -- Ser Ciappelletto's outrageous deathbed performance, Melchisedech's parable of the rings, a Gascon lady who shames a cowardly king with a single sentence.\n\nHe notices something. Every tale is about **wit** -- about the power of the right word at the right moment. The wicked man survives by the cleverness of his tongue. The wise man survives by the cleverness of his parable. Even the woman's rebuke is a kind of weapon forged from language.\n\nAfter the last tale, Dioneo nudges him. 'You're quiet. Thinking deep thoughts?'\n\n'I'm thinking that words matter more here than swords,' Theo says.\n\nDioneo grins. 'Now you're beginning to understand Florence.'",
      "choices": [
        {
          "text": "Ask Dioneo about the relationship between wit and survival",
          "target": "act2_day1_dioneo_talk"
        },
        {
          "text": "Seek out Filomena, who seemed to understand the tales most deeply",
          "target": "act2_day1_filomena_talk"
        },
        {
          "text": "Nod politely and go to bed -- it's been a long day",
          "target": "end_neutral"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day1_wit",
      "vocabulary": [
        {
          "term": "Wit",
          "definition": "In the Decameron, 'wit' (Italian: motto or ingegno) means more than humor -- it means the intelligence and verbal dexterity to navigate dangerous situations. It is perhaps the supreme virtue in Boccaccio's world."
        }
      ],
      "figures": [
        "Dioneo"
      ],
      "tags": [
        "day1",
        "listening",
        "observation"
      ]
    },
    "act2_day1_wit_tale": {
      "title": "A Tale of Words",
      "text": "Theo improvises a tale about a student who is called before a strict teacher and accused of cheating. The student didn't cheat, but all the evidence is against him. So instead of arguing the facts, he tells the teacher a story -- a parable about how things that look identical can have very different origins, just like Melchisedech's three rings.\n\nThe brigata is delighted. 'He learns fast!' Pampinea says.\n\nFilostrato is less impressed. 'A pretty trick. But wit alone can't save you from real suffering. Wait until Day Four -- I'll show you what love and death look like.'\n\nThat evening, walking in the garden, Theo finds himself drawn into a conversation between two of the women.",
      "choices": [
        {
          "text": "Join Pampinea and Filomena debating whether cleverness is a virtue or a vice",
          "target": "act3_cleverness_debate"
        },
        {
          "text": "Wander to the garden wall and look back toward Florence",
          "target": "act3_garden_wall"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day1_wit",
      "vocabulary": [],
      "figures": [
        "Filostrato",
        "Pampinea"
      ],
      "tags": [
        "day1",
        "storytelling_success",
        "rising_action"
      ]
    },
    "act2_day1_plague_tale": {
      "title": "An Unwelcome Truth",
      "text": "Theo tells what he saw: the mother with the empty cradle. The gravediggers who stopped counting. The palazzo where the rich drank and danced while the poor died in doorways.\n\nThe garden goes quiet. Pampinea's expression tightens. Filostrato looks away. Even Dioneo has nothing to say.\n\n'That's not a tale,' Pampinea says finally. 'That's a report. We came here to escape that -- to build something human in the space the plague leaves behind. If we only repeat what the plague does to us, we're not storytelling. We're just dying more slowly.'\n\nTheo feels the rebuke. But Filomena speaks up. 'No -- he's right to tell it. The best tales hold truth inside them, even when the truth is ugly. The question is what you do with the truth after you tell it.'",
      "choices": [
        {
          "text": "Accept Pampinea's correction -- stories should lift people up",
          "target": "act3_garden_wall"
        },
        {
          "text": "Side with Filomena -- truth matters, even when it hurts",
          "target": "act3_truth_matters"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day1_wit",
      "vocabulary": [],
      "figures": [
        "Pampinea",
        "Filomena",
        "Filostrato",
        "Dioneo"
      ],
      "tags": [
        "day1",
        "truth_vs_comfort",
        "key_decision"
      ]
    },
    "act2_day1_dioneo_talk": {
      "title": "Dioneo's Philosophy",
      "text": "Dioneo leans against a column, peeling an orange with a knife. 'Wit,' he says, 'is the only weapon that doesn't rust. Swords break. Money runs out. Beauty fades. But if you can make someone laugh at the right moment, or say the one thing that turns an enemy into a friend, you'll survive anything.'\n\n'Even the plague?'\n\n'Especially the plague.' He gestures at the villa. 'What do you think this is? We can't cure the sickness. We can't fight it. All we can do is tell stories -- and the stories have to be good enough to make us forget, at least for an hour, that half the world is rotting outside these walls.'\n\nHe pops an orange segment into his mouth. 'That's why I always tell the last tale. The one that makes them laugh. Someone has to remind the others that being alive is still worth something. Even now. **Especially** now.'",
      "choices": [
        {
          "text": "Ask what happens when laughter isn't enough",
          "target": "act3_garden_wall"
        },
        {
          "text": "Ask about the days ahead -- what themes will the tales explore?",
          "target": "act3_cleverness_debate"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day1_wit",
      "vocabulary": [],
      "figures": [
        "Dioneo"
      ],
      "tags": [
        "day1",
        "dioneo",
        "philosophy"
      ]
    },
    "act2_day1_filomena_talk": {
      "title": "Filomena's Insight",
      "text": "Filomena is sitting by the fountain, trailing her fingers in the water. She looks up when Theo approaches.\n\n'You noticed it,' she says. 'The tales aren't just entertainment. They're arguments. Ciappelletto's tale asks: can a lie serve the truth? The three rings ask: can tolerance survive in a world that demands certainty?'\n\n'And the Gascon lady?'\n\n'She asks the simplest question of all: when someone with power fails to use it justly, is it enough to shame them with words?' Filomena smiles. 'Boccaccio -- the man who arranged these tales -- believed that stories are how civilized people argue. Not with swords or laws, but with **novelle**. Each tale is a tiny courtroom. The reader is the judge.'\n\nShe looks toward the city on the horizon. The smoke from the plague pyres is visible even here.\n\n'The real question,' she says quietly, 'is whether the judge can bear to hear all the evidence. Some of the tales ahead are not gentle.'",
      "choices": [
        {
          "text": "Ask what she means by 'not gentle'",
          "target": "act3_truth_matters"
        },
        {
          "text": "Ask about the structure of the ten days",
          "target": "act3_cleverness_debate"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day1_wit",
      "vocabulary": [
        {
          "term": "Novelle",
          "definition": "Short prose tales -- the literary form Boccaccio perfected in the Decameron. The Italian word gives us the English 'novel.' Each novella in the Decameron is a self-contained story told by one of the ten narrators."
        }
      ],
      "figures": [
        "Filomena"
      ],
      "tags": [
        "day1",
        "filomena",
        "literary_insight"
      ]
    },
    "act3_cleverness_debate": {
      "title": "The Virtue of Cleverness",
      "text": "The days pass. Day Two brings tales of **Fortune** -- how chance tosses people about like ships in a storm. Theo hears the tale of **Andreuccio da Perugia**, a naive horse-dealer who goes to Naples, gets swindled, falls into a sewer, and ends up robbing an archbishop's tomb. He arrives richer than he started. Fortune and wit together.\n\nDay Three celebrates cleverness itself -- **ingegno**. Tales of people who get what they want through sheer intelligence. Some of the cleverness is admirable. Some is... morally questionable.\n\nAt dinner, an argument breaks out. Pampinea insists that cleverness is neutral -- a tool, like a knife. It depends on who wields it. Filostrato disagrees: 'A knife that only cuts for yourself is selfishness dressed as intelligence.'\n\nThey turn to Theo.",
      "choices": [
        {
          "text": "Side with Pampinea: cleverness is a tool, neither good nor evil",
          "target": "act4_fortune_path"
        },
        {
          "text": "Side with Filostrato: intelligence without compassion is dangerous",
          "target": "act4_tragedy_path"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day2_fortune",
      "vocabulary": [
        {
          "term": "Fortune",
          "definition": "Fate or chance, personified in medieval literature as the goddess Fortuna, who spins her wheel to raise and cast down mortals at will. Day Two of the Decameron explores how people respond when Fortune acts upon them."
        },
        {
          "term": "Andreuccio da Perugia",
          "definition": "The hero of Novel II.5 -- a naive horse-dealer whose night of misadventures in Naples is one of the greatest picaresque tales in the Decameron."
        },
        {
          "term": "Ingegno",
          "definition": "Intelligence, cleverness, resourcefulness -- perhaps the most celebrated virtue in the Decameron. Day Three is devoted to tales of those who obtain what they desire through ingegno."
        }
      ],
      "figures": [
        "Andreuccio",
        "Pampinea",
        "Filostrato"
      ],
      "tags": [
        "day2",
        "day3",
        "cleverness",
        "convergence",
        "key_decision"
      ]
    },
    "act3_garden_wall": {
      "title": "The View from the Wall",
      "text": "Theo walks to the garden wall and looks south toward Florence. Smoke rises from the city -- not cooking fires but something worse. The plague pyres. Even from this distance, the stench reaches him on certain winds.\n\nHe thinks about what they're doing here. Ten young people telling stories in a garden while the world burns. Is it cowardice? Self-indulgence? Or is Pampinea right -- is storytelling the most human thing you can do when everything else has failed?\n\nFilostrato joins him at the wall. His face is grim.\n\n'You're wondering if any of this matters,' he says. 'Whether tales of wit and fortune can stand up against the reality of that.' He points at the smoke. 'Wait for Day Four. That's my day. The theme is love that ends in death. I'll show you stories that don't look away.'",
      "choices": [
        {
          "text": "Ask Filostrato why tragedy matters",
          "target": "act4_tragedy_path"
        },
        {
          "text": "Push back: stories should give people hope, not more darkness",
          "target": "act4_fortune_path"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day2_fortune",
      "vocabulary": [],
      "figures": [
        "Filostrato"
      ],
      "tags": [
        "plague",
        "reflection",
        "convergence"
      ]
    },
    "act3_truth_matters": {
      "title": "The Weight of Truth",
      "text": "Over the next two days, the tales grow darker. Fortune batters the innocent. Cleverness sometimes serves cruelty. A princess is shipwrecked and passed from man to man, and the tale treats her suffering as comedy. Theo is disturbed.\n\nHe finds Filomena in the library. 'Some of these tales bother me,' he says. 'They laugh at people who are suffering.'\n\nShe nods slowly. 'Yes. Boccaccio doesn't always comfort. Sometimes he holds up a mirror and what you see is ugly. The question is whether looking away makes you wiser or just more comfortable.'\n\n'But what's the point of a story that only shows suffering?'\n\n'The point,' Filomena says, 'is that you *felt* the suffering. A story that makes you uncomfortable is doing its work. The **Decameron** has room for all of it -- comedy, tragedy, justice, cruelty. That's what makes it honest.'\n\nThe conversation is interrupted by Filostrato announcing that tomorrow, Day Four, belongs to him. The theme: love that ends in death.",
      "choices": [
        {
          "text": "Attend Day Four with an open heart -- face the tragedy",
          "target": "act4_tragedy_path"
        },
        {
          "text": "Skip Day Four and walk in the countryside instead",
          "target": "act4_fortune_path"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day2_fortune",
      "vocabulary": [
        {
          "term": "Decameron",
          "definition": "From the Greek: 'ten days' work.' Boccaccio's masterpiece -- a collection of one hundred tales told over ten days by ten young people who have fled the Black Death in Florence. Written c. 1349-1353."
        }
      ],
      "figures": [
        "Filomena",
        "Filostrato"
      ],
      "tags": [
        "truth",
        "discomfort",
        "convergence"
      ]
    },
    "act4_fortune_path": {
      "title": "The Wheel Turns",
      "text": "Theo throws himself into the lighter days. Day Two's tales of **Fortuna** fascinate him -- the way people are tossed about by chance, and how the ones who survive are the ones who adapt. Andreuccio falls into a sewer and emerges a thief. A princess crosses the Mediterranean nine times. Fortune doesn't care about your plans.\n\nOn Day Five, the theme is love rewarded. The tales are gentler. But one tale seizes Theo's attention: the story of **Federigo degli Alberighi**, who spends his entire fortune trying to win a lady's love. When she finally visits his house, he has nothing left to feed her -- so he kills his beloved **falcon**, his last treasure, and serves it to her. She is so moved by his sacrifice that she marries him.\n\n'That's beautiful,' Theo says.\n\nDioneo snorts. 'It's insane. The man cooked his best friend for a woman who ignored him for years.'\n\n'No,' Filomena says quietly. 'It's the most perfect story in the whole Decameron. Everything stripped away until only the gesture remains.'",
      "choices": [
        {
          "text": "Agree with Filomena -- Federigo's sacrifice is noble",
          "target": "act5_sacrifice_noble"
        },
        {
          "text": "Agree with Dioneo -- there's something troubling about it",
          "target": "act5_sacrifice_troubling"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day5_love",
      "vocabulary": [
        {
          "term": "Fortuna",
          "definition": "The personified goddess of fortune or chance, often depicted turning a great wheel that raises some to power and casts others into ruin. A central concept in Day Two of the Decameron."
        },
        {
          "term": "Federigo degli Alberighi",
          "definition": "The hero of Novel V.9 -- the most famous tale in the Decameron. A nobleman who sacrifices his beloved falcon (his last possession) to feed the woman he loves. Critics from the Renaissance onward have praised it as the 'perfect novella.'"
        },
        {
          "term": "Falcon",
          "definition": "Federigo's prized hunting hawk, the last remnant of his former wealth and his only companion. When he kills it to honor his guest, the falcon becomes a symbol of absolute selfless devotion."
        }
      ],
      "figures": [
        "Federigo",
        "Dioneo",
        "Filomena"
      ],
      "tags": [
        "day5",
        "falcon",
        "fortune",
        "love",
        "key_decision"
      ]
    },
    "act4_tragedy_path": {
      "title": "Day the Fourth: Love and Death",
      "text": "Filostrato takes the throne. His theme: tales of those whose love has an unhappy ending.\n\nThe first tale is devastating. **Tancred**, a prince, discovers his daughter **Ghismonda** has taken a lover beneath her station. He kills the lover and sends her the man's heart in a golden cup. But before she dies -- by her own hand, with poison -- Ghismonda delivers a speech so powerful that it silences the entire brigata.\n\n'I chose my lover not by noble birth but by noble character,' she tells her father. 'Nature makes no distinction between the blood of the poor and the blood of princes. The only true nobility is **virtue**.'\n\nTheo is shaken. The tale asks whether a father's authority can override a daughter's right to choose. Ghismonda says no -- and pays with her life.\n\nAfter the tale, the garden is silent. Even Dioneo has nothing clever to say.",
      "choices": [
        {
          "text": "Ghismonda was right to defy her father -- love and virtue matter more than obedience",
          "target": "act5_ghismonda_right"
        },
        {
          "text": "The whole situation is tragic -- both father and daughter had reasons, and both lost everything",
          "target": "act5_tragedy_complex"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day4_tragedy",
      "vocabulary": [
        {
          "term": "Tancred",
          "definition": "The Prince of Salerno in Novel IV.1. He discovers his daughter's love affair and murders her lover, provoking one of the most powerful speeches in the Decameron."
        },
        {
          "term": "Ghismonda",
          "definition": "Tancred's daughter. Her defense of her right to choose a lover based on virtue rather than birth is one of the most famous speeches in medieval literature -- a declaration of natural law against paternal tyranny."
        },
        {
          "term": "Virtue",
          "definition": "In the Decameron's usage, virtue means excellence of character -- moral courage, generosity, wisdom -- rather than mere obedience or chastity. Ghismonda argues that virtue belongs to the individual, not to their bloodline."
        }
      ],
      "figures": [
        "Filostrato",
        "Tancred",
        "Ghismonda"
      ],
      "tags": [
        "day4",
        "tragedy",
        "ghismonda",
        "key_decision"
      ]
    },
    "act5_sacrifice_noble": {
      "title": "The Heart of Generosity",
      "text": "Filomena's eyes brighten. 'You understand. Federigo's falcon isn't just a bird -- it's everything he has left. And he gives it away without hesitation, without calculation, without even knowing whether his gesture will be received. That's what **magnificenza** looks like.'\n\n'Generosity,' Theo says.\n\n'Not just generosity. *Magnificence*. The willingness to give beyond what anyone could ask, because the giving itself is the point. Day Ten -- the last day -- is all about this. Tales of people who are so generous, so magnanimous, that they transcend the pettiness of the world.'\n\nShe pauses. 'But you haven't heard Day Six yet. That's the day about speech -- about the power of the right word. And Day Ten... Day Ten is where it all comes together. Or falls apart.'",
      "choices": [
        {
          "text": "Ask about Day Six -- the power of speech",
          "target": "act6_day6_speech"
        },
        {
          "text": "Skip ahead to Day Ten -- you want to see how it ends",
          "target": "act7_day10_magnanimity"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day5_love",
      "vocabulary": [
        {
          "term": "Magnificenza",
          "definition": "Magnanimity, magnificence -- the willingness to perform great and generous deeds beyond what is required. The crowning virtue of Day Ten, where the Decameron reaches its moral summit."
        }
      ],
      "figures": [
        "Filomena",
        "Federigo"
      ],
      "tags": [
        "day5",
        "generosity",
        "magnificenza"
      ]
    },
    "act5_sacrifice_troubling": {
      "title": "The Falcon's Shadow",
      "text": "Dioneo claps Theo on the back. 'Finally, someone with sense! The falcon tale is beautiful, sure. But pull back the curtain and what do you see? A man who destroys the thing he loves most to impress someone who never gave him the time of day. Is that love or is that madness?'\n\n'It's the same question Ghismonda raises,' Filomena says, joining them. 'What is love worth? What should you be willing to sacrifice for it? Boccaccio never gives a simple answer. He just tells you the story and lets you argue.'\n\nDioneo shrugs. 'And that's why I always tell the last tale of the day. Someone has to remind everyone that most of life is comedy, not tragedy. The worst thing you can do is take yourself too seriously.'\n\n'Is that what Day Six is about?' Theo asks. 'The day of speech?'\n\n'Day Six,' Dioneo says, grinning, 'is my favorite. It's about people who say exactly the right thing at exactly the right moment. The art of the **motto**.'",
      "choices": [
        {
          "text": "Explore Day Six with Dioneo -- the art of perfect speech",
          "target": "act6_day6_speech"
        },
        {
          "text": "Press the argument further -- is Boccaccio ultimately an optimist or a pessimist?",
          "target": "act6_optimist_pessimist"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day5_love",
      "vocabulary": [
        {
          "term": "Motto",
          "definition": "A witty remark or bon mot -- the verbal weapon of Day Six. In Boccaccio's Florence, the ability to deliver the perfect rejoinder at the perfect moment was considered a supreme social skill."
        }
      ],
      "figures": [
        "Dioneo",
        "Filomena"
      ],
      "tags": [
        "day5",
        "questioning",
        "comedy_vs_tragedy"
      ]
    },
    "act5_ghismonda_right": {
      "title": "Natural Law",
      "text": "Theo's words hang in the evening air. 'She was right. No one should have to ask permission to love.'\n\nFilostrato nods slowly. 'That's what I wanted the tales to show. Love isn't polite. It doesn't obey fathers or kings or priests. It follows its own law -- the law of nature. And when society crushes it, the result is tragedy.'\n\n'But the Decameron doesn't end with tragedy,' Pampinea says. 'Day Five is love rewarded. Day Six is the power of words. And Day Ten...' She smiles. 'Day Ten is about people who rise above everything -- love, loss, fortune -- through sheer generosity of spirit.'\n\nFilostrato waves his hand. 'Pampinea the optimist. Always rushing toward the happy ending.'\n\n'Not rushing,' she says. 'Earning it. You have to walk through the dark days to deserve the light ones.'",
      "choices": [
        {
          "text": "Follow the bright thread -- hear about Day Six and the power of speech",
          "target": "act6_day6_speech"
        },
        {
          "text": "Stay with the darkness a moment longer -- ask about the cruelest tales",
          "target": "act6_cruel_tales"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day4_tragedy",
      "vocabulary": [],
      "figures": [
        "Filostrato",
        "Pampinea"
      ],
      "tags": [
        "day4",
        "natural_law",
        "defiance"
      ]
    },
    "act5_tragedy_complex": {
      "title": "The Weight of Both Sides",
      "text": "Theo shakes his head. 'I can't just pick a side. Tancred loved his daughter -- that's why he went mad. Ghismonda loved Guiscardo -- that's why she defied her father. They were both right and both wrong.'\n\nThe brigata considers this. It's Neifile who speaks first: 'That's the most Boccaccian thing anyone has said all day. He never gives you a simple moral. Every tale has at least two truths fighting each other.'\n\nFilomena adds: 'The great tales -- the ones that last for centuries -- are the ones where you can argue both sides forever. That's what a **novella** is at its best: not a lesson but a question.'\n\nDioneo raises his cup. 'And on that note, I have a tale for Day Six that will make all of you laugh. Come back tomorrow and I'll tell you about a friar, a feather, and a very gullible congregation.'",
      "choices": [
        {
          "text": "Come back for Day Six -- you need laughter after Day Four",
          "target": "act6_day6_speech"
        },
        {
          "text": "Reflect on what Filomena said about tales as questions, not lessons",
          "target": "act6_optimist_pessimist"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day4_tragedy",
      "vocabulary": [],
      "figures": [
        "Neifile",
        "Filomena",
        "Dioneo"
      ],
      "tags": [
        "day4",
        "complexity",
        "both_sides"
      ]
    },
    "act6_day6_speech": {
      "title": "Day the Sixth: The Art of the Word",
      "text": "Day Six belongs to speech -- tales of those who, by a clever remark, avoided danger or turned shame into triumph.\n\nThe shortest tale is the most striking: **Madonna Oretta** accepts a knight's offer to 'carry her' with a story on a long walk. But he tells the tale so badly -- stammering, repeating, losing the thread -- that she begs him to set her down. 'Sir,' she says, 'your horse trots too rough.'\n\nTheo laughs. It's Boccaccio writing about *bad storytelling*.\n\nThen comes **Fra Cipolla** -- a wandering friar who promises country folk a feather from the Angel Gabriel's wing. When pranksters swap his relic for charcoal, he improvises a speech so magnificently absurd that the congregation gives even more money than before.\n\n'There it is,' Dioneo says. 'The supreme lesson of the Decameron. It's not what you have. It's what you *say* about what you have.'",
      "choices": [
        {
          "text": "This is Boccaccio's manifesto -- storytelling IS the supreme art",
          "target": "act7_day10_magnanimity"
        },
        {
          "text": "But isn't Fra Cipolla just a con man? Where's the line between wit and fraud?",
          "target": "act6_wit_vs_fraud"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day6_speech",
      "vocabulary": [
        {
          "term": "Madonna Oretta",
          "definition": "The heroine of Novel VI.1 -- the shortest and most self-reflexive tale in the Decameron. Her polite rebuke of a bad storyteller is Boccaccio's miniature manifesto about the art of narration."
        },
        {
          "term": "Fra Cipolla",
          "definition": "The hero of Novel VI.10 -- a wandering friar whose gift for improvised rhetoric is so extraordinary that he turns a prank into a triumph. He represents the comic genius of the Decameron at its most exuberant."
        }
      ],
      "figures": [
        "Madonna Oretta",
        "Fra Cipolla",
        "Dioneo"
      ],
      "tags": [
        "day6",
        "speech",
        "storytelling",
        "convergence"
      ]
    },
    "act6_optimist_pessimist": {
      "title": "The Arc of the Ten Days",
      "text": "Theo sits with Filomena under the lemon trees. 'Is Boccaccio an optimist or a pessimist?' he asks.\n\n'Neither,' she says. 'He's a realist. But a realist who believes in architecture.'\n\n'Architecture?'\n\n'Look at the shape of the ten days. Day One: freedom, wit, anything goes. Days Two and Three: fortune and cleverness -- the world as it is, messy and amoral. Day Four: love and death, the darkest valley. Day Five: love rewarded, the first light after the storm. Day Six: the power of speech. Days Seven and Eight: comedy and tricks -- human nature at its most basic. Day Nine: another free day, a breath before the end. And Day Ten...' She looks up at him. 'Day Ten is magnanimity. The highest virtue. After all the wit and fortune and tragedy and comedy and trickery, the Decameron ends with tales of people who are *generous beyond reason*.'\n\n'The arc goes from plague to virtue,' Theo says.\n\n'From death to the best of what we can be. That's the architecture. That's why the order matters.'",
      "choices": [
        {
          "text": "Go to Day Ten and see the summit for yourself",
          "target": "act7_day10_magnanimity"
        },
        {
          "text": "First, hear about Day Six -- the art of the word",
          "target": "act6_day6_speech"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day6_speech",
      "vocabulary": [],
      "figures": [
        "Filomena"
      ],
      "tags": [
        "structure",
        "arc",
        "filomena"
      ]
    },
    "act6_cruel_tales": {
      "title": "The Scholar's Revenge",
      "text": "The middle days bring stories Theo finds hard to stomach. Day Seven: wives who trick their husbands. Day Eight: elaborate pranks and cruel revenge.\n\nOne tale in particular haunts him. A scholar, humiliated by a beautiful widow, takes such terrible revenge that Theo feels sick. He traps her on a tower roof in the summer sun, naked and burning, while he lectures her about the superiority of intellect over beauty.\n\n'That's not a tale,' Theo says. 'That's cruelty.'\n\nPampinea nods. 'It is. And Boccaccio knew it. The Decameron doesn't only show us what's admirable. It shows us what intelligence becomes when it has no compassion -- a weapon.'\n\n'Then why include it?'\n\n'Because if you only tell the pretty stories, you're lying. The ten days have to contain everything. Light and dark. Mercy and cruelty. That's what makes Day Ten so powerful -- after all the ugliness, the Decameron chooses to end with the best of us, not the worst.'",
      "choices": [
        {
          "text": "Trust the architecture -- go to Day Ten",
          "target": "act7_day10_magnanimity"
        },
        {
          "text": "Ask about Day Six first -- the bridge between comedy and virtue",
          "target": "act6_day6_speech"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day6_speech",
      "vocabulary": [],
      "figures": [
        "Pampinea"
      ],
      "tags": [
        "day8",
        "cruelty",
        "dark_tales"
      ]
    },
    "act6_wit_vs_fraud": {
      "title": "The Line Between Wit and Fraud",
      "text": "Dioneo raises an eyebrow. 'A con man? Fra Cipolla? Absolutely. The finest con man in all of literature. But here's the thing: the congregation *knows* he's full of nonsense. They come anyway. They *want* the performance. They're paying for the show, not the feather.'\n\n'So it's... mutual?'\n\n'It's Florence,' Dioneo says. 'In this city, we respect a good performance more than a dull truth. Ciappelletto lied his way into sainthood on Day One. Fra Cipolla lies his way into everyone's purse on Day Six. The Decameron doesn't moralize about this -- it celebrates the craft.'\n\nFilomena interrupts. 'Dioneo is half right. Boccaccio celebrates the craft but not always the craftsman. There's a difference between Melchisedech's parable -- a lie that serves peace -- and Ciappelletto's confession -- a lie that serves vanity. The tales make you figure out which is which.'\n\nIt strikes Theo that this is itself the lesson: the Decameron trusts its reader to judge.",
      "choices": [
        {
          "text": "Head to Day Ten -- time to see whether the final tales redeem the rest",
          "target": "act7_day10_magnanimity"
        },
        {
          "text": "Ask one more question: what's the very last tale about?",
          "target": "act7_griselda_question"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day6_speech",
      "vocabulary": [],
      "figures": [
        "Dioneo",
        "Filomena"
      ],
      "tags": [
        "day6",
        "wit_vs_fraud",
        "moral_ambiguity"
      ]
    },
    "act7_day10_magnanimity": {
      "title": "Day the Tenth: Magnanimity",
      "text": "The final day arrives. Panfilo is king. His theme: tales of those who have performed some generous or magnificent deed.\n\nThe mood shifts. After nine days of wit and fortune and cleverness and tragedy and tricks, Day Ten lifts the Decameron to a different plane entirely.\n\n**Saladin** -- the great Muslim sultan -- travels in disguise and receives hospitality from a Christian knight, **Messer Torello**. Years later, when Torello is captured in the Crusades, Saladin recognizes him and returns the kindness a hundredfold. The tale crosses every boundary -- religion, culture, war -- and says that true courtesy knows no borders.\n\nTheo listens to tale after tale of people who give beyond what anyone could ask. A chain of generosity where each act of sacrifice inspires the next.\n\nThen Dioneo stands. He always tells the last tale. And the last tale of the entire Decameron is...",
      "choices": [
        {
          "text": "Listen to the tale of Patient Griselda",
          "target": "act7_griselda"
        },
        {
          "text": "Ask why the most irreverent narrator tells the final tale",
          "target": "act7_griselda_question"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day10_virtue",
      "vocabulary": [
        {
          "term": "Saladin",
          "definition": "The great Muslim sultan (1137-1193) who appears twice in the Decameron -- once in the tale of the Three Rings (I.3) and once in the tale of Messer Torello (X.9). Boccaccio portrays him as the embodiment of cross-cultural courtesy and magnanimity."
        },
        {
          "term": "Messer Torello",
          "definition": "The Christian knight of Novel X.9 whose generous hospitality to a disguised Saladin is repaid magnificently -- a tale of mutual respect across the divide of the Crusades."
        }
      ],
      "figures": [
        "Panfilo",
        "Saladin",
        "Messer Torello",
        "Dioneo"
      ],
      "tags": [
        "day10",
        "magnanimity",
        "summit",
        "convergence"
      ]
    },
    "act7_griselda_question": {
      "title": "Why Dioneo?",
      "text": "'Why does Dioneo tell the last tale?' Theo asks Filomena.\n\n'Because it's the most unsettling tale in the entire Decameron,' she says. 'And only the most irreverent voice can deliver it without it being unbearable.'\n\n'What do you mean?'\n\n'The tale is called **Patient Griselda**. A marquis marries a peasant girl and then tests her obedience with escalating cruelty. He takes away her children. He pretends they're dead. He pretends to divorce her and marry another woman. Through it all, Griselda endures without complaint. In the end, he reveals it was all a test and reunites her with her children.'\n\nTheo is appalled. 'That's monstrous.'\n\n'Is it?' Filomena says. 'Or is it the most radical statement about virtue in the entire book? *If* Griselda represents the human soul being tested by God -- as Petrarch later argued -- then the tale is an allegory. But if you read it as a story about a real woman and a real husband... it's a horror story.'\n\n'Boccaccio wants you to hold both readings at once.'",
      "choices": [
        {
          "text": "Listen to the tale yourself and decide",
          "target": "act7_griselda"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day10_virtue",
      "vocabulary": [
        {
          "term": "Patient Griselda",
          "definition": "The subject of Novel X.10 -- the final and most debated tale of the Decameron. A peasant woman endures her husband's escalating cruelty with perfect patience. Read as allegory (the soul tested by God) or as realism (domestic abuse), the tale has provoked argument for seven centuries."
        }
      ],
      "figures": [
        "Filomena",
        "Dioneo",
        "Griselda"
      ],
      "tags": [
        "day10",
        "griselda",
        "setup"
      ]
    },
    "act7_griselda": {
      "title": "Patient Griselda",
      "text": "Dioneo tells the tale. His voice, usually light and mocking, is careful now. He tells of the Marquis of Saluzzo who chose Griselda from among the poorest of the poor and married her -- then spent years testing her patience with unthinkable cruelty.\n\nThe brigata listens in horrified silence. When the tale ends and the marquis reveals the 'test,' Dioneo adds: 'Perhaps it would have served him right if, when he drove her from his house in her shift, she had found someone else to shake her fur and get a fine dress out of the bargain.'\n\nThe garden erupts. Pampinea calls the marquis a monster. Filostrato says the tale proves that love requires suffering. Neifile says Griselda's patience is superhuman and therefore meaningless as a model. Filomena says the tale is Boccaccio's final riddle -- an unanswerable question planted like a seed that will grow in the reader's mind forever.\n\nThey all turn to Theo.",
      "choices": [
        {
          "text": "Griselda's patience is a kind of strength -- she endured and won",
          "target": "end_patience_reading"
        },
        {
          "text": "The tale is a warning -- obedience without limits is not virtue, it's submission",
          "target": "end_critical_reading"
        },
        {
          "text": "Boccaccio doesn't want us to choose -- the tale's power is in the argument itself",
          "target": "end_literary_reading"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "day10_virtue",
      "vocabulary": [],
      "figures": [
        "Dioneo",
        "Griselda",
        "Pampinea",
        "Filostrato",
        "Neifile",
        "Filomena"
      ],
      "tags": [
        "day10",
        "griselda",
        "climax",
        "key_decision"
      ]
    },
    "end_plague_courage": {
      "title": "The Courage That Stays",
      "text": "Theo stays in Florence. He works with the friar until the bread runs out, then with the gravediggers, then with the nuns at the hospital of Santa Maria Nuova. He sees things no one should see. He holds hands that will never be held again.\n\nHe never hears the hundred tales. He never learns about Federigo's falcon or Ghismonda's defiance or Fra Cipolla's magnificent lies. He never reaches Day Ten.\n\nBut one evening, sitting by the Arno as the plague finally begins to retreat, a woman starts to tell a story. It's simple -- about a man who lost everything and found something better. The survivors listen. For the first time in months, someone laughs.\n\nTheo understands then what Pampinea was trying to tell him: stories don't replace courage. But they're what courage sounds like when the worst is over.\n\nThe golden light returns. The marble bench. The textbook open on his desk. Theo stares at the chapter about Boccaccio with new eyes. The tales are still waiting for him. And now he knows why they were written.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "return",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good",
        "courage",
        "plague"
      ]
    },
    "end_patience_reading": {
      "title": "The Strength in Patience",
      "text": "'Griselda won,' Theo says. 'Not by fighting, not by running, not by being clever. She endured. And in the end, the marquis was the one who broke -- he couldn't sustain his cruelty forever. Patience outlasted power.'\n\nFilostrato nods. Pampinea looks unconvinced. Dioneo laughs and says, 'A charitable reading! But I like it.'\n\nThe tenth day ends. The hundred tales are told. Tomorrow the brigata will return to Florence. The plague is not over, but something has been built in this garden -- an architecture of stories that moves from the darkest comedy to the highest virtue.\n\nThat night, walking in the garden alone, Theo feels the golden light begin to shift. The lemon trees blur. The fountain's sound becomes the hum of an air conditioner.\n\nHe's back at his desk. The textbook is open. But the tales are alive in him now -- not as words on a page but as voices. Pampinea's authority. Dioneo's laughter. Filomena's quiet wisdom. Ghismonda's defiance. Griselda's impossible patience.\n\nHe picks up a pen and begins to write.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "return",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good",
        "patience",
        "traditional"
      ]
    },
    "end_critical_reading": {
      "title": "The Reader as Judge",
      "text": "'No,' Theo says. 'Griselda's patience isn't virtue. It's a trap. If the tale teaches us that a woman should endure anything a man inflicts on her, then it's teaching cruelty dressed as morality.'\n\nPampinea stands up. 'Yes. That's what I've been trying to say all along. The Decameron gives us a hundred tales -- some brilliant, some troubling, some both. Our job isn't to accept them. It's to argue with them.'\n\nDioneo grins. 'That's exactly what I hoped someone would say. Why do you think I told the tale? Not to praise Griselda. To make you angry enough to think.'\n\nThe tenth day ends. The tales are told. But the argument, Theo realizes, is only beginning. That's the genius of the Decameron -- it doesn't end when you close the book. It ends when you stop thinking about it, and you never quite do.\n\nThe golden light shifts. The garden dissolves. Theo is at his desk, pen in hand, writing furiously in the margin of his textbook: 'The tale is not the lesson. The argument about the tale is the lesson.'",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "return",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "best",
        "critical_reading",
        "agency"
      ]
    },
    "end_literary_reading": {
      "title": "One Hundred Questions",
      "text": "Theo looks at the expectant faces. 'I think... Boccaccio doesn't want us to solve Griselda. He wants us to carry her. Like a question you can't put down.'\n\nFilomena smiles. 'Go on.'\n\n'Every tale in the Decameron is like that. Ciappelletto -- is it comedy or horror? Federigo's falcon -- is it love or madness? Ghismonda -- is she a hero or a victim? The Decameron isn't one hundred answers. It's one hundred questions. And the real story isn't in the garden -- it's in the reader who has to live with the questions afterward.'\n\nThe brigata is quiet. Then Pampinea speaks: 'That's the most truthful thing anyone has said in ten days. Perhaps we should have made you king.'\n\nDioneo laughs. 'King of questions! The worst kind of king -- the one who makes you think instead of giving you answers.'\n\nThe golden light floods the garden. The fountain blurs into a desk lamp. Theo is sitting in his chair, the textbook open to the page about the **frame narrative** -- ten young people in a garden, telling stories while the plague rages.\n\nHe understands now. The stories aren't an escape from the plague. They're the only honest response to it. One hundred tales. One hundred questions. And a seventeen-year-old boy who will never read a story the same way again.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "return",
      "vocabulary": [
        {
          "term": "Frame narrative",
          "definition": "A story within a story. The Decameron's frame narrative -- ten young people fleeing the plague and telling tales in a garden -- is not just a device but the key to understanding the work: storytelling as a response to catastrophe, order imposed on chaos, human connection maintained when all other bonds have dissolved."
        }
      ],
      "figures": [],
      "tags": [
        "ending",
        "best",
        "literary_reading",
        "synthesis"
      ]
    },
    "end_neutral": {
      "title": "A Pleasant Sojourn",
      "text": "Theo spent ten days in the villa. He heard the tales. He ate the food. He walked in the garden. It was pleasant.\n\nBut when the golden light returns and deposits him at his desk, he finds that the tales have already begun to fade. He remembers the falcon, vaguely. Something about rings. A patient woman. The details dissolve like morning mist.\n\nHe closes the textbook and reaches for his phone. The Decameron will be on the test, probably. He should look up a summary.\n\nHe never quite realizes what he missed.",
      "choices": [],
      "is_ending": true,
      "ending_type": "neutral",
      "era": "return",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "neutral",
        "passive"
      ]
    }
  },
  "start_node": "start",
  "edges": [
    [
      "start",
      "act1_plague_join_brigata"
    ],
    [
      "start",
      "act1_plague_stay_florence"
    ],
    [
      "act1_plague_join_brigata",
      "act2_day1_tell_tale"
    ],
    [
      "act1_plague_join_brigata",
      "act2_day1_listen"
    ],
    [
      "act1_plague_stay_florence",
      "act1_plague_late_arrival"
    ],
    [
      "act1_plague_stay_florence",
      "end_plague_courage"
    ],
    [
      "act1_plague_late_arrival",
      "act2_day1_tell_tale"
    ],
    [
      "act1_plague_late_arrival",
      "act2_day1_listen"
    ],
    [
      "act2_day1_tell_tale",
      "act2_day1_wit_tale"
    ],
    [
      "act2_day1_tell_tale",
      "act2_day1_plague_tale"
    ],
    [
      "act2_day1_listen",
      "act2_day1_dioneo_talk"
    ],
    [
      "act2_day1_listen",
      "act2_day1_filomena_talk"
    ],
    [
      "act2_day1_listen",
      "end_neutral"
    ],
    [
      "act2_day1_wit_tale",
      "act3_cleverness_debate"
    ],
    [
      "act2_day1_wit_tale",
      "act3_garden_wall"
    ],
    [
      "act2_day1_plague_tale",
      "act3_garden_wall"
    ],
    [
      "act2_day1_plague_tale",
      "act3_truth_matters"
    ],
    [
      "act2_day1_dioneo_talk",
      "act3_garden_wall"
    ],
    [
      "act2_day1_dioneo_talk",
      "act3_cleverness_debate"
    ],
    [
      "act2_day1_filomena_talk",
      "act3_truth_matters"
    ],
    [
      "act2_day1_filomena_talk",
      "act3_cleverness_debate"
    ],
    [
      "act3_cleverness_debate",
      "act4_fortune_path"
    ],
    [
      "act3_cleverness_debate",
      "act4_tragedy_path"
    ],
    [
      "act3_garden_wall",
      "act4_tragedy_path"
    ],
    [
      "act3_garden_wall",
      "act4_fortune_path"
    ],
    [
      "act3_truth_matters",
      "act4_tragedy_path"
    ],
    [
      "act3_truth_matters",
      "act4_fortune_path"
    ],
    [
      "act4_fortune_path",
      "act5_sacrifice_noble"
    ],
    [
      "act4_fortune_path",
      "act5_sacrifice_troubling"
    ],
    [
      "act4_tragedy_path",
      "act5_ghismonda_right"
    ],
    [
      "act4_tragedy_path",
      "act5_tragedy_complex"
    ],
    [
      "act5_sacrifice_noble",
      "act6_day6_speech"
    ],
    [
      "act5_sacrifice_noble",
      "act7_day10_magnanimity"
    ],
    [
      "act5_sacrifice_troubling",
      "act6_day6_speech"
    ],
    [
      "act5_sacrifice_troubling",
      "act6_optimist_pessimist"
    ],
    [
      "act5_ghismonda_right",
      "act6_day6_speech"
    ],
    [
      "act5_ghismonda_right",
      "act6_cruel_tales"
    ],
    [
      "act5_tragedy_complex",
      "act6_day6_speech"
    ],
    [
      "act5_tragedy_complex",
      "act6_optimist_pessimist"
    ],
    [
      "act6_day6_speech",
      "act7_day10_magnanimity"
    ],
    [
      "act6_day6_speech",
      "act6_wit_vs_fraud"
    ],
    [
      "act6_optimist_pessimist",
      "act7_day10_magnanimity"
    ],
    [
      "act6_optimist_pessimist",
      "act6_day6_speech"
    ],
    [
      "act6_cruel_tales",
      "act7_day10_magnanimity"
    ],
    [
      "act6_cruel_tales",
      "act6_day6_speech"
    ],
    [
      "act6_wit_vs_fraud",
      "act7_day10_magnanimity"
    ],
    [
      "act6_wit_vs_fraud",
      "act7_griselda_question"
    ],
    [
      "act7_day10_magnanimity",
      "act7_griselda"
    ],
    [
      "act7_day10_magnanimity",
      "act7_griselda_question"
    ],
    [
      "act7_griselda_question",
      "act7_griselda"
    ],
    [
      "act7_griselda",
      "end_patience_reading"
    ],
    [
      "act7_griselda",
      "end_critical_reading"
    ],
    [
      "act7_griselda",
      "end_literary_reading"
    ]
  ]
};
