// Auto-generated by story_graph.py — do not edit by hand
const STORY_DATA = {
  "nodes": {
    "start": {
      "title": "The Closing Bookshop",
      "text": "Sam is twenty-two, an English major with a creative-writing concentration, and has not written a decent sentence in three weeks. Tomorrow is the Modern Short Stories final -- an essay exam: 'What did Chekhov, Joyce, and Hemingway change about fiction, and why does it matter?'\n\nThe campus bookshop is closing in ten minutes. Sam is curled in the back corner with three paperbacks fanned open on the carpet: a Chekhov collection, *Dubliners*, and *Men Without Women*. The fluorescent lights buzz. The owner calls out: '*Five minutes!*'\n\nSam's eyes close. When they open, the bookshop is gone. Sam is sitting in a wooden chair in a room that smells of old paper and pipe smoke. The walls are bookshelves, floor to ceiling, and they are breathing -- spines expanding and contracting like sleeping lungs.\n\nA woman sits across a small table. She is ageless -- somewhere between thirty and seventy -- and she is shuffling three manuscripts like playing cards.\n\n'You want to know what changed,' she says. 'Good. But you cannot learn it by reading *about* stories. You have to go *inside*.'\n\nShe fans the three manuscripts on the table.",
      "choices": [
        {
          "text": "Ask what she means by 'inside'",
          "target": "act1_modern"
        },
        {
          "text": "Pick up the first manuscript -- it smells of salt air and cypress",
          "target": "act2_yalta"
        },
        {
          "text": "Pick up the middle one -- you hear distant piano music",
          "target": "act3_party"
        },
        {
          "text": "Pick up the last one -- it radiates dry heat",
          "target": "act4_station"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "frame",
      "vocabulary": [
        {
          "term": "modern short story",
          "definition": "Fiction after c. 1890 that shifted from 'What happens next?' to 'What does it feel like to be this person, in this moment?'"
        },
        {
          "term": "the modern turn",
          "definition": "The shift (c. 1890) in short fiction from plot mechanics to the texture of consciousness"
        }
      ],
      "figures": [],
      "tags": [
        "opening",
        "frame"
      ]
    },
    "act1_modern": {
      "title": "Before and After",
      "text": "'Before 1890,' the woman says, 'a story was a *machine for delivering an outcome*. Edgar Allan Poe said every sentence should drive toward a single preconceived effect. Guy de Maupassant built perfect little traps. O. Henry gave you twist endings like a magician pulling a rabbit from a hat.'\n\nShe sets a fourth manuscript on the table -- older, dog-eared. 'Read the last line of any of those and you knew exactly what the story meant. The writer told you. The ending was a closed door.'\n\n'Then Chekhov came along and *left the door open*. He wrote a story about a married man who has an affair at a seaside resort, and at the end nobody decides anything. The most important line is: *the most complicated and difficult part was only just beginning*. That is not an ending. That is a beginning disguised as an ending.'\n\nShe leans forward. 'Joyce took it further -- prose that does the work of poetry, snow falling on the living and the dead. And Hemingway went the opposite direction: he took everything *out*. One-eighth above the surface, seven-eighths below.'\n\n'Three writers. Three solutions to the same problem: how do you represent the inner lives of people who cannot or will not speak honestly?'\n\nShe pushes the three manuscripts toward Sam.",
      "choices": [
        {
          "text": "The salt-air manuscript -- start with Chekhov",
          "target": "act2_yalta"
        },
        {
          "text": "The one with piano music -- start with Joyce",
          "target": "act3_party"
        },
        {
          "text": "The dry-heat manuscript -- start with Hemingway",
          "target": "act4_station"
        },
        {
          "text": "I think I get the overview. That's probably enough.",
          "target": "end_surface"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "frame",
      "vocabulary": [
        {
          "term": "Edgar Allan Poe",
          "definition": "American writer (1809-1849) who argued every sentence in a short story should drive toward a single preconceived effect"
        },
        {
          "term": "single effect",
          "definition": "Poe's principle that a short story should be crafted so every element contributes to one unified emotional impression"
        },
        {
          "term": "twist ending",
          "definition": "A surprise reversal at the story's close (O. Henry, Maupassant) -- the technique modernism largely abandoned"
        }
      ],
      "figures": [],
      "tags": [
        "frame",
        "history"
      ]
    },
    "end_surface": {
      "title": "The Closed Book",
      "text": "Sam puts down the manuscripts. 'I think I get the general idea,' Sam says. 'Plot gave way to consciousness. Chekhov opened the door. Joyce made prose into poetry. Hemingway stripped it bare. I can write that on the exam.'\n\nThe woman looks at Sam for a long moment. 'You can summarize it,' she says. 'That is not the same as understanding it.'\n\nThe bookshelves stop breathing. The room folds up like a closing book. Sam wakes in the campus bookshop. The lights are off. The owner has gone.\n\nSam walks home in the dark, writes a competent exam essay the next morning, and gets a B+. It is a perfectly adequate grade. It is also, Sam suspects, exactly the kind of ending Chekhov would have refused to write -- neat, finished, and fundamentally dishonest about how things actually feel.\n\nThe three paperbacks sit on Sam's desk for years, spines uncracked after that night. Sometimes Sam picks one up and puts it down again.\n\nSome books wait.",
      "choices": [],
      "is_ending": true,
      "ending_type": "neutral",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "neutral"
      ]
    },
    "act2_yalta": {
      "title": "The Promenade at Yalta",
      "text": "Sam opens the manuscript and the page swallows the room.\n\nWarm air. Blinding light off the Black Sea. The promenade at Yalta is crowded with summer visitors -- women in white dresses, men in straw hats, the smell of coffee and dust and something floral Sam cannot name.\n\nA man leans against the railing, watching the crowd with practiced boredom. He is under forty, well-dressed, vaguely handsome. His name, Sam somehow knows, is Dmitri Dmitritch Gurov. He works at a bank in Moscow. He has a wife, three children, and a habit of calling women '*the lower race*' while being entirely unable to live without them.\n\nA young woman walks past with a small white Pomeranian. She is new here -- Sam can tell because she looks at the sea the way locals never do, as though it might contain an answer to something.\n\nGurov is already interested. '*There is something pathetic about her, anyway,*' he thinks. Or does the narrator think it? The line between Gurov's voice and the narrator's has blurred -- Sam cannot tell who is speaking.\n\nThis, Sam realizes, is a technique. And it has a name.",
      "choices": [
        {
          "text": "Follow the blurred voice -- whose thoughts are these?",
          "target": "act2_fid"
        },
        {
          "text": "Follow Anna and Gurov to the sea at night",
          "target": "act2_oreanda"
        },
        {
          "text": "Step back and watch from a distance -- what is this story really about?",
          "target": "act2_two_lives"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "chekhov",
      "vocabulary": [
        {
          "term": "Dmitri Dmitritch Gurov",
          "definition": "Protagonist of 'The Lady with the Dog' -- a serial adulterer who, past forty, falls genuinely in love for the first time"
        },
        {
          "term": "Anna Sergeyevna",
          "definition": "The 'lady with the dog' -- young, married, guilt-ridden, sincere; Gurov's lover at Yalta"
        },
        {
          "term": "Yalta",
          "definition": "Black Sea resort town where Gurov and Anna's affair begins -- a place out of time where ordinary rules feel suspended"
        }
      ],
      "figures": [],
      "tags": [
        "chekhov",
        "opening"
      ]
    },
    "act2_fid": {
      "title": "Whose Voice Is This?",
      "text": "Sam listens more carefully. Gurov is watching Anna across a restaurant table. She is telling him about her husband, whom she calls '*a flunkey*.' The narrator reports: '*His wife seemed to him half as long again as he.*'\n\nWait. Is that the narrator's observation, or Gurov's resentful perception of his own wife back in Moscow? It is both at once. The narrator has borrowed Gurov's voice without using quotation marks, without announcing '*Gurov thought*.' The reader is thinking alongside the character without knowing where the boundary is.\n\nThis is *free indirect discourse* -- and Chekhov deploys it like a magician. When Gurov dismisses women as 'the lower race,' is that Chekhov's view? Of course not. But Chekhov never *says* it is wrong. He lets us hear the thought, lets us sit with it, and trusts us to recognize the gap between what Gurov believes about himself and what is actually true.\n\nSam suddenly understands: Chekhov is not telling us what to think. He is creating a window into Gurov's mind and letting us look through it -- biases, self-deceptions, and all. The reading is the judgment.",
      "choices": [
        {
          "text": "Follow Anna and Gurov to the sea at Oreanda",
          "target": "act2_oreanda"
        },
        {
          "text": "Jump ahead to Moscow -- see what happens when the holiday ends",
          "target": "act2_sturgeon"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "chekhov",
      "vocabulary": [
        {
          "term": "free indirect discourse",
          "definition": "Narrative technique where the narrator borrows a character's voice and thoughts without quotation marks, blurring the line between narrator and character"
        },
        {
          "term": "the lower race",
          "definition": "Gurov's dismissive term for women -- Chekhov lets us hear this thought without editorial comment, trusting the reader to judge"
        },
        {
          "term": "unreliable narrator",
          "definition": "A narrator whose account the reader has reason to question due to bias, self-deception, or limited knowledge"
        }
      ],
      "figures": [],
      "tags": [
        "chekhov",
        "technique"
      ]
    },
    "act2_oreanda": {
      "title": "The Sea at Oreanda",
      "text": "Night. Sam stands on the cliff at Oreanda while Gurov and Anna sit on a bench nearby, the affair already begun. Below them, the sea makes what Chekhov calls a '*monotonous, hollow sound*' -- and then the narrative lifts, suddenly, into something enormous:\n\n'*The monotonous hollow sound of the sea rising up from below, spoke of the peace, of the eternal sleep awaiting us. So it must have sounded when there was no Yalta, no Oreanda here; so it sounds now, and it will sound as indifferently and monotonously when we are all no more.*'\n\nSam feels the scale shift. A moment ago this was a story about two people having an affair. Now it is about time, mortality, the indifference of the natural world to human feeling. Chekhov has done this in a single paragraph -- opened a trapdoor beneath a love scene and dropped both characters and reader into something vast.\n\nAnna turns to Gurov. '*I wanted to live! To live, to live!*' she says. And the word *live* suddenly carries more weight than it did a page ago, because the sea has just reminded us that living is temporary.\n\nSam realizes: setting in Chekhov is not decoration. It is emotional landscape.",
      "choices": [
        {
          "text": "Stay with the affair -- watch it deepen toward something real",
          "target": "act2_sturgeon"
        },
        {
          "text": "Ask what Chekhov is doing with place -- Yalta vs. Moscow, warmth vs. cold",
          "target": "act2_two_lives"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "chekhov",
      "vocabulary": [
        {
          "term": "Oreanda",
          "definition": "Cliffside near Yalta where Gurov and Anna sit by the sea; the story's meditation on eternity happens here"
        },
        {
          "term": "setting as emotional landscape",
          "definition": "Chekhov's technique of using physical setting to externalize inner states -- Yalta = warmth and possibility; Moscow = cold and obligation"
        },
        {
          "term": "motif",
          "definition": "A recurring image or symbol that develops meaning through repetition (the sea, snow, hills)"
        }
      ],
      "figures": [],
      "tags": [
        "chekhov",
        "setting"
      ]
    },
    "act2_sturgeon": {
      "title": "The Sturgeon Moment",
      "text": "Moscow. Winter. Everything grey.\n\nGurov has returned from Yalta expecting the affair to fade like all the others. It does not. The memory of Anna grows *more* vivid, not less. He sees her face in the evenings, hears her breathing in the silence of his study. He cannot tell anyone.\n\nOne night at his club, Gurov cannot bear it. He turns to a colleague and says, desperately: '*If only you knew what a fascinating woman I met in Yalta!*'\n\nThe man puts down his fork and replies: '*You were right this evening: the sturgeon was a bit too strong!*'\n\nSam watches Gurov's face in the silence that follows. This is one of the loneliest exchanges in short fiction. Gurov's real experience -- the only thing that matters to him -- has no audience. His social world cannot accommodate what he feels. The sturgeon remark is not cruelty; it is indifference, which is worse.\n\nAfter this, Gurov takes a train to Anna's provincial town. He stands outside her house. A grey fence with nails on top. '*He would have called out to her, he would have thrown stones at the window,*' the narrator says -- and the desperation is unmistakable, because Gurov the practiced, cynical seducer has become Gurov the genuinely helpless lover.\n\nThe man who called women '*the lower race*' cannot sleep for thinking about one.",
      "choices": [
        {
          "text": "Follow Gurov to the theater where he finds Anna",
          "target": "act2_two_lives"
        },
        {
          "text": "This isolation -- step back and see the full architecture",
          "target": "act2_ending"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "chekhov",
      "vocabulary": [
        {
          "term": "the sturgeon moment",
          "definition": "Gurov's failed attempt to share his real experience with a colleague who responds with small talk about fish -- emblematic of social isolation"
        },
        {
          "term": "realism",
          "definition": "Fiction representing life as actually lived, without idealization or sentimentality; ordinary people in recognizable settings"
        }
      ],
      "figures": [],
      "tags": [
        "chekhov",
        "isolation"
      ]
    },
    "act2_two_lives": {
      "title": "Two Lives",
      "text": "Sam sees Gurov at the center of two worlds that cannot touch each other.\n\nIn one: the bank, the club, the wife who spells words phonetically, the dinners where people talk about sturgeon. This is the public life -- 'full of conventional truth and conventional deception, exactly like the lives of his friends and acquaintances.'\n\nIn the other: Anna. Secret meetings at the Slaviansky Bazaar hotel in Moscow. Her grey dress. His greying hair. Both older now. Both trapped. Both real.\n\n'*Everything that was essential, of interest and of value to him, everything in which he was sincere and did not deceive himself, everything that made the kernel of his life, was hidden from other people.*'\n\nSam reads that sentence twice. It is the key to the entire story. Gurov's authentic self exists only in secret. His public self is a performance. And the story's quiet argument is that this is not unusual -- that most people live this way, carrying their real selves like contraband.\n\nChekhov does not judge Gurov for the affair. He does not judge Anna for her tears. He does not even judge the colleague and his sturgeon. He simply shows what it looks like when a person's inner life has nowhere to go.",
      "choices": [
        {
          "text": "Read the ending -- how does Chekhov close an uncloseable story?",
          "target": "act2_ending"
        },
        {
          "text": "You've seen enough of Chekhov. Go to Joyce's Dublin.",
          "target": "act3_party"
        },
        {
          "text": "You've seen enough of Chekhov. Go to Hemingway's Spain.",
          "target": "act4_station"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "chekhov",
      "vocabulary": [
        {
          "term": "public self vs. private self",
          "definition": "Gurov's two lives: the conventional social performance and the hidden authentic self that exists only in the affair"
        },
        {
          "term": "naturalism",
          "definition": "Related to realism; emphasizes environment, heredity, and social conditions shaping characters -- Chekhov shares some naturalist concerns but resists determinism"
        }
      ],
      "figures": [],
      "tags": [
        "chekhov",
        "theme"
      ]
    },
    "act2_ending": {
      "title": "Only Just Beginning",
      "text": "The final scene. A hotel room. Anna is crying. Gurov looks in the mirror and sees that his hair is grey. '*Only now when his head was grey had he fallen properly, really in love -- for the first time in his life.*'\n\nSam waits for the resolution. Gurov will leave his wife. Or Anna will leave her husband. Or they will be discovered. Or they will part forever. Something will *happen*.\n\nNothing happens. The final line reads: '*And it seemed as though in a little while the solution would be found, and then a new and splendid life would begin; and it was clear to both of them that they had still a long, long road before them, and that the most complicated and difficult part of it was only just beginning.*'\n\nSam stares at the page. That is not an ending. That is a refusal to end. Chekhov has spent thirty pages making us care about these two people and then he *leaves them there*, mid-sentence, mid-life, mid-problem.\n\nBut Sam realizes: that IS the honesty. Resolution would be false. Life does not resolve. The greatest love story of the nineteenth century ends with two people in a hotel room who have no idea what to do next.\n\nThe manuscript shimmers. The text fades. Sam is back in the room with the breathing bookshelves.",
      "choices": [
        {
          "text": "Pick up the Joyce manuscript -- hear the piano music",
          "target": "act3_party"
        },
        {
          "text": "Pick up the Hemingway manuscript -- feel the dry heat",
          "target": "act4_station"
        },
        {
          "text": "You're ready to understand what all three share",
          "target": "act5_methods"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "chekhov",
      "vocabulary": [
        {
          "term": "the unresolved ending",
          "definition": "Chekhov's signature: refusing narrative closure because resolution would be false to how life actually works"
        },
        {
          "term": "denouement",
          "definition": "The final stage of a narrative where loose threads are gathered -- in modern fiction, often deliberately absent or incomplete"
        }
      ],
      "figures": [],
      "tags": [
        "chekhov",
        "ending"
      ]
    },
    "act3_party": {
      "title": "The Annual Dance",
      "text": "Sam opens the manuscript and falls into noise, warmth, and the smell of goose fat.\n\nIt is the Misses Morkan's annual dance on Usher's Island, Dublin. Christmas or New Year -- the house is packed. Lily, the caretaker's daughter, is 'literally run off her feet.' Upstairs, Aunt Kate and Aunt Julia -- elderly, devoted to music and hospitality -- are receiving guests.\n\nA man arrives: Gabriel Conroy, their nephew. He is stout, tallish, wears gilt-rimmed glasses, and is immediately anxious. He tries a joke with Lily about her love life. She replies bitterly: '*The men that is now is only all palaver and what they can get out of you.*' Gabriel is flustered. He gives her a coin, which makes it worse.\n\nSam watches Gabriel move through the party like a man walking on ice -- every step calculated, every gesture a performance. He is preparing a speech. He is worried about quoting Browning (too intellectual for his audience?). He is already rehearsing and revising in his head.\n\nSomething about Gabriel reminds Sam of every social gathering where the real self stays hidden behind a polished front. Joyce is building something here. Sam can feel the weight of it, even though nothing dramatic has happened.",
      "choices": [
        {
          "text": "Watch Gabriel clash with Miss Ivors",
          "target": "act3_gabriel"
        },
        {
          "text": "Listen to the music -- Aunt Julia is about to sing",
          "target": "act3_music"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "joyce",
      "vocabulary": [
        {
          "term": "Gabriel Conroy",
          "definition": "Protagonist of 'The Dead' -- teacher, book reviewer, husband to Gretta; anxious, self-conscious, prone to seeing others as images rather than people"
        },
        {
          "term": "paralysis",
          "definition": "Joyce's word for Dublin's spiritual condition -- the inability to act, change, or leave; the central subject of Dubliners"
        },
        {
          "term": "Dubliners",
          "definition": "Joyce's 1914 short story collection; 'The Dead' is the last and longest story, written in Trieste at age 25"
        }
      ],
      "figures": [],
      "tags": [
        "joyce",
        "opening"
      ]
    },
    "act3_gabriel": {
      "title": "West Briton",
      "text": "Miss Molly Ivors corners Gabriel during the lancers. She is a nationalist, firm-jawed, wearing a brooch with an Irish motto. She has read Gabriel's book reviews in *The Daily Express* -- a pro-British paper.\n\n'*Why do you write for that rag?*' she asks. Then, smiling: '*Aren't you ashamed of yourself?*'\n\nShe calls him a '*West Briton*' -- an Irishman who has turned his back on Ireland. She invites him to the Aran Isles for the summer. Gabriel, who prefers France and Belgium, stumbles through a defense: '*Irish is not my language.*' Then, sharper than he intends: '*I'm sick of my own country, sick of it!*'\n\nSam watches the exchange with fascination. This is not just a personal quarrel -- it is the Irish Question compressed into a dance. Gabriel's relationship to Ireland is ambivalent: he lives there but faces east, toward the Continent, toward culture, away from the west of Ireland where his wife Gretta grew up.\n\nJoyce wrote this story in Trieste -- an exile writing about a country he left but could never stop writing about. Sam begins to wonder whether Gabriel is Joyce's self-portrait, and whether the story is about to judge him.\n\nMiss Ivors leaves before supper. Gabriel feels relieved. He should not.",
      "choices": [
        {
          "text": "Listen to the music and watch Joyce's accumulation method",
          "target": "act3_music"
        },
        {
          "text": "Skip to Gabriel's speech -- see the performance",
          "target": "act3_staircase"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "joyce",
      "vocabulary": [
        {
          "term": "West Briton",
          "definition": "Derogatory term for an Irish person perceived as culturally aligned with Britain rather than Irish nationalism"
        },
        {
          "term": "Miss Molly Ivors",
          "definition": "Nationalist who confronts Gabriel about his Anglophile tendencies; her challenge destabilizes his self-image"
        },
        {
          "term": "The Daily Express",
          "definition": "Pro-British newspaper Gabriel reviews for; his association with it marks his political ambivalence"
        }
      ],
      "figures": [],
      "tags": [
        "joyce",
        "politics"
      ]
    },
    "act3_music": {
      "title": "Arrayed for the Bridal",
      "text": "Aunt Julia stands to sing. She is old -- grey hair, a face that looks 'like a shrivelled red apple' in the gaslight. She sings '*Arrayed for the Bridal*' and her voice, though fading, fills the room.\n\nSam listens. There is something devastating about the song choice -- a wedding song, sung by an elderly woman whose life of music and devotion to the Church is nearly over. Joyce does not underline the irony. He trusts the reader to hear it.\n\nAfter the song, the guests discuss the old Italian opera companies that used to come to Dublin. '*The old singers,*' someone says, their voices now only memories. The party is saturated with music, and every piece of music points backward -- to voices that are gone, to Dublin as it used to be, to a world that is passing.\n\nSam understands Joyce's method now. It is *accumulation* -- layering detail on detail, image on image, until meaning emerges from the sheer weight of what has been gathered. There is no plot driving forward. There is only the party, growing denser and more alive, and beneath it the slow, quiet pressure of time passing.\n\nThe party IS the story. At least, Sam thinks it is. That thought will turn out to be wrong.",
      "choices": [
        {
          "text": "The party is ending -- follow Gabriel to the staircase",
          "target": "act3_staircase"
        },
        {
          "text": "Step back -- what is Joyce building with all this density?",
          "target": "act3_staircase"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "joyce",
      "vocabulary": [
        {
          "term": "accumulation",
          "definition": "Joyce's narrative method: layering detail upon detail until meaning emerges from the weight of what has been gathered, rather than from plot"
        },
        {
          "term": "Aunt Julia Morkan",
          "definition": "Elderly hostess; her performance of 'Arrayed for the Bridal' -- a wedding song sung by an ageing woman -- carries unspoken irony"
        },
        {
          "term": "stream of consciousness",
          "definition": "Continuous, unedited flow of a character's thought; Joyce developed this technique fully in Ulysses, with traces in 'The Dead'"
        }
      ],
      "figures": [],
      "tags": [
        "joyce",
        "music"
      ]
    },
    "act3_staircase": {
      "title": "Distant Music",
      "text": "The party is ending. Guests are leaving. Gabriel stands at the foot of the stairs and looks up.\n\nHis wife Gretta is standing motionless on the landing, one hand on the banister, her head tilted. She is listening to something: a tenor, Bartell D'Arcy, singing '*The Lass of Aughrim*' in the room above.\n\nGabriel looks at her and thinks: '*If he were a painter he would paint her in that attitude. Distant Music he would call the picture.*'\n\nSam freezes. There it is. Gabriel is composing an *image* of his wife. He is turning a living woman into a painting, a title, an aesthetic object. He is not wondering what she is feeling. He is not asking why she has stopped. He is framing her.\n\nJoyce is setting a trap -- and Sam can see it, and Gabriel cannot. Joyce has let us share Gabriel's romanticized vision so completely that when truth arrives, the fall will be devastating.\n\nIn the cab, Gabriel is full of desire. He recalls 'moments of their secret life together, that no one knew of or would ever know of.' He is building a romantic narrative. The hotel room awaits.",
      "choices": [
        {
          "text": "Follow them to the hotel room -- watch the trap spring",
          "target": "act3_furey"
        },
        {
          "text": "Consider Gabriel's habit of composing images of people",
          "target": "end_aesthetic"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "joyce",
      "vocabulary": [
        {
          "term": "Distant Music",
          "definition": "The title Gabriel mentally gives to the 'painting' of Gretta on the stairs -- reveals his habit of aestheticizing people rather than truly seeing them"
        },
        {
          "term": "The Lass of Aughrim",
          "definition": "Irish ballad about a woman abandoned by her lover; sung by Bartell D'Arcy at the party, it triggers Gretta's buried memory of Michael Furey"
        },
        {
          "term": "Gretta Conroy",
          "definition": "Gabriel's wife, from Connacht (western Ireland); carries a secret grief that will shatter Gabriel's self-image"
        }
      ],
      "figures": [],
      "tags": [
        "joyce",
        "staircase"
      ]
    },
    "act3_furey": {
      "title": "Michael Furey",
      "text": "The Gresham Hotel. Gabriel is full of desire. He calls to Gretta. She is distracted, distant. She kisses him suddenly: '*You are a very generous person, Gabriel.*'\n\nHe thinks she is yielding. She is not.\n\nShe begins to cry. He asks what is wrong. She says she has been thinking about the song -- '*The Lass of Aughrim.*' About a boy named Michael Furey. He lived in Galway. He was seventeen. He sang that song. He was ill, dying, and the night before Gretta left for the convent he came to see her in the rain.\n\n'*He said he did not want to live,*' she whispers. '*I think he died for me.*'\n\nHe died a week later. She has carried this for years -- privately, silently, inside a marriage Gabriel thought he understood.\n\nSam watches Gabriel's face as the truth lands. '*He saw himself as a ludicrous figure, acting as a pennyboy for his aunts, a nervous, well-meaning sentimentalist, orating to vulgarians and idealising his own clownish lusts.*'\n\nEverything Gabriel believed about himself -- his intelligence, his passion, his marriage -- cracks open. The deepest feeling in the marriage belongs to someone who is not in the room. Someone who has been dead since he was seventeen.\n\nAnd then something shifts. Gabriel does not collapse into self-pity. He thinks: '*Better pass boldly into that other world, in the full glory of some passion, than fade and wither dismally with age.*'",
      "choices": [
        {
          "text": "Watch the snow fall",
          "target": "act3_snow"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "joyce",
      "vocabulary": [
        {
          "term": "Michael Furey",
          "definition": "A boy from Galway who loved Gretta, came to see her in the rain while dying at seventeen; the hidden emotional center of 'The Dead'"
        },
        {
          "term": "epiphany",
          "definition": "Joyce's term: a sudden, often painful moment when a character (or reader) sees something clearly for the first time -- not a happy insight but a reckoning"
        },
        {
          "term": "pennyboy",
          "definition": "An errand-runner; Gabriel's self-lacerating word for what he has been all evening -- a performer, not a person"
        }
      ],
      "figures": [],
      "tags": [
        "joyce",
        "revelation"
      ]
    },
    "act3_snow": {
      "title": "The Living and the Dead",
      "text": "Gretta has cried herself to sleep. Gabriel stands at the window. Outside, snow is falling.\n\nJoyce's prose lifts into something that is no longer narrative. It is closer to music:\n\n'*Snow was general all over Ireland. It was falling on every part of the dark central plain, on the treeless hills, falling softly upon the Bog of Allen and, farther westward, softly falling into the dark mutinous Shannon waves. It was falling, too, upon every part of the lonely churchyard on the hill where Michael Furey lay buried.*'\n\nSam reads: '*His soul swooned slowly as he heard the snow falling faintly through the universe and faintly falling, like the descent of their last end, upon all the living and the dead.*'\n\nThe story has moved beyond Gabriel. Beyond Gretta and Michael Furey. Beyond Dublin. The snow is universal -- it falls on everything, the living and the dead alike, without distinction. The prose has become incantatory, almost hypnotic, specific nouns giving way to vast ones.\n\n'*One by one, they were all becoming shades.*'\n\nSam feels something break open. This is not just an ending. It is what prose can do when it stops being *about* something and starts *being* something -- when fiction does the work of poetry.\n\nThe manuscript dissolves. Sam is back in the room.",
      "choices": [
        {
          "text": "Pick up the Hemingway manuscript",
          "target": "act4_station"
        },
        {
          "text": "Go back to Chekhov -- see the connection",
          "target": "act2_yalta"
        },
        {
          "text": "You're ready to understand what all three share",
          "target": "act5_methods"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "joyce",
      "vocabulary": [
        {
          "term": "snow was general all over Ireland",
          "definition": "The celebrated final passage of 'The Dead'; snow becomes a universal image connecting the living and the dead, the personal and the cosmic"
        },
        {
          "term": "His soul swooned slowly",
          "definition": "Joyce's closing sentence -- prose becomes musical, incantatory; individual consciousness dissolves into something vast and impersonal"
        }
      ],
      "figures": [],
      "tags": [
        "joyce",
        "ending"
      ]
    },
    "end_aesthetic": {
      "title": "The Composed Image",
      "text": "Sam steps back from Joyce's Dublin and thinks about Gabriel's habit of composing images of people -- turning Gretta into '*Distant Music*,' turning his aunts into '*the Three Graces*,' turning every living person into an occasion for his own aesthetic response.\n\nIt is a tempting habit. Sam recognizes it: the writer's instinct to frame everything, to transform experience into material before truly feeling it. To look at a person and think *painting* instead of *who are you?*\n\nSam returns to the bookshop with this insight but does not go further. The exam essay is good -- observant, even stylish. But the short stories Sam writes afterward have a curious quality: beautifully composed, exquisitely observed, and somehow always about the writer rather than the subject.\n\nIt takes Sam years to recognize the problem. Gabriel's trap is also the writer's trap: you can see everything about another person except the fact that you are not really seeing them.\n\nThe snow, when it falls, falls on someone else.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "joyce",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good"
      ]
    },
    "act4_station": {
      "title": "Two Sides of the Valley",
      "text": "Sam opens the manuscript and arrives in heat.\n\nA railway station between Barcelona and Madrid, in the valley of the Ebro. It is blisteringly hot. There is a bar with a bamboo bead curtain. Two people sit at a table with two glasses of beer. They have no names -- the narrative calls them '*the American*' and '*the girl*' (later '*Jig*').\n\nThe girl looks at the hills across the valley. '*They look like white elephants,*' she says.\n\n'*I've never seen one,*' the man says.\n\n'*No, you wouldn't have.*'\n\nSam feels the edge in that reply -- one of the sharpest lines in all of short fiction. But what does it *mean*? The man is literal-minded, practical, incurious? He would not see wonder or strangeness because he does not look for it?\n\nSam looks at the two sides of the valley. On one side: '*brown and dry*' -- barren hills. On the other: '*fields of grain and trees along the banks of the Ebro*' -- fertile, alive. The couple sits between them.\n\nTwo landscapes. Two possible futures. Sam is beginning to understand what this story is about, though no one has said the word yet.\n\nNo one will.",
      "choices": [
        {
          "text": "Listen to what the couple is really talking about",
          "target": "act4_subtext"
        },
        {
          "text": "Focus on the power dynamics -- who is controlling this conversation?",
          "target": "act4_power"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "hemingway",
      "vocabulary": [
        {
          "term": "the American",
          "definition": "The unnamed man in 'Hills Like White Elephants'; he talks more, reassures relentlessly, and has already made up his mind"
        },
        {
          "term": "Jig",
          "definition": "The unnamed girl/woman; she sees the white elephants, names the emptiness, and is being managed rather than listened to"
        },
        {
          "term": "white elephant",
          "definition": "Something costly and burdensome that the owner cannot dispose of; the girl sees them in the hills -- the man does not"
        },
        {
          "term": "the two landscapes",
          "definition": "Barren hills on one side, fertile valley on the other -- Hemingway's physical embodiment of the two possible futures facing the couple"
        }
      ],
      "figures": [],
      "tags": [
        "hemingway",
        "opening"
      ]
    },
    "act4_subtext": {
      "title": "The Unspoken Word",
      "text": "The man says: '*It's really an awfully simple operation, Jig. It's not really an operation at all.*'\n\n'*I know. You just let the air in,*' she says.\n\nSam waits for someone to say the word. No one does. In 1,500 words of story, the word *abortion* never appears. Hemingway has built the entire narrative around a hole -- the most important thing is the thing that is never said.\n\nThis is the *iceberg principle* in action. Only one-eighth of the story is visible above the surface. The seven-eighths below -- the pregnancy, the relationship's history, the future -- is what gives it power. The reader is trusted to feel what is missing.\n\n'*Then I'll do it. Because I don't care about me,*' Jig says.\n\n'*What do you mean?*'\n\n'*I don't care about me.*'\n\nSam hears the flatness in her voice. She is not agreeing. She is surrendering. And the man, who has been reassuring her for ten minutes, cannot hear the difference -- or will not.\n\nThere is no narrator to explain this. No free indirect discourse. No snow passage. Just two people talking, and the abyss between what they say and what they mean.",
      "choices": [
        {
          "text": "Watch the power dynamics unfold",
          "target": "act4_power"
        },
        {
          "text": "Wait for the ending -- 'I feel fine'",
          "target": "act4_fine"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "hemingway",
      "vocabulary": [
        {
          "term": "iceberg principle",
          "definition": "Hemingway's theory: only one-eighth of a story is visible on the surface; the seven-eighths below (what is omitted) is what gives it power"
        },
        {
          "term": "subtext",
          "definition": "What characters mean but do not say; in Hemingway, subtext IS the story -- the surface dialogue is only the tip"
        }
      ],
      "figures": [],
      "tags": [
        "hemingway",
        "technique"
      ]
    },
    "act4_power": {
      "title": "He Said, She Said",
      "text": "Sam starts counting. The man speaks more than Jig. He initiates more topics. He returns to the operation again and again, even after she asks him to stop. His reassurances -- '*It's perfectly simple*,' '*I don't want you to do it if you don't want to*,' '*I wouldn't have you do it if you didn't want to*' -- have the quality of a sales pitch, not a conversation.\n\nHe is managing her. Not listening to her.\n\nThen Jig says something that cracks the story open:\n\n'*That's all we do, isn't it -- look at things and try new drinks?*'\n\nSam hears the desolation in it. She is naming the emptiness of their life -- a life of surfaces, of pleasures, of moving from place to place without roots or commitment. The operation is not an isolated decision; it is the latest instance of the same pattern. Another problem to be made to go away so they can move on to the next drink, the next hotel, the next country.\n\n'*And we could have all this,*' she says, looking at the fertile side of the valley. '*And we could have everything and every day we make it more impossible.*'\n\nThe man says: '*We can have everything.*'\n\n'*No, we can't.*'",
      "choices": [
        {
          "text": "Watch her reach the breaking point",
          "target": "act4_please"
        },
        {
          "text": "Consider the iceberg beneath this conversation",
          "target": "act4_fine"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "hemingway",
      "vocabulary": [
        {
          "term": "that's all we do",
          "definition": "Jig's devastating summary of their relationship -- a life of surfaces without depth, commitment, or consequence"
        },
        {
          "term": "power dynamics in dialogue",
          "definition": "Hemingway reveals character through who speaks more, who initiates topics, who concedes, and who refuses to hear"
        }
      ],
      "figures": [],
      "tags": [
        "hemingway",
        "power"
      ]
    },
    "act4_please": {
      "title": "Seven Pleases",
      "text": "The man will not stop. He keeps returning to the operation. He says he knows people who have had it done. He says everything will be fine afterward. He says it is the only thing bothering them.\n\nJig says:\n\n'*Would you please please please please please please please stop talking?*'\n\nSeven *please*s. Sam counts them. This is not a polite request. This is someone at the absolute end of what she can bear. The repetition does what exclamation marks and adverbs cannot -- it makes the reader feel the pressure, the relentlessness of being worn down by someone who calls their persistence concern.\n\nThe man says he will stop. Then: '*But I don't want you to. I don't care anything about it.*'\n\nHe has already contradicted himself. He cannot stop because stopping would mean accepting her silence as an answer, and her silence is not the answer he wants.\n\nHemingway gives us no interior monologue. No narrative judgment. Just the rhythm of who speaks and who falls silent, what gets repeated and what gets dropped. Sam is reading this the way you overhear a conversation at the next table in a restaurant -- catching everything, understanding everything, and unable to intervene.",
      "choices": [
        {
          "text": "Read the final line",
          "target": "act4_fine"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "hemingway",
      "vocabulary": [
        {
          "term": "seven pleases",
          "definition": "Jig's repeated 'please' -- not politeness but desperation; Hemingway uses repetition to convey emotional extremity without commentary"
        }
      ],
      "figures": [],
      "tags": [
        "hemingway",
        "climax"
      ]
    },
    "act4_fine": {
      "title": "I Feel Fine",
      "text": "The train is coming. The man carries their bags to the other side of the station. He stops at the bar and has a drink alone -- an anise, among people '*reasonably*' waiting for the train. That word '*reasonably*' does the work of an entire paragraph.\n\nHe returns to Jig. He asks if she feels better.\n\n'*I feel fine,*' she says. '*There's nothing wrong with me. I feel fine.*'\n\nThe story ends.\n\nSam stares at the last line. Is it genuine? Is she resigned? Is it a wall she has built to stop the conversation? Is she going to have the operation? Has she already decided not to? Hemingway does not say. The story closes on the same ambiguity it opened with -- two people, two landscapes, and a decision that the reader must infer because the writer has refused to make it for us.\n\n'*I feel fine*' is either the bravest or the most defeated sentence in American short fiction. Sam cannot decide which. Hemingway would say: that is exactly the point.\n\nThe manuscript goes white. The heat fades. Sam is back in the room with the breathing bookshelves, and the woman is waiting.",
      "choices": [
        {
          "text": "Pick up the Chekhov manuscript -- see what you missed",
          "target": "act2_yalta"
        },
        {
          "text": "Pick up the Joyce manuscript -- hear the piano",
          "target": "act3_party"
        },
        {
          "text": "You're ready. What do the three stories share?",
          "target": "act5_methods"
        },
        {
          "text": "You don't need more. Go home and write.",
          "target": "end_silence"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "hemingway",
      "vocabulary": [
        {
          "term": "I feel fine",
          "definition": "The final words of 'Hills Like White Elephants' -- ambiguous, undecidable; the reader must determine whether it is genuine, resigned, or a wall"
        },
        {
          "term": "reasonably",
          "definition": "Hemingway's single adverb describing the people at the bar -- it does the work of a paragraph by implying the man sees himself as the reasonable one"
        }
      ],
      "figures": [],
      "tags": [
        "hemingway",
        "ending"
      ]
    },
    "end_silence": {
      "title": "The Iceberg",
      "text": "Sam does not need the synthesis. Sam has felt it.\n\nThe bookshop rematerializes. It is dark. The owner is gone. Sam walks home with Hemingway's lesson branded into memory: the most powerful thing in a story is what you leave out.\n\nSam's final exam is sharp, spare, and slightly unnerving -- the professor writes '*Where did this come from?*' in the margin. The short stories Sam writes afterward are built like Hemingway's: surfaces that conceal depths, dialogue that means more than it says, endings that refuse to close.\n\nIt is a real skill. Readers praise the restraint, the precision, the way Sam's characters seem to vibrate with unsaid things.\n\nBut sometimes, late at night, Sam wonders whether restraint alone is enough. Whether there is something that Chekhov's compassion and Joyce's lyricism can reach that Hemingway's silence cannot. Whether the iceberg, for all its power, can ever make the reader feel what the snow passage feels -- that moment when prose stops being *about* something and starts *being* something.\n\nSeven-eighths below the surface is a great deal of power.\n\nIt is also a great deal of loneliness.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "hemingway",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good"
      ]
    },
    "act5_methods": {
      "title": "Three Methods",
      "text": "'Three writers,' the woman says. 'Three solutions to the same problem.'\n\nShe places the manuscripts side by side.\n\n'**Chekhov** gives you a window into the mind. Free indirect discourse. You think alongside the character -- hearing their biases, their self-deceptions, their rationalizations -- and the reading itself is the judgment. He trusts you to see what Gurov cannot see about himself.'\n\n'**Joyce** gives you immersion. A wide, anxious field of awareness -- the party, the music, Gabriel's nerves -- layered and layered until the weight of accumulation makes the final revelation land with its full force. Without twenty pages of party, the snow would be a trick. With them, it is devastating.'\n\n'**Hemingway** gives you a closed door. No interiority at all. Surface only -- dialogue, gesture, landscape. The reader must infer everything. Silence is not the absence of meaning; it is where meaning lives.'\n\nShe looks at Sam. 'All three solve the same problem: how to represent the inner lives of people who cannot or will not speak honestly. Gurov cannot admit he is in love. Gabriel cannot see his wife as a separate person. Jig cannot make the man hear her. The stories *make you feel* what the characters cannot say.'\n\n'The question,' she says, 'is what you do with that.'",
      "choices": [
        {
          "text": "Ask about epiphany -- the painful recognition at each story's center",
          "target": "act5_epiphany"
        },
        {
          "text": "Ask about the reader's work -- what modern fiction demands of us",
          "target": "act5_reader"
        },
        {
          "text": "Ask about the tradition they started -- who came after?",
          "target": "act5_tradition"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "synthesis",
      "vocabulary": [
        {
          "term": "three methods of inner life",
          "definition": "Chekhov: narrate it (free indirect discourse); Joyce: immerse in it (accumulation); Hemingway: remove it entirely and trust the reader"
        }
      ],
      "figures": [],
      "tags": [
        "synthesis",
        "comparison"
      ]
    },
    "act5_epiphany": {
      "title": "The Reckoning",
      "text": "'Epiphany,' the woman says. 'Joyce's word. But they all use it.'\n\n'An epiphany is not a *solution*. It is a sudden, often painful moment when a character -- or a reader -- sees something clearly for the first time. An unwelcome flash of self-knowledge. A recognition that cannot be taken back.'\n\nShe holds up the Chekhov manuscript. 'Gurov's epiphany: he is in love for the first time in his life, and he is too old and too trapped to do anything about it. The story does not solve this. It names it.'\n\nThe Joyce manuscript. 'Gabriel's epiphany: the deepest feeling in his marriage belongs to a dead boy he has never heard of. His entire self-image -- the clever, passionate husband -- collapses. What replaces it is not despair. It is something like *honesty*.'\n\nThe Hemingway manuscript. 'Jig's epiphany -- if she has one -- is hidden from us. *I feel fine.* Is that recognition? Resignation? A closing of the door? We do not know. And Hemingway's argument is that not-knowing is the most honest position of all.'\n\n'All three endings are open,' the woman says. 'None of the characters escapes. Each, by the end, *sees* -- and that seeing is what matters in the logic of modern fiction. Before these writers, a story ended when the problem was solved. After them, a story could end when the problem was *seen*.'",
      "choices": [
        {
          "text": "Ask what the reader's responsibility is in all this",
          "target": "act5_reader"
        },
        {
          "text": "Ask who inherited this tradition",
          "target": "act5_tradition"
        },
        {
          "text": "You understand. It's time to write your own story.",
          "target": "act5_write"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "synthesis",
      "vocabulary": [
        {
          "term": "epiphany (literary)",
          "definition": "A sudden, painful moment of recognition -- not a solution but a reckoning; the character sees clearly for the first time, and cannot unsee"
        },
        {
          "term": "open ending",
          "definition": "An ending that refuses resolution; the problem is named, not solved -- Chekhov, Joyce, and Hemingway all use this technique"
        }
      ],
      "figures": [],
      "tags": [
        "synthesis",
        "epiphany"
      ]
    },
    "act5_reader": {
      "title": "The Reader's Work",
      "text": "'Here is what changed,' the woman says. 'Before Chekhov, the writer did the work. The story told you what it meant. You received it. After Chekhov, the reader does the work. The meaning is not hidden from you -- it is waiting for you to arrive at it yourself.'\n\nShe gestures at the three manuscripts. 'Chekhov does not tell you Gurov is a hypocrite. He lets you hear Gurov's thoughts and trusts you to notice the contradictions. Joyce does not tell you Gabriel is failing to see his wife. He shows you the staircase scene and trusts you to feel the gap between *Distant Music* and whatever Gretta is actually experiencing. Hemingway does not tell you what the couple has decided. He gives you the conversation and trusts you to hear what is beneath it.'\n\n'Confusion,' she says, 'is not failure. It is the starting point. These stories are designed to be *re-read*. The first time through, you feel something -- unease, sadness, a sense that you have missed something important. The second time, you begin to see the architecture. The third time, you see the silences.'\n\n'The meaning lives in what is withheld. That is the modern short story's great gift to fiction: the discovery that what you leave out can be more powerful than what you put in.'",
      "choices": [
        {
          "text": "Ask about the tradition -- who carried this forward?",
          "target": "act5_tradition"
        },
        {
          "text": "You understand. Return to the bookshop. Write.",
          "target": "act5_write"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "synthesis",
      "vocabulary": [
        {
          "term": "the reader's work",
          "definition": "Modern fiction's demand that the reader supply what is withheld -- meaning is not hidden but waiting to be arrived at through active, attentive reading"
        },
        {
          "term": "re-reading",
          "definition": "Essential to the modern short story; first read = feeling, second read = seeing the architecture, third read = hearing the silences"
        }
      ],
      "figures": [],
      "tags": [
        "synthesis",
        "reading"
      ]
    },
    "act5_tradition": {
      "title": "What They Started",
      "text": "'They changed what fiction was for,' the woman says. 'Before them, a story was a machine for delivering an outcome. After them, a story could be a way of paying attention.'\n\nShe pulls more manuscripts from the shelves -- they seem to breed in this room.\n\n'**Flannery O'Connor** took Chekhov's gift for self-deception and relocated it to the rural American South, with a theological edge. Funny and terrifying.'\n\n'**Raymond Carver** pushed Hemingway's iceberg further into working-class American lives. Stripped-down prose. Silences you could fall into.'\n\n'**Alice Munro** wrote stories with the scope of novels -- small-town Ontario, time that jumps and folds like memory. They called her the Chekhov of the English language, and they were not wrong.'\n\n'**Frank O'Connor** -- no relation to Flannery -- was Joyce's Irish successor, with more warmth. He wrote one of the best books about the short story ever written: *The Lonely Voice*.'\n\n'And the influence goes beyond fiction. When a film ends ambiguously. When a TV episode refuses to resolve. When a song says everything by saying almost nothing. The lineage runs back here.'\n\nShe looks at Sam. 'The question is whether the open ending is the more honest choice, or whether it is its own kind of evasion. A closed ending takes courage too: the courage to commit to a meaning.'\n\n'How you answer says something about what you believe stories are for.'",
      "choices": [
        {
          "text": "Open endings are more honest -- life does not resolve",
          "target": "act5_write"
        },
        {
          "text": "Both take courage. The best writers know when to use which.",
          "target": "act5_write"
        },
        {
          "text": "You don't have an answer yet. But you want to find out.",
          "target": "act5_write"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "synthesis",
      "vocabulary": [
        {
          "term": "Flannery O'Connor",
          "definition": "American writer (1925-1964); Chekhov's self-deception relocated to the South with theological intensity; start with 'A Good Man Is Hard to Find'"
        },
        {
          "term": "Raymond Carver",
          "definition": "American writer (1938-1988); Hemingway's iceberg pushed into working-class lives; start with 'Cathedral'"
        },
        {
          "term": "Alice Munro",
          "definition": "Canadian writer (1931-2024); stories with the scope of novels, time-jumping like memory; called 'the Chekhov of the English language'"
        },
        {
          "term": "The Lonely Voice",
          "definition": "Frank O'Connor's critical study of the short story -- one of the best books about the form ever written"
        }
      ],
      "figures": [],
      "tags": [
        "synthesis",
        "tradition"
      ]
    },
    "act5_write": {
      "title": "Your Own Story",
      "text": "The bookshelves exhale. The room is smaller now, more intimate. The woman gathers the three manuscripts into a stack.\n\n'You have been inside three stories,' she says. 'You have felt Chekhov's compassion and his refusal to judge. You have felt Joyce's accumulation building to revelation. You have felt Hemingway's silence pressing down on everything unsaid.'\n\nShe slides a blank manuscript across the table. A pen materializes beside it.\n\n'Now write,' she says. 'Not about what you have learned. Write *from* what you have learned. There is a difference.'\n\nSam picks up the pen. The blank page is terrifying and electric. Three weeks of writer's block suddenly feel like preparation rather than failure -- Sam was not stuck, Sam was *waiting* for something to understand.\n\nThe question is: what kind of story does Sam write?",
      "choices": [
        {
          "text": "A story built on compassion -- see people as they are, without judgment",
          "target": "end_compassion"
        },
        {
          "text": "A story where the prose itself becomes the meaning -- language as music",
          "target": "end_music"
        },
        {
          "text": "A story of perfect restraint -- trust the reader with everything",
          "target": "end_iceberg"
        },
        {
          "text": "A story that ends with recognition -- not escape, but sight",
          "target": "end_recognition"
        },
        {
          "text": "A story that combines all three -- find your own voice in the conversation",
          "target": "end_voice"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "synthesis",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "synthesis",
        "write"
      ]
    },
    "end_compassion": {
      "title": "What Chekhov Knew",
      "text": "Sam writes a story about two people in a laundromat at 2 AM. One is folding sheets with practiced efficiency. The other is watching a single sock spin in a dryer. They do not know each other. They will not become lovers or friends.\n\nBut the story enters each of their minds -- free indirect discourse, Chekhov's gift -- and what Sam discovers is that both of them are carrying something: a fight with a parent, a diagnosis they have not told anyone, a memory of a childhood kitchen that smelled like cinnamon.\n\nThe story does not judge them. It does not fix their problems. It simply *sees* them -- sees the way people carry private worlds through public spaces, and how rarely those worlds collide, and how the moments when they almost collide are the moments worth writing about.\n\nSam wakes on the bookshop carpet. The sun is coming up. The exam is in four hours. Sam writes the essay in Chekhov's spirit -- not explaining what the stories mean, but showing what it feels like to be inside them.\n\nThe professor writes: '*This is the first exam I have received that reads like the thing it is describing.*'\n\nSam begins writing stories. They are quiet, unflashy, full of people who never quite say what they mean. Readers write in to say: '*How did you know that about me?*'\n\nSam smiles. Chekhov knew it first.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "synthesis",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "best"
      ]
    },
    "end_music": {
      "title": "What Prose Can Do",
      "text": "Sam writes a story about a family dinner -- Thanksgiving, a house in the suburbs, the table set for nine but only seven chairs filled. Nobody mentions the empty chairs. The story spends pages on the dinner itself: the way the gravy boat is passed, the specific clink of ice in a glass, a child's fork scraping a plate.\n\nJoyce's method: accumulation. Every detail is precise and seemingly ordinary, and the weight of all those ordinary details builds and builds until, in the final paragraph, the narrator steps outside and looks at the house from the street -- windows lit, shadows moving behind curtains, snow beginning to fall.\n\nThe prose shifts. It lifts. It becomes, for a few sentences, something that is not quite narrative and not quite poetry but a third thing that only fiction can do. The reader does not cry because something sad has happened. The reader cries because something *true* has been rendered in language that is equal to it.\n\nSam wakes in the bookshop with tears on both cheeks and writes an exam essay that the professor calls '*the most Joycean thing a student has ever turned in, and I mean that as a compliment.*'\n\nThe stories Sam writes are long, dense, musical. Not everyone has the patience for them. But those who do emerge changed -- the way you emerge changed from the last paragraph of 'The Dead,' having felt the snow fall faintly through the universe.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "synthesis",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "best"
      ]
    },
    "end_iceberg": {
      "title": "Seven-Eighths Below",
      "text": "Sam writes a story that is mostly dialogue. Two old friends meeting for coffee after years apart. One has something to tell the other. The reader can feel it in the pauses, in the way the conversation keeps circling around a subject without landing on it.\n\nThe thing is never said. The story ends with one of them saying, '*It was good to see you,*' and the other saying, '*You too.*' And between those six words is everything: the secret, the years, the reason one of them cried in the parking lot before coming inside.\n\nHemingway's lesson: what you leave out can be more powerful than what you put in. The story is 1,200 words. It takes three minutes to read. People remember it for years.\n\nSam wakes in the bookshop, writes a razor-sharp exam, and begins a career of writing short fiction that reviewers call '*devastating*' and '*deceptively simple*' -- two adjectives that would have pleased Hemingway enormously, though he would never have said so.\n\nOne-eighth above the surface. Seven-eighths below.\n\nThe readers feel the weight of what they cannot see. That is the trick. That is the whole trick.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "synthesis",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good"
      ]
    },
    "end_recognition": {
      "title": "The Moment of Seeing",
      "text": "Sam writes a story about a woman driving home from her mother's house. The drive is three hours. The radio is broken. She is replaying a conversation they had at lunch -- her mother said something about Sam's father, who left twenty years ago, and the thing she said was not new. She has said it before. But today, on this particular drive, with the window cracked and the highway stretching ahead, the woman hears it differently.\n\nShe understands, suddenly, that her mother was not complaining. She was apologizing. She has been apologizing for twenty years, and her daughter has never heard it.\n\nThe story does not end with a phone call or a reconciliation or a dramatic turn. It ends with the woman pulling into her own driveway and sitting in the car for a long time with the engine off.\n\nEpiphany: not escape, but sight. The character does not solve anything. She *sees* something. And that seeing changes the weight of every scene that came before.\n\nSam wakes in the bookshop, writes the exam like someone who has just understood what stories are *for*, and begins writing fiction that reviewers will describe with a single recurring word: '*honest*'.\n\nIt is the hardest adjective to earn. Sam earned it the way all three masters did -- by being willing to look at what is actually there.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "synthesis",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good"
      ]
    },
    "end_voice": {
      "title": "Between the Lines",
      "text": "Sam writes a story that sounds like no one else.\n\nIt has Chekhov's compassion -- the way the narrative enters a character's mind without judgment, letting self-deception speak for itself. It has Joyce's density -- details that seem decorative until the ending reveals them as load-bearing. And it has Hemingway's restraint -- the crucial thing is implied, never stated, and the reader must lean in to find it.\n\nBut it also has something none of them had: Sam's own experience. Sam's ear for how people actually talk in the twenty-first century. Sam's specific loneliness, which is not Gurov's and not Gabriel's and not Jig's but is recognizable to anyone who has ever carried a private truth through a public space and had no one to tell it to.\n\nThe woman in the room with the breathing bookshelves smiles. It is the first time she has smiled.\n\n'The tradition is not a museum,' she says. 'It is a conversation. Chekhov spoke. Joyce answered. Hemingway answered differently. Now you answer.'\n\nSam wakes in the bookshop. Sunlight through the windows. The exam is soon. But the exam is not the point anymore. The point is the story Sam is already writing in the margins of the bluebook, unable to stop.\n\nIt begins: '*The bookshop was closing in ten minutes.*'\n\nSome stories begin where they end. The best ones begin where another story left off, between the lines, in the space where three traditions meet and a new voice speaks.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "synthesis",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "best"
      ]
    }
  },
  "start_node": "start",
  "edges": [
    [
      "start",
      "act1_modern"
    ],
    [
      "start",
      "act2_yalta"
    ],
    [
      "start",
      "act3_party"
    ],
    [
      "start",
      "act4_station"
    ],
    [
      "act1_modern",
      "act2_yalta"
    ],
    [
      "act1_modern",
      "act3_party"
    ],
    [
      "act1_modern",
      "act4_station"
    ],
    [
      "act1_modern",
      "end_surface"
    ],
    [
      "act2_yalta",
      "act2_fid"
    ],
    [
      "act2_yalta",
      "act2_oreanda"
    ],
    [
      "act2_yalta",
      "act2_two_lives"
    ],
    [
      "act2_fid",
      "act2_oreanda"
    ],
    [
      "act2_fid",
      "act2_sturgeon"
    ],
    [
      "act2_oreanda",
      "act2_sturgeon"
    ],
    [
      "act2_oreanda",
      "act2_two_lives"
    ],
    [
      "act2_sturgeon",
      "act2_two_lives"
    ],
    [
      "act2_sturgeon",
      "act2_ending"
    ],
    [
      "act2_two_lives",
      "act2_ending"
    ],
    [
      "act2_two_lives",
      "act3_party"
    ],
    [
      "act2_two_lives",
      "act4_station"
    ],
    [
      "act2_ending",
      "act3_party"
    ],
    [
      "act2_ending",
      "act4_station"
    ],
    [
      "act2_ending",
      "act5_methods"
    ],
    [
      "act3_party",
      "act3_gabriel"
    ],
    [
      "act3_party",
      "act3_music"
    ],
    [
      "act3_gabriel",
      "act3_music"
    ],
    [
      "act3_gabriel",
      "act3_staircase"
    ],
    [
      "act3_music",
      "act3_staircase"
    ],
    [
      "act3_staircase",
      "act3_furey"
    ],
    [
      "act3_staircase",
      "end_aesthetic"
    ],
    [
      "act3_furey",
      "act3_snow"
    ],
    [
      "act3_snow",
      "act4_station"
    ],
    [
      "act3_snow",
      "act2_yalta"
    ],
    [
      "act3_snow",
      "act5_methods"
    ],
    [
      "act4_station",
      "act4_subtext"
    ],
    [
      "act4_station",
      "act4_power"
    ],
    [
      "act4_subtext",
      "act4_power"
    ],
    [
      "act4_subtext",
      "act4_fine"
    ],
    [
      "act4_power",
      "act4_please"
    ],
    [
      "act4_power",
      "act4_fine"
    ],
    [
      "act4_please",
      "act4_fine"
    ],
    [
      "act4_fine",
      "act2_yalta"
    ],
    [
      "act4_fine",
      "act3_party"
    ],
    [
      "act4_fine",
      "act5_methods"
    ],
    [
      "act4_fine",
      "end_silence"
    ],
    [
      "act5_methods",
      "act5_epiphany"
    ],
    [
      "act5_methods",
      "act5_reader"
    ],
    [
      "act5_methods",
      "act5_tradition"
    ],
    [
      "act5_epiphany",
      "act5_reader"
    ],
    [
      "act5_epiphany",
      "act5_tradition"
    ],
    [
      "act5_epiphany",
      "act5_write"
    ],
    [
      "act5_reader",
      "act5_tradition"
    ],
    [
      "act5_reader",
      "act5_write"
    ],
    [
      "act5_tradition",
      "act5_write"
    ],
    [
      "act5_write",
      "end_compassion"
    ],
    [
      "act5_write",
      "end_music"
    ],
    [
      "act5_write",
      "end_iceberg"
    ],
    [
      "act5_write",
      "end_recognition"
    ],
    [
      "act5_write",
      "end_voice"
    ]
  ]
};
