// Auto-generated by story_graph.py — do not edit by hand
const STORY_DATA = {
  "nodes": {
    "start": {
      "title": "The Worn Anthology",
      "text": "Maia is seventeen, a closet poet who fills notebooks with verses she never shows anyone. Tonight she has a poetry exam. The anthology on her desk is open to Shakespeare's Sonnets -- 154 poems, dense and strange, about someone called the Fair Youth and someone called the Dark Lady.\n\nShe reads Sonnet 18 aloud: '*Shall I compare thee to a summer's day?*'\n\nThe words blur. The lamplight shifts from electric to candle flame. When Maia opens her eyes, she is standing in a narrow lane smelling of hay and horse dung. A wooden sign reads THE GLOBE. Through an open door, she glimpses a round theatre open to the sky.\n\nA man in a leather doublet steps out, quill behind his ear, ink on his fingers. He is balding, bright-eyed, distracted.\n\n'*A visitor,*' he says. '*Good. I am stuck on a verse and could use fresh ears. I am Will. Shakespeare, if you need the surname. Come -- I am wrestling with time and beauty, and they are winning.*'",
      "choices": [
        {
          "text": "Follow Shakespeare inside the Globe",
          "target": "act1_globe"
        },
        {
          "text": "Ask him what he's writing -- what are the Sonnets about?",
          "target": "act1_about"
        },
        {
          "text": "Ask who the Fair Youth is -- you've always wondered",
          "target": "act1_mystery"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "frame",
      "vocabulary": [
        {
          "term": "Sonnet",
          "definition": "A 14-line poem in iambic pentameter with a specific rhyme scheme. From the Italian sonetto, 'little song.' Shakespeare wrote 154 of them."
        },
        {
          "term": "The Globe",
          "definition": "Shakespeare's famous theatre, built in 1599 on London's South Bank. An open-air playhouse where his greatest plays were performed."
        },
        {
          "term": "Fair Youth",
          "definition": "The unnamed young man addressed in Sonnets 1-126. Shakespeare urges him to marry, praises his beauty, and claims poetry will make him immortal."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "entry",
        "frame_story"
      ]
    },
    "act1_globe": {
      "title": "The Wooden O",
      "text": "Inside, the Globe is magnificent -- three tiers of galleries surrounding a thrust stage. Shakespeare leads Maia to a small writing room backstage, cluttered with manuscripts.\n\n'*I am a shareholder here,*' he says. '*Actor, playwright, businessman. But the plays are public work -- written for the crowd, shaped by the crowd. The sonnets are different. They are private. They circulate in manuscript among friends. They will not be published until... well, until Thomas Thorpe gets his hands on them.*'\n\nHe picks up a sheaf of papers. '*One hundred and fifty-four poems. A sequence. Not a story exactly, but a soul's argument with itself about time, beauty, love, and whether words can outlast the grave.*'\n\n'*Where shall we begin? With the form itself -- the fourteen-line cage that sets the words free? Or with the first great theme: beauty's duty to reproduce?*'",
      "choices": [
        {
          "text": "The form -- teach me how a sonnet works",
          "target": "act2_form"
        },
        {
          "text": "The first theme -- why should beauty reproduce?",
          "target": "act3_procreation"
        },
        {
          "text": "Tell me about the people in the poems first",
          "target": "act1_mystery"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "context",
      "vocabulary": [
        {
          "term": "Shareholder",
          "definition": "Shakespeare was part-owner of the Lord Chamberlain's Men (later the King's Men), meaning he profited from performances -- unusual for a playwright."
        },
        {
          "term": "Thomas Thorpe",
          "definition": "Publisher who issued the 1609 Quarto of Shakespeare's Sonnets, with the mysterious dedication to 'Mr. W.H.' -- whose identity remains debated."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "context",
        "globe"
      ]
    },
    "act1_about": {
      "title": "The Soul's Argument",
      "text": "Shakespeare sits on a barrel and thinks.\n\n'*What are they about? Everything. Nothing. A young man I love. A woman who torments me. A rival poet who writes better than I do -- or thinks he does. Time, which destroys all beauty. And poetry, which might -- might -- save it.*'\n\nHe ticks off on his fingers: '*The first seventeen poems beg the Fair Youth to have children -- to reproduce his beauty before time steals it. Then I discover a better answer: my verse will make him immortal. Then comes shadow and betrayal. Then absence and longing. Then a rival who steals his attention. Then estrangement. Then the Dark Lady -- who is nothing like Petrarch's blonde, untouchable ideal.*'\n\nHe looks at Maia. '*Which thread calls to you?*'",
      "choices": [
        {
          "text": "The form -- I want to understand how sonnets work before diving in",
          "target": "act2_form"
        },
        {
          "text": "Procreation -- why does beauty have a duty to reproduce?",
          "target": "act3_procreation"
        },
        {
          "text": "The Dark Lady -- she sounds fascinating",
          "target": "act7_dark_lady"
        },
        {
          "text": "Interesting overview. That's probably enough for the exam.",
          "target": "end_surface"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "context",
      "vocabulary": [
        {
          "term": "Dark Lady",
          "definition": "The unnamed woman of Sonnets 127-152. Unlike the idealized Petrarchan mistress, she is dark-haired, sexually frank, and morally complex."
        },
        {
          "term": "Petrarch",
          "definition": "Italian poet (1304-1374) whose Canzoniere defined the sonnet tradition for 200 years: an idealized, unattainable beloved with fair skin and golden hair."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "context",
        "overview"
      ]
    },
    "act1_mystery": {
      "title": "The Mystery of Mr. W.H.",
      "text": "Shakespeare's expression shifts -- amused, guarded, a little sad.\n\n'*You want to know who he is. Everyone does. When Thorpe publishes these poems in 1609 -- yes, I know things I should not -- the dedication will read: To the only begetter of these ensuing sonnets, Mr. W.H. And for four hundred years, scholars will argue.*'\n\nHe holds up two fingers. '*Henry Wriothesley, Earl of Southampton -- my patron, to whom I dedicated Venus and Adonis. Or William Herbert, Earl of Pembroke. Both young, both beautiful, both plausible. I will never tell.*'\n\nHe leans closer. '*But here is what matters: the poems are not autobiography. They are a performance of autobiography. Every confession is shaped, every cry of anguish is in perfect iambic pentameter. The question is not who he was. The question is what the poems do.*'",
      "choices": [
        {
          "text": "Then teach me what the poems do -- start with the form",
          "target": "act2_form"
        },
        {
          "text": "Start with the first poems -- beauty's duty to reproduce",
          "target": "act3_procreation"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "context",
      "vocabulary": [
        {
          "term": "Mr. W.H.",
          "definition": "The mysterious dedicatee of the 1609 Quarto. Leading candidates: Henry Wriothesley (Earl of Southampton) and William Herbert (Earl of Pembroke). Identity remains unknown."
        },
        {
          "term": "Henry Wriothesley",
          "definition": "Earl of Southampton, Shakespeare's early patron. Venus and Adonis (1593) and The Rape of Lucrece (1594) were dedicated to him."
        },
        {
          "term": "Iambic Pentameter",
          "definition": "The meter of English sonnets: five iambs per line (da-DUM x 5 = 10 syllables). The heartbeat rhythm of English poetry."
        }
      ],
      "figures": [
        "Shakespeare",
        "Henry Wriothesley"
      ],
      "tags": [
        "context",
        "mystery"
      ]
    },
    "act2_form": {
      "title": "The Fourteen-Line Cage",
      "text": "Shakespeare picks up a quill and draws on a scrap of paper.\n\n'*Fourteen lines. Three quatrains and a couplet. Rhyme scheme: ABAB CDCD EFEF GG. Each quatrain turns the argument like a gem showing a new facet. Then the couplet snaps shut like a lock.*'\n\nHe draws the structure:\nQuatrain 1 -- *state the problem*\nQuatrain 2 -- *deepen or complicate it*\nQuatrain 3 -- *turn: 'but,' 'yet,' 'however'*\nCouplet -- *resolve, reverse, or explode*\n\n'*The Italians -- Petrarch and his followers -- split the poem in two: an octave and a sestet, eight lines and six, with the turn at line nine. I keep the turn but add another at line thirteen. Two pivots instead of one. It is more like the way the mind actually argues.*'\n\nHe hands Maia the quill. '*The trick is the volta -- the turn. Find the turn and you find the poem's secret.*'",
      "choices": [
        {
          "text": "Ask about the volta -- how do you find the turn?",
          "target": "act2_volta"
        },
        {
          "text": "Ask about the devices -- metaphor, imagery, rhetoric",
          "target": "act2_devices"
        },
        {
          "text": "Enough theory -- show me the poems in action",
          "target": "act3_procreation"
        },
        {
          "text": "The volta idea is enough. That changes how you read everything.",
          "target": "end_volta"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "form",
      "vocabulary": [
        {
          "term": "Quatrain",
          "definition": "A four-line unit of verse. Shakespeare's sonnets have three quatrains (ABAB CDCD EFEF) before the final couplet."
        },
        {
          "term": "Couplet",
          "definition": "Two consecutive rhyming lines (GG). In Shakespeare's sonnets, the couplet delivers the final punch: resolution, reversal, or paradox."
        },
        {
          "term": "Volta",
          "definition": "The 'turn' -- the pivotal moment where the sonnet's argument shifts direction. In Shakespeare, look for it at line 9 or line 13, often signaled by 'but,' 'yet,' or 'so.'"
        },
        {
          "term": "Octave",
          "definition": "The first eight lines of a Petrarchan sonnet (ABBAABBA). Sets up the problem or situation before the volta."
        },
        {
          "term": "Sestet",
          "definition": "The final six lines of a Petrarchan sonnet. Responds to the octave with resolution, reversal, or complication."
        }
      ],
      "figures": [
        "Shakespeare",
        "Petrarch"
      ],
      "tags": [
        "form",
        "structure"
      ]
    },
    "act2_volta": {
      "title": "Finding the Turn",
      "text": "'*Read any sonnet of mine,*' Shakespeare says. '*Find the word but or yet or so near line nine or line thirteen. That is where the poem pivots. Everything before the turn pushes in one direction. Everything after pulls the other way.*'\n\nHe recites Sonnet 29: '*When, in disgrace with fortune and men's eyes, I all alone beweep my outcast state...*' Eight lines of self-pity. Then line 9: '*Yet in these thoughts myself almost despising, / Haply I think on thee.*' The turn. Despair becomes joy. The whole poem flips.\n\n'*Sometimes the couplet is the real turn. Twelve lines of argument, then two lines that reverse everything. That is the Shakespearean couplet at its most dangerous -- a trap door beneath the reader's feet.*'\n\nMaia begins to see: the sonnet is not just a form. It is a machine for thinking.",
      "choices": [
        {
          "text": "Show me the imagery and rhetoric -- how does the language work?",
          "target": "act2_devices"
        },
        {
          "text": "Let's see the poems in action -- start with procreation",
          "target": "act3_procreation"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "form",
      "vocabulary": [
        {
          "term": "Anaphora",
          "definition": "Repetition of a word or phrase at the beginning of successive lines. Creates rhythmic emphasis and builds intensity."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "form",
        "volta"
      ]
    },
    "act2_devices": {
      "title": "The Poet's Toolkit",
      "text": "Shakespeare spreads his manuscripts across the table and points out patterns.\n\n'*I think in clusters of imagery. Time appears as a scythe, an hourglass, winter, a crooked knife. Love appears as warfare -- the heart besieged, desire as an invading army. Beauty is a flower, a lease, a loan that must be repaid. And always: mirrors. The face reflected, the poem as mirror, the child as mirror of the parent.*'\n\nHe picks up a sonnet. '*I personify everything. Time devours. Death brags. The sun has an eye. I use apostrophe -- speaking directly to absent things: O Time, O Muse, O cruel fair. And antithesis -- setting opposites against each other: fair and foul, black and bright, love and hate.*'\n\n'*The sonnets are an argument in verse. Every rhetorical device is a weapon. The question is: what am I fighting?*'\n\nHe looks at Maia. '*Time. I am always fighting time.*'",
      "choices": [
        {
          "text": "Show me the fight against time -- the procreation sonnets",
          "target": "act3_procreation"
        },
        {
          "text": "Skip to the moment poetry replaces procreation -- Sonnet 18",
          "target": "act4_eighteen"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "form",
      "vocabulary": [
        {
          "term": "Personification",
          "definition": "Giving human qualities to abstract forces. Shakespeare personifies Time (devouring, carving), Death (bragging), and the Sun (whose 'eye' shines)."
        },
        {
          "term": "Apostrophe",
          "definition": "Directly addressing an absent person, abstraction, or thing: 'O Time,' 'O Muse.' Creates urgency and dramatic intensity."
        },
        {
          "term": "Antithesis",
          "definition": "Placing contrasting ideas side by side for emphasis: fair/foul, black/bright, love/hate. Central to Shakespeare's rhetorical strategy."
        },
        {
          "term": "Blazon",
          "definition": "A poetic catalogue of the beloved's features (eyes, lips, cheeks, hair). Shakespeare both uses and subverts this Petrarchan convention."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "form",
        "devices"
      ]
    },
    "act3_procreation": {
      "title": "Beauty's Debt",
      "text": "Shakespeare reads Sonnet 1 aloud:\n\n'*From fairest creatures we desire increase, / That thereby beauty's rose might never die...*'\n\nHe looks up. '*The argument is simple: you are beautiful. Beauty is not yours -- it is a loan from Nature. If you die without children, you default on the debt. The rose dies with you. The world is poorer.*'\n\nHe reads the key accusation: '*Making a famine where abundance lies, / Thy self thy foe, to thy sweet self too cruel.* The Youth is a glutton feeding only on himself. A candle consuming its own flame.\n\n'*Seventeen sonnets I wrote begging him to marry and have children. Seventeen different ways of saying: your beauty is not your private property. You hold it in trust for the future.*'",
      "choices": [
        {
          "text": "Read Sonnet 2 -- time as invader",
          "target": "act3_sonnet2"
        },
        {
          "text": "Read Sonnet 3 -- the mirror and the mother",
          "target": "act3_sonnet3"
        },
        {
          "text": "Skip ahead to where poetry replaces children -- Sonnet 18",
          "target": "act4_eighteen"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "procreation",
      "vocabulary": [
        {
          "term": "Procreation Sonnets",
          "definition": "Sonnets 1-17, urging the Fair Youth to marry and have children to preserve his beauty. The first 'solution' to mortality, before poetry takes over."
        },
        {
          "term": "Beauty's Rose",
          "definition": "The central metaphor of Sonnet 1: beauty as a rose that must reproduce or die. Nature lends beauty; the recipient must pass it on."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "procreation",
        "sonnet1"
      ]
    },
    "act3_sonnet2": {
      "title": "Forty Winters",
      "text": "'*When forty winters shall besiege thy brow / And dig deep trenches in thy beauty's field...*'\n\nShakespeare's voice drops. '*This is Sonnet 2. Time is an army. It besieges. It digs trenches -- wrinkles -- in the field of the Youth's face. At forty, his proud livery -- his youth -- is a tattered weed.*'\n\nHe traces the financial metaphor: '*Where all thy beauty lies, where all thy treasure? He has spent his beauty and has nothing to show for it. No child. No succession. But if he has a child -- new made -- then in old age he can see his beauty warm and new again.*'\n\nMaia notices: the imagery shifts from war to accounting. Time besieges, but the real crime is bad bookkeeping -- spending beauty without investing it.\n\n'*Every metaphor is an argument,*' Shakespeare says. '*The trenches make you feel the violence. The accounting makes you feel the waste.*'",
      "choices": [
        {
          "text": "Read Sonnet 3 -- the mirror and the mother",
          "target": "act3_sonnet3"
        },
        {
          "text": "Move to the turning point -- Sonnet 18",
          "target": "act4_eighteen"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "procreation",
      "vocabulary": [
        {
          "term": "Livery",
          "definition": "In Sonnet 2, the Youth's beauty is compared to a 'proud livery' (fine clothing) that time reduces to a 'tatter'd weed.' Beauty as garment, worn and discarded."
        },
        {
          "term": "Succession",
          "definition": "The passing of beauty (or wealth, or power) from one generation to the next. A child is the Youth's 'succession' -- his investment in the future."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "procreation",
        "sonnet2"
      ]
    },
    "act3_sonnet3": {
      "title": "The Mirror",
      "text": "'*Look in thy glass and tell the face thou viewest / Now is the time that face should form another...*'\n\nShakespeare holds up an imaginary mirror. '*Sonnet 3. The Youth looks in the glass and sees his face. But the mirror is not just reflecting -- it is commanding: now is the time to reproduce that face in a child.*'\n\n'*Then the most beautiful image in the sequence so far: his mother sees her lovely April reflected in him. She looks at her son's face and sees her own golden time restored. That is what a child does -- it is a living mirror, carrying the parent's beauty forward through time.*'\n\nHe pauses. '*But the Youth refuses. He is uneared -- unplowed. His womb of potential goes uncultivated. The agricultural metaphor is deliberate: tillage, husbandry, harvest. Refusing to reproduce is letting a fertile field go fallow.*'",
      "choices": [
        {
          "text": "Move to the great pivot -- when poetry replaces children",
          "target": "act4_eighteen"
        },
        {
          "text": "This mirror metaphor is fascinating. How do mirrors work across the sonnets?",
          "target": "act3_mirrors"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "procreation",
      "vocabulary": [
        {
          "term": "Glass",
          "definition": "Mirror. In Sonnet 3, the mirror is both literal (the Youth's reflection) and metaphorical (the child as living mirror of the parent's beauty)."
        },
        {
          "term": "Uneared",
          "definition": "'Unplowed' -- from ear, to plow. The Youth's potential for reproduction is compared to a fertile field left uncultivated."
        },
        {
          "term": "Husbandry",
          "definition": "Double meaning: farming/cultivation AND marriage/being a husband. Shakespeare puns deliberately -- agricultural duty mirrors marital duty."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "procreation",
        "sonnet3",
        "mirrors"
      ]
    },
    "act3_mirrors": {
      "title": "Reflections",
      "text": "'*Mirrors run through everything I write,*' Shakespeare says. '*The child mirrors the parent. The poem mirrors the beloved. The beloved mirrors the poet. And the reader -- you -- mirrors them all.*'\n\n'*In the procreation sonnets, the mirror commands: reproduce yourself. But after Sonnet 17, I discover that the poem itself is a mirror -- one that does not age, does not crack, does not lie. The beloved's reflection in verse is more faithful than any glass.*'\n\nHe smiles. '*And here is the trick: when you read these poems aloud, you become the mirror too. Your voice carries his beauty forward. Every reader who speaks these lines is part of the reproduction. The poem is the child the Youth never had.*'\n\nMaia feels a shiver. She has been carrying these poems in her mouth for her exam. She has been the mirror all along.",
      "choices": [
        {
          "text": "Now show me the turning point -- Sonnet 18",
          "target": "act4_eighteen"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "procreation",
      "vocabulary": [],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "procreation",
        "mirrors"
      ]
    },
    "act4_eighteen": {
      "title": "Shall I Compare Thee",
      "text": "Shakespeare stands. His voice changes -- becomes formal, incantatory.\n\n'*Shall I compare thee to a summer's day? / Thou art more lovely and more temperate.*'\n\nHe walks as he recites. '*Summer is rough winds. Too hot. Too short. Its lease expires. Every lovely thing declines by chance or nature's changing course. But --*'\n\nHe turns. The volta. Line 9.\n\n'*But thy eternal summer shall not fade.* Here it is. The great pivot. For seventeen sonnets I begged the Youth to have children. Now I find a better answer: *So long as men can breathe, or eyes can see, / So long lives this, and this gives life to thee.*'\n\n'*Not children. Verse. My poem will outlast summer, outlast the Youth's body, outlast even time. This is the boldest claim a poet can make: my words are stronger than death.*'",
      "choices": [
        {
          "text": "Read Sonnet 19 -- the direct challenge to Time",
          "target": "act4_nineteen"
        },
        {
          "text": "That's an audacious claim. Does he really believe it?",
          "target": "act4_audacity"
        },
        {
          "text": "Move on to the darker sonnets -- shadow and betrayal",
          "target": "act5_shadow"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "immortality",
      "vocabulary": [
        {
          "term": "Sonnet 18",
          "definition": "'Shall I compare thee to a summer's day?' -- the most famous sonnet in English. The pivot from procreation to poetry as the means of achieving immortality."
        },
        {
          "term": "Eternal Lines",
          "definition": "Sonnet 18's claim: 'in eternal lines to time thou grow'st.' The beloved is grafted into time itself through the poem's words."
        },
        {
          "term": "Summer's Lease",
          "definition": "Sonnet 18's metaphor: summer 'hath all too short a date' -- beauty has a limited rental agreement with time."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "immortality",
        "sonnet18"
      ]
    },
    "act4_nineteen": {
      "title": "Devouring Time",
      "text": "'*Devouring Time, blunt thou the lion's paws, / And make the earth devour her own sweet brood...*'\n\nShakespeare's voice is fierce now. '*Sonnet 19. I speak directly to Time. I grant permission for all destruction: blunt the lion, devour the earth's children, pull the tiger's teeth, burn the phoenix. Do your worst. But --*'\n\nHe raises a finger. '*One crime I forbid thee: do not carve my love's fair brow. Do not draw lines in his face with thine antique pen.*'\n\nHe laughs. '*Of course Time will disobey. That is the point. The prohibition is rhetorical. The real insurance is the couplet: Yet, do thy worst, old Time: despite thy wrong, / My love shall in my verse ever live young.*'\n\n'*Even if Time carves its lines in his face, my lines -- my verse -- keep him forever young. Lines against lines. The pen against the scythe.*'",
      "choices": [
        {
          "text": "The pen against the scythe -- that's a powerful image. But does it darken?",
          "target": "act5_shadow"
        },
        {
          "text": "Stay with the immortality theme -- is poetry really stronger than death?",
          "target": "act4_audacity"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "immortality",
      "vocabulary": [
        {
          "term": "Sonnet 19",
          "definition": "'Devouring Time, blunt thou the lion's paws' -- a direct challenge to Time personified. Shakespeare grants Time every destruction except aging the beloved's face."
        },
        {
          "term": "Antique Pen",
          "definition": "Time's weapon in Sonnet 19: it 'carves' wrinkles into the beloved's brow. Shakespeare's pen of verse fights back against Time's pen of decay."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "immortality",
        "sonnet19"
      ]
    },
    "act4_audacity": {
      "title": "The Poet's Gamble",
      "text": "Maia asks the question that has nagged her: does Shakespeare really believe poetry can defeat time?\n\nHe is quiet for a long moment.\n\n'*Sometimes, when I am writing, I believe it absolutely. The words come and they feel eternal -- as though they were always there, waiting to be found. The poem feels stronger than stone, stronger than bronze, stronger than any monument.*'\n\n'*But other times I know the truth: paper rots, ink fades, languages die. Four hundred years from now, will anyone read these? The claim of immortality is a gamble. A magnificent, necessary gamble. Because the alternative -- silence, oblivion, no attempt at all -- is worse.*'\n\nHe picks up his quill. '*And here is the paradox: if you are reading this four hundred years hence, the gamble paid off. The poem kept its promise. My words gave life. That is either a miracle or a very good bet.*'",
      "choices": [
        {
          "text": "Follow the sequence into darkness -- what goes wrong?",
          "target": "act5_shadow"
        },
        {
          "text": "This is enough. The poems are alive because you're reading them now.",
          "target": "end_immortal"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "immortality",
      "vocabulary": [],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "immortality",
        "meta"
      ]
    },
    "act5_shadow": {
      "title": "When the Sun Goes In",
      "text": "Shakespeare's mood darkens. He reads Sonnet 33:\n\n'*Full many a glorious morning have I seen / Flatter the mountain-tops with sovereign eye, / Kissing with golden face the meadows green, / Gilding pale streams with heavenly alchemy; / Anon permit the basest clouds to ride / With ugly rack on his celestial face...*'\n\nHe pauses. '*The sun -- the Youth -- shone on me briefly. Then clouds covered him. He turned away. Betrayed me with someone else, perhaps. Or simply grew cold. The poem does not specify the sin. It only captures the grief of a sun that stops shining.*'\n\nThe couplet: '*Yet him for this my love no whit disdaineth; / Suns of the world may stain when heaven's sun staineth.*'\n\n'*I forgive him. If even the actual sun can be stained by clouds, why not my sun? The forgiveness is magnificent and devastating. I cannot stop loving.*'",
      "choices": [
        {
          "text": "Ask about absence -- what happens when the Youth is gone?",
          "target": "act5_absence"
        },
        {
          "text": "Ask about the Rival Poet -- who threatens Shakespeare's place?",
          "target": "act6_rival"
        },
        {
          "text": "Skip to the Dark Lady -- the other love",
          "target": "act7_dark_lady"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "shadow",
      "vocabulary": [
        {
          "term": "Sonnet 33",
          "definition": "The sun-and-cloud sonnet. The Youth's withdrawal is compared to a glorious sun hidden by 'basest clouds.' Forgiveness offered through cosmic metaphor."
        },
        {
          "term": "Heavenly Alchemy",
          "definition": "In Sonnet 33, sunlight transforms pale streams into gold -- 'heavenly alchemy.' The Youth's presence similarly transforms everything it touches."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "shadow",
        "sonnet33"
      ]
    },
    "act5_absence": {
      "title": "Darkly Bright",
      "text": "Shakespeare recites Sonnet 43:\n\n'*When most I wink, then do mine eyes best see, / For all the day they view things unrespected; / But when I sleep, in dreams they look on thee, / And darkly bright, are bright in dark directed.*'\n\n'*This is the paradox of absence,*' he says. '*I see better with my eyes shut. Waking, everything is dull -- unrespected. But in dreams, the Youth appears: darkly bright. Luminous in the darkness.*'\n\nHe traces the inversion: '*Days are nights without him. Nights become bright days when dreams restore him. The whole natural order flips. Love rewrites reality.*'\n\nMaia thinks of her own notebooks -- the poems she writes at 2 AM when the world is dark but her mind is blazing. She understands this paradox. Creation happens in the dark.",
      "choices": [
        {
          "text": "Ask about the Rival Poet -- the competitive threat",
          "target": "act6_rival"
        },
        {
          "text": "Ask about estrangement -- how does it end with the Youth?",
          "target": "act6_estrangement"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "absence",
      "vocabulary": [
        {
          "term": "Sonnet 43",
          "definition": "'When most I wink, then do mine eyes best see' -- the paradox of love-in-absence. Closed eyes see the beloved more clearly than waking sight."
        },
        {
          "term": "Darkly Bright",
          "definition": "Shakespeare's oxymoron in Sonnet 43: the beloved appears luminous in the darkness of dreams, reversing natural expectations of light and dark."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "absence",
        "sonnet43"
      ]
    },
    "act6_rival": {
      "title": "The Other Poet",
      "text": "Shakespeare's jaw tightens.\n\n'*There is another poet. Sonnets 78 through 86. He writes for the same patron -- my Youth. He may be Christopher Marlowe, or George Chapman, or someone lost to history. All I know is: his verse is polished, his learning is vast, and the Youth's attention is drifting.*'\n\nHe reads Sonnet 78: '*So oft have I invoked thee for my Muse... How have I not alien pens to lend, / Under thee their poesy disperse.*'\n\n'*Everyone borrows from the Youth's beauty now. But here is my defense: in their work, the Youth merely mends the style. In mine, the Youth is the style. He is not my inspiration -- he is my entire art. Without him, I have nothing. That makes my verse more honest, even if it is less learned.*'\n\nHe pauses. '*Rude ignorance elevated to the level of learning by love. That is my argument. I pray it is enough.*'",
      "choices": [
        {
          "text": "How does it end with the Youth? Ask about estrangement.",
          "target": "act6_estrangement"
        },
        {
          "text": "Move to the Dark Lady -- the other story",
          "target": "act7_dark_lady"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "rivalry",
      "vocabulary": [
        {
          "term": "Rival Poet",
          "definition": "The unnamed competitor of Sonnets 78-86 who also writes for the Fair Youth. Leading candidate: Christopher Marlowe, Shakespeare's contemporary and rival."
        },
        {
          "term": "Sonnet 78",
          "definition": "Opens the Rival Poet sequence. Shakespeare argues his verse is more authentic: in others' work, the Youth 'mends the style'; in Shakespeare's, the Youth IS the art."
        },
        {
          "term": "Alien Pen",
          "definition": "Other poets who write for the Youth's favor. Shakespeare's anxiety that their learning and polish will eclipse his more rough-hewn, love-driven verse."
        }
      ],
      "figures": [
        "Shakespeare",
        "Christopher Marlowe"
      ],
      "tags": [
        "rivalry",
        "sonnet78"
      ]
    },
    "act6_estrangement": {
      "title": "Farewell Without Blame",
      "text": "Shakespeare reads Sonnet 87 in a voice stripped of all performance:\n\n'*Farewell! thou art too dear for my possessing, / And like enough thou know'st thy estimate...*'\n\n'*This is the hardest sonnet I have written,*' he says quietly. '*Not because it is angry but because it is not. I do not blame the Youth. I do not accuse. I simply concede: you are too valuable for me. My bonds in thee are all determinate -- expired, like a legal contract.*'\n\nHe reads the devastating couplet: '*Thus have I had thee, as a dream doth flatter, / In sleep a king, but waking no such matter.*'\n\n'*Everything I had was a dream. I was a king in sleep. Now I wake and I am nothing.*'\n\nMaia's throat tightens. Behind all the legal metaphors -- charters, patents, bonds -- there is a person saying: I loved you, and I was not enough.",
      "choices": [
        {
          "text": "The Dark Lady -- does love go somewhere else?",
          "target": "act7_dark_lady"
        },
        {
          "text": "This is devastating. How does it resolve?",
          "target": "act8_constancy"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "rivalry",
      "vocabulary": [
        {
          "term": "Sonnet 87",
          "definition": "'Farewell, thou art too dear for my possessing' -- the formal farewell to the Youth, framed in legal language (bonds, charters, patents) that barely conceals grief."
        },
        {
          "term": "Determinate",
          "definition": "In Sonnet 87: expired, concluded. 'My bonds in thee are all determinate' -- the contractual metaphor for love's end."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "estrangement",
        "sonnet87"
      ]
    },
    "act7_dark_lady": {
      "title": "Black Is Fair",
      "text": "The room changes. Shakespeare's mood shifts from elegy to something fiercer, more combustible.\n\n'*Now we come to her,*' he says. '*Sonnet 127. The Dark Lady. Everything Petrarch taught us about love -- golden hair, fair skin, angelic purity -- I am about to destroy.*'\n\nHe reads: '*In the old age black was not counted fair, / Or if it were, it bore not beauty's name; / But now is black beauty's successive heir.*'\n\n'*She is dark. Dark-haired, dark-eyed, dark-souled, perhaps. In a world where every poet praises blondes, where cosmetics let anyone fake fairness, her blackness is authentic. Everyone else is counterfeit. She is real.*'\n\n'*But do not mistake this for a love poem. It is a demolition of false beauty standards. And the woman it describes will torment me as much as she fascinates me. She is not an angel. She is a person. That is what makes her terrifying.*'",
      "choices": [
        {
          "text": "Read Sonnet 130 -- 'My mistress' eyes are nothing like the sun'",
          "target": "act7_130"
        },
        {
          "text": "Ask about the love triangle -- Youth, Lady, and Shakespeare",
          "target": "act7_triangle"
        },
        {
          "text": "This is enough darkness. How does it all end?",
          "target": "act8_constancy"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "dark_lady",
      "vocabulary": [
        {
          "term": "Sonnet 127",
          "definition": "Opens the Dark Lady sequence (127-152). Declares 'black is beauty's successive heir' -- dark beauty as more authentic than cosmetically enhanced fairness."
        },
        {
          "term": "Dark Lady",
          "definition": "The unnamed woman of Sonnets 127-152. Sexually frank, morally complex, dark-featured -- the anti-Petrarchan beloved. Her identity, like the Youth's, is unknown."
        },
        {
          "term": "Anti-Petrarchan",
          "definition": "Deliberately subverting Petrarchan conventions. Instead of idealized, unattainable beauty, Shakespeare presents a real, flawed, sexually active woman."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "dark_lady",
        "sonnet127"
      ]
    },
    "act7_130": {
      "title": "My Mistress' Eyes",
      "text": "Shakespeare recites with a wicked grin:\n\n'*My mistress' eyes are nothing like the sun; / Coral is far more red than her lips' red; / If snow be white, why then her breasts are dun; / If hairs be wires, black wires grow on her head.*'\n\nHe watches Maia's face. '*Every line is a Petrarchan convention demolished. Eyes like the sun? No. Lips like coral? No. Skin like snow? No. Cheeks like roses? I have seen roses, and her cheeks are not roses. She does not walk like a goddess. She walks on the ground.*'\n\nThe couplet: '*And yet, by heaven, I think my love as rare / As any she belied with false compare.*'\n\n'*That is the point. The entire blazon tradition -- cataloguing the beloved's perfections -- is a lie. My mistress is real. And my love for a real woman is worth more than a hundred polished lies about imaginary goddesses.*'",
      "choices": [
        {
          "text": "Ask about the love triangle -- the Dark Lady and the Youth",
          "target": "act7_triangle"
        },
        {
          "text": "This honesty is revolutionary. How does the sequence end?",
          "target": "act8_constancy"
        },
        {
          "text": "The Dark Lady is who you came here for. Hold her paradox.",
          "target": "end_dark"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "dark_lady",
      "vocabulary": [
        {
          "term": "Sonnet 130",
          "definition": "'My mistress' eyes are nothing like the sun' -- the most famous anti-Petrarchan sonnet. Demolishes conventional praise to argue that honest love surpasses false comparison."
        },
        {
          "term": "False Compare",
          "definition": "The Petrarchan tradition of comparing the beloved to impossible ideals (sun, coral, snow, roses). Shakespeare argues this dishonors rather than honors the real person."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "dark_lady",
        "sonnet130"
      ]
    },
    "act7_triangle": {
      "title": "The Tangled Web",
      "text": "Shakespeare's voice drops to barely a whisper.\n\n'*She is sleeping with him. The Dark Lady and the Fair Youth. And I -- I am caught between them, loving both, betrayed by both, unable to stop loving either.*'\n\nHe reads Sonnet 144: '*Two loves I have of comfort and despair, / Which like two spirits do suggest me still; / The better angel is a man right fair, / The worser spirit a woman colour'd ill.*'\n\n'*There it is. Angel and devil. Fair and dark. The Youth is my comfort, the Lady my despair. But the devil is corrupting the angel. She has drawn him away from me. And the worst of it? I cannot be certain. I only suspect, and the suspicion is hell.*'\n\nMaia sees: the sonnets are not just poems about love. They are poems about the impossibility of knowing another person. Every sonnet is a guess -- brilliant, anguished, and uncertain.",
      "choices": [
        {
          "text": "How does this resolve? Does anything survive the triangle?",
          "target": "act8_constancy"
        },
        {
          "text": "Stay with the darkness. Read about sin and shame.",
          "target": "act7_sin"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "dark_lady",
      "vocabulary": [
        {
          "term": "Sonnet 144",
          "definition": "'Two loves I have of comfort and despair' -- the love triangle sonnet. The Fair Youth as 'better angel,' the Dark Lady as 'worser spirit,' with Shakespeare caught between."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "dark_lady",
        "triangle"
      ]
    },
    "act7_sin": {
      "title": "Love Is My Sin",
      "text": "Shakespeare reads Sonnet 142:\n\n'*Love is my sin, and thy dear virtue hate, / Hate of my sin, grounded on sinful loving...*'\n\n'*Neither of us has moral high ground,*' he says. '*She sins. I sin. She hates my sin while committing the same sin herself. Her virtue -- her hatred of my transgression -- is founded on her own transgression. It is a perfect circle of hypocrisy.*'\n\nHe catalogs her offenses without flinching: '*Profaned lips. Broken beds' revenues. Sealed false bonds of love. She has done everything I have done.*'\n\n'*And yet I beg for pity. Because if she withholds mercy from me, she sets a precedent that will be used against her own desires. We are both sinners. We both need grace. That is the Dark Lady sonnets in a sentence: love between sinners who cannot stop sinning.*'",
      "choices": [
        {
          "text": "How does the whole sequence end? What survives?",
          "target": "act8_constancy"
        },
        {
          "text": "This is the rawest thing you've ever read. Rest here.",
          "target": "end_honest"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "dark_lady",
      "vocabulary": [
        {
          "term": "Sonnet 142",
          "definition": "'Love is my sin' -- the mutual sin sonnet. Neither poet nor Dark Lady has moral authority; both are sinners grounded in the same transgression."
        },
        {
          "term": "Tu Quoque",
          "definition": "'You too' -- a rhetorical strategy where the accused deflects blame by showing the accuser's equal guilt. Central to the Dark Lady sonnets."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "dark_lady",
        "sin"
      ]
    },
    "act8_constancy": {
      "title": "Despite Everything",
      "text": "Shakespeare gathers the scattered manuscripts into a pile. His hands are steady.\n\n'*After the betrayal, the rivalry, the Dark Lady, the triangle, the sin -- what remains? Constancy. Sonnet 116:*'\n\n'*Let me not to the marriage of true minds / Admit impediments. Love is not love / Which alters when it alteration finds, / Or bends with the remover to remove...*'\n\n'*Love bears it out even to the edge of doom. That is my final answer. Not that love is easy, or pure, or deserved. But that it does not move. It is the star to every wandering bark. Fixed. Constant. Even when the beloved betrays, even when the poet sins, even when time devours everything -- love endures.*'\n\nHe looks at Maia. '*One hundred and fifty-four poems. And in the end, only two things survive: love and the words that carry it.*'",
      "choices": [
        {
          "text": "Those words have survived 400 years. That's the answer.",
          "target": "end_immortal"
        },
        {
          "text": "You're a poet too, Maia. What will you do with what you've learned?",
          "target": "end_poet"
        },
        {
          "text": "Read one more -- the poet's apology",
          "target": "act8_apology"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "closure",
      "vocabulary": [
        {
          "term": "Sonnet 116",
          "definition": "'Let me not to the marriage of true minds admit impediments' -- the great constancy sonnet. Love as fixed star, unshaken by storms, bearing out 'even to the edge of doom.'"
        },
        {
          "term": "Marriage of True Minds",
          "definition": "Sonnet 116's metaphor: love as a union not of bodies but of minds. It does not alter, bend, or remove when circumstances change."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "closure",
        "constancy"
      ]
    },
    "act8_apology": {
      "title": "The Confession",
      "text": "Shakespeare reads Sonnet 117 -- a confession:\n\n'*Accuse me thus: that I have scanted all / Wherein I should your great deserts repay...*'\n\n'*I invite the Youth to accuse me,*' he says. '*I have failed to visit. I have spent time with strangers. I have hoisted sail to all the winds, sailing away from the one who matters most.*'\n\n'*But by naming every fault myself, I take control. The apology becomes an argument. And the couplet offers a defense: I strayed to test your constancy. To prove that your love could survive my worst.*'\n\nHe shakes his head. '*Is that honest? Or is it the poet's old trick -- turning shame into eloquence, making the confession more beautiful than the sin?*'\n\nHe does not answer his own question. The sonnets never do. They ask; they do not resolve.",
      "choices": [
        {
          "text": "The poems ask and we answer by reading them. That's the miracle.",
          "target": "end_immortal"
        },
        {
          "text": "You're a poet, Maia. Write your own answer.",
          "target": "end_poet"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "closure",
      "vocabulary": [
        {
          "term": "Sonnet 117",
          "definition": "The confessional apology sonnet. Shakespeare preemptively names his own faults, then offers a paradoxical defense: straying was a test of the Youth's love."
        }
      ],
      "figures": [
        "Shakespeare"
      ],
      "tags": [
        "closure",
        "apology"
      ]
    },
    "end_immortal": {
      "title": "So Long Lives This",
      "text": "Maia wakes at her desk. The anthology is still open to Sonnet 18.\n\n*So long as men can breathe, or eyes can see, / So long lives this, and this gives life to thee.*\n\nShe has been breathing. She has been seeing. She has been the eyes and lungs that keep the poem alive. For four hundred years, readers have done this -- given their breath to Shakespeare's words, carried the Fair Youth's beauty forward through time.\n\nThe gamble paid off. The poem kept its promise. And Maia, reading aloud in her quiet room, is the latest link in an unbroken chain of voices stretching back to the Globe.\n\nShe reads the sonnet one more time. Not for the exam. For the miracle.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "immortality"
      ]
    },
    "end_poet": {
      "title": "The Quill Passes",
      "text": "Maia wakes at her desk. But instead of reaching for the anthology, she reaches for her notebook.\n\nShe has been hiding her poems. Afraid they are not good enough. Afraid of the exposure -- the rawness of putting your heart in fourteen lines and handing them to someone.\n\nBut Shakespeare did it. He wrote about love that betrayed him, beauty that faded, rivals who outshone him, desire that shamed him. He wrote it all in perfect iambic pentameter, and then he let it go.\n\nMaia opens her notebook. She picks up her pen. She writes a first line:\n\n*When I was afraid to speak, the words spoke me.*\n\nNot Shakespeare. Not yet. But hers. And that is where every poem begins: with the courage to write the first line.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "vocation"
      ]
    },
    "end_honest": {
      "title": "Rare as Any She",
      "text": "Maia wakes with Sonnet 130 in her head:\n\n*And yet, by heaven, I think my love as rare / As any she belied with false compare.*\n\nHonesty. That is what she takes from the sonnets. Not the golden rhetoric of Sonnet 18, not the anguished triangle of 144, but the simple, stubborn honesty of 130: my love is real because I do not lie about it.\n\nShe closes the anthology. She will ace the exam. But more than that, she will carry this lesson: the truest praise is the praise that tells the truth. No false compare. No counterfeit beauty. Just what is, seen clearly, and loved for what it is.\n\nThat is rare enough.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "honesty"
      ]
    },
    "end_volta": {
      "title": "The Turn",
      "text": "Maia wakes at the word *but*.\n\nShe has learned to find the volta -- the turn, the pivot, the moment where everything shifts. Line 9. Line 13. The single word that flips the argument on its head.\n\nShe realizes: her own life has voltas. Moments where despair turned to hope, where loss became understanding, where a closed door revealed another opening. Every sonnet taught her to look for the turn.\n\nShe picks up the anthology and reads Sonnet 29 one more time:\n*Yet in these thoughts myself almost despising, / Haply I think on thee...*\n\n*Yet.* The smallest, most powerful word in the English language. The word that saves everything.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "volta"
      ]
    },
    "end_surface": {
      "title": "Summer's Lease",
      "text": "Maia wakes at her desk, yawns, and checks the time. The exam is in six hours. She has retained enough: three quatrains and a couplet, ABAB CDCD EFEF GG, the Fair Youth and the Dark Lady, Sonnet 18.\n\nShe closes the anthology. Shakespeare stays between the covers.\n\nSomewhere, in a line she didn't quite reach, the poet writes: *Shall I compare thee to a summer's day?* And summer's lease, as always, hath all too short a date.\n\nThe poems wait. They have waited four hundred years. They can wait a little longer.",
      "choices": [],
      "is_ending": true,
      "ending_type": "neutral",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "surface"
      ]
    },
    "end_dark": {
      "title": "Two Loves",
      "text": "Maia wakes in the dark. The room is quiet. The anthology is closed.\n\nShe lies still, thinking about the Dark Lady -- the anti-ideal, the sin acknowledged, the beauty that doesn't need permission. She thinks about Sonnet 144: two loves, comfort and despair, angel and devil, and the impossible space between them.\n\nShe is seventeen. She has her own two loves, her own contradictions, her own midnight negotiations between what she wants and who she thinks she should be.\n\nShakespeare did not resolve the paradox. He held it. Fourteen lines at a time, he held the contradiction and let it speak.\n\nMaia can do that too. Hold the paradox. Let it speak.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "darkness"
      ]
    }
  },
  "start_node": "start",
  "edges": [
    [
      "start",
      "act1_globe"
    ],
    [
      "start",
      "act1_about"
    ],
    [
      "start",
      "act1_mystery"
    ],
    [
      "act1_globe",
      "act2_form"
    ],
    [
      "act1_globe",
      "act3_procreation"
    ],
    [
      "act1_globe",
      "act1_mystery"
    ],
    [
      "act1_about",
      "act2_form"
    ],
    [
      "act1_about",
      "act3_procreation"
    ],
    [
      "act1_about",
      "act7_dark_lady"
    ],
    [
      "act1_about",
      "end_surface"
    ],
    [
      "act1_mystery",
      "act2_form"
    ],
    [
      "act1_mystery",
      "act3_procreation"
    ],
    [
      "act2_form",
      "act2_volta"
    ],
    [
      "act2_form",
      "act2_devices"
    ],
    [
      "act2_form",
      "act3_procreation"
    ],
    [
      "act2_form",
      "end_volta"
    ],
    [
      "act2_volta",
      "act2_devices"
    ],
    [
      "act2_volta",
      "act3_procreation"
    ],
    [
      "act2_devices",
      "act3_procreation"
    ],
    [
      "act2_devices",
      "act4_eighteen"
    ],
    [
      "act3_procreation",
      "act3_sonnet2"
    ],
    [
      "act3_procreation",
      "act3_sonnet3"
    ],
    [
      "act3_procreation",
      "act4_eighteen"
    ],
    [
      "act3_sonnet2",
      "act3_sonnet3"
    ],
    [
      "act3_sonnet2",
      "act4_eighteen"
    ],
    [
      "act3_sonnet3",
      "act4_eighteen"
    ],
    [
      "act3_sonnet3",
      "act3_mirrors"
    ],
    [
      "act3_mirrors",
      "act4_eighteen"
    ],
    [
      "act4_eighteen",
      "act4_nineteen"
    ],
    [
      "act4_eighteen",
      "act4_audacity"
    ],
    [
      "act4_eighteen",
      "act5_shadow"
    ],
    [
      "act4_nineteen",
      "act5_shadow"
    ],
    [
      "act4_nineteen",
      "act4_audacity"
    ],
    [
      "act4_audacity",
      "act5_shadow"
    ],
    [
      "act4_audacity",
      "end_immortal"
    ],
    [
      "act5_shadow",
      "act5_absence"
    ],
    [
      "act5_shadow",
      "act6_rival"
    ],
    [
      "act5_shadow",
      "act7_dark_lady"
    ],
    [
      "act5_absence",
      "act6_rival"
    ],
    [
      "act5_absence",
      "act6_estrangement"
    ],
    [
      "act6_rival",
      "act6_estrangement"
    ],
    [
      "act6_rival",
      "act7_dark_lady"
    ],
    [
      "act6_estrangement",
      "act7_dark_lady"
    ],
    [
      "act6_estrangement",
      "act8_constancy"
    ],
    [
      "act7_dark_lady",
      "act7_130"
    ],
    [
      "act7_dark_lady",
      "act7_triangle"
    ],
    [
      "act7_dark_lady",
      "act8_constancy"
    ],
    [
      "act7_130",
      "act7_triangle"
    ],
    [
      "act7_130",
      "act8_constancy"
    ],
    [
      "act7_130",
      "end_dark"
    ],
    [
      "act7_triangle",
      "act8_constancy"
    ],
    [
      "act7_triangle",
      "act7_sin"
    ],
    [
      "act7_sin",
      "act8_constancy"
    ],
    [
      "act7_sin",
      "end_honest"
    ],
    [
      "act8_constancy",
      "end_immortal"
    ],
    [
      "act8_constancy",
      "end_poet"
    ],
    [
      "act8_constancy",
      "act8_apology"
    ],
    [
      "act8_apology",
      "end_immortal"
    ],
    [
      "act8_apology",
      "end_poet"
    ]
  ]
};
