// Auto-generated by story_graph.py — do not edit by hand
const STORY_DATA = {
  "nodes": {
    "start": {
      "title": "The History Paper",
      "text": "Alex is thirteen and has a history paper due tomorrow. The question, written at the top of an empty page, is: '*When did the modern world begin?*'\n\nThe school library is almost empty. Alex has six textbooks open: Elizabeth I, the Spanish Empire, the Thirty Years' War, the Enlightenment, the Industrial Revolution, World War I. Four hundred years of history. One essay question. No thesis.\n\nAlex's head drops.\n\nWhen it rises, the library is gone. Alex is standing in a torchlit corridor lined with portraits -- kings and queens, generals and philosophers, revolutionaries and tyrants. Each portrait is a doorway.\n\nA voice from nowhere says: '*The modern world did not begin once. It began several times, in several places, for several reasons. You will not find a single answer. You will find a question that keeps changing shape.*'\n\n'*The question is: who has the right to rule -- and by what authority?*'\n\nThe portraits glow. Each leads to a different century, a different answer.",
      "choices": [
        {
          "text": "A woman in a white ruff: Elizabeth I's England (1558)",
          "target": "act2_elizabeth"
        },
        {
          "text": "A man in dark armor: the Spanish Empire (1492)",
          "target": "act3_empire"
        },
        {
          "text": "A shattered window: the Thirty Years' War (1618)",
          "target": "act4_war"
        },
        {
          "text": "This is a history paper, not an adventure. Summarize and go home.",
          "target": "end_surface"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "frame",
      "vocabulary": [
        {
          "term": "the modern world",
          "definition": "The era beginning roughly 1500-1700, defined by the rise of nation-states, scientific method, individual rights, and global trade"
        }
      ],
      "figures": [],
      "tags": [
        "opening",
        "frame"
      ]
    },
    "end_surface": {
      "title": "The Summary",
      "text": "Alex writes a competent summary: the modern world began with the Enlightenment, probably around 1687 when Newton published the *Principia*, or maybe 1689 with the English Bill of Rights. The paper gets a B+.\n\nIt is the right kind of answer for a test. It is the wrong kind of answer for understanding. History is not a timeline with a starting flag. It is a conversation between centuries, and the question '*who has the right to rule?*' is still being argued in every election, every courtroom, every revolution.\n\nAlex puts the textbooks away and goes home. The portraits in the library corridor -- the ones Alex did not notice before -- watch silently.\n\nSome doors wait.",
      "choices": [],
      "is_ending": true,
      "ending_type": "neutral",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "neutral"
      ]
    },
    "act2_elizabeth": {
      "title": "The Queen Who Would Not Open Windows",
      "text": "Alex steps through the portrait and into a throne room. A woman sits at the center -- red-haired, sharp-eyed, dripping with pearls. She is the most powerful person in England and she knows it.\n\n'I will not open windows into men's souls,' Elizabeth says. Her voice carries the weight of someone who has survived assassination plots, religious wars, and a childhood in the Tower of London.\n\nShe is talking about religion. England has been torn apart -- Catholic under her father Henry VIII (then Protestant, then Catholic again under her sister Mary). Elizabeth's solution is the *Elizabethan Settlement*: England will be Protestant, officially, but Catholic forms of worship will be kept. Attend church. Pay the fine if you don't. Beyond that, believe what you like.\n\n'It is a compromise,' she says. 'Puritans hate it because it is not pure enough. Catholics hate it because it is not Catholic enough. But it *works*. England has peace. My father's England did not.'\n\nOutside, the Spanish Armada is being prepared. Philip II of Spain has 130 ships and the blessing of the Pope. Elizabeth has Francis Drake, bad weather, and the English Channel.",
      "choices": [
        {
          "text": "Stay in England -- see what happens after Elizabeth",
          "target": "act2_civil_war"
        },
        {
          "text": "Go to Spain -- see Philip II's empire",
          "target": "act3_empire"
        },
        {
          "text": "Ask about the scientists -- Bacon, Newton, the Royal Society",
          "target": "act2_science"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "england",
      "vocabulary": [
        {
          "term": "Elizabethan Settlement",
          "definition": "Religious compromise (1559-1563) making England officially Protestant while retaining Catholic forms of worship -- 'I will not open windows into men's souls'"
        },
        {
          "term": "Spanish Armada",
          "definition": "Philip II's fleet of 130 ships sent to invade England in 1588; defeated by English navy and storms; roughly half the ships destroyed"
        },
        {
          "term": "divine right of kings",
          "definition": "The belief that a monarch's authority comes directly from God and cannot be limited by Parliament -- used by James I and Charles I after Elizabeth"
        }
      ],
      "figures": [],
      "tags": [
        "england",
        "elizabeth"
      ]
    },
    "act2_civil_war": {
      "title": "The King Loses His Head",
      "text": "Time shifts. Elizabeth is dead. James I, then Charles I -- kings who believe in *divine right*, that their authority comes from God and no Parliament can limit it.\n\nCharles I dissolves Parliament. He raises taxes without consent. He imprisons opponents. Parliament fights back with the *Petition of Right* (1628): no imprisonment without cause, no taxes without consent.\n\nCharles ignores it. England erupts into civil war: Cavaliers (king) versus Roundheads (Parliament). Oliver Cromwell leads the Parliamentary army to victory.\n\nAnd then something unprecedented happens. On January 30, 1649, King Charles I is publicly tried, convicted, and *beheaded*. The first reigning European monarch to be executed by his own people.\n\nAlex watches the crowd. Some weep. Some cheer. All of them know the world has changed. If a king can be killed by his subjects, then the king's authority is not absolute. It depends on something -- on *consent*, on *law*, on the agreement between ruler and ruled.\n\nCromwell rules as Lord Protector. He is not a king. He has near-kingly powers. He refuses the crown. When he dies in 1658, the Commonwealth collapses.",
      "choices": [
        {
          "text": "See the Glorious Revolution -- what replaces the Commonwealth?",
          "target": "act2_glorious"
        },
        {
          "text": "Jump to the Enlightenment -- where does consent theory lead?",
          "target": "act5_reason"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "england",
      "vocabulary": [
        {
          "term": "Petition of Right (1628)",
          "definition": "Parliament demanded Charles I acknowledge limits: no imprisonment without cause, no taxes without consent, no billeting soldiers"
        },
        {
          "term": "English Civil War (1642-1651)",
          "definition": "Cavaliers (royalists) vs. Roundheads (Parliament); ended with execution of Charles I -- the first European king publicly tried and beheaded"
        },
        {
          "term": "Commonwealth (1649-1653)",
          "definition": "Republican government after Charles I's execution; no king; governed by Parliament and Council of State"
        },
        {
          "term": "Oliver Cromwell",
          "definition": "Leader of the Parliamentary army and Lord Protector (1653-1658); refused the crown but held near-kingly powers"
        }
      ],
      "figures": [],
      "tags": [
        "england",
        "civil_war"
      ]
    },
    "act2_glorious": {
      "title": "The Revolution Without Blood",
      "text": "The monarchy returns -- Charles II, then James II, who is Catholic and determined to restore Catholic power. Parliament has had enough.\n\nIn 1688, Parliament invites William of Orange and his wife Mary (James's daughter) to take the throne. James II flees. Almost no blood is spilled on English soil. They call it the *Glorious Revolution*.\n\nThe price of the crown: the *English Bill of Rights* (1689). Suspending laws without Parliament's consent is illegal. Standing armies in peacetime require consent. Elections must be free. No cruel and unusual punishments.\n\n'*Parliamentary supremacy,*' Alex reads. Parliament is the supreme law-making authority. No monarch may override it. The king rules *under* law, not above it.\n\nAnd there is *habeas corpus* -- confirmed in 1679. The government cannot imprison you without charging you and bringing you before a court. '*You shall have the body.*' Four Latin words that protect every person from arbitrary power.\n\nAlex thinks: this is the answer Elizabeth was groping toward. Not divine right. Not absolute power. *Accountable* power. Power that must justify itself.",
      "choices": [
        {
          "text": "See the Scientific Revolution -- another kind of authority challenged",
          "target": "act2_science"
        },
        {
          "text": "Jump to the Enlightenment -- Locke, Voltaire, and the rights of man",
          "target": "act5_reason"
        },
        {
          "text": "Jump to WWI -- see where the balance of power ends",
          "target": "act7_alliances"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "england",
      "vocabulary": [
        {
          "term": "Glorious Revolution (1688)",
          "definition": "Transfer of crown from James II to William and Mary; nearly bloodless; permanently established parliamentary supremacy"
        },
        {
          "term": "English Bill of Rights (1689)",
          "definition": "No suspending laws without Parliament; free elections; no cruel punishment; standing armies require consent"
        },
        {
          "term": "parliamentary supremacy",
          "definition": "Parliament is the supreme law-making authority; no monarch may override it"
        },
        {
          "term": "habeas corpus",
          "definition": "'You shall have the body'; government cannot imprison without charge; confirmed by Habeas Corpus Act of 1679"
        }
      ],
      "figures": [],
      "tags": [
        "england",
        "glorious"
      ]
    },
    "act2_science": {
      "title": "Take Nobody's Word for It",
      "text": "While kings and parliaments fight over political authority, another revolution is happening in the laboratories and observatories.\n\nFrancis Bacon publishes *Novum Organum* (1620): '*Nature, to be commanded, must be obeyed.*' His *inductive method* -- start with observations, test through experiment, then draw conclusions -- overturns 1,500 years of arguing from authority. Truth is not found in old books. Truth is found by *looking*.\n\nThe Royal Society is founded in 1660. Its motto: *Nullius in verba* -- 'Take nobody's word for it.' The oldest continuously operating scientific society in the world.\n\nAnd then Isaac Newton. The *Principia Mathematica* (1687) -- possibly the most important book in the history of science. Three laws of motion. Universal gravitation. The same force that makes an apple fall holds the moon in orbit.\n\nAlex sees the connection: the Scientific Revolution and the political revolution are the same revolution, fought on different fronts. In both, the question is: *who has the authority to tell you what is true?* A king? A church? An ancient philosopher? Or the evidence of your own eyes, tested by reason and experiment?",
      "choices": [
        {
          "text": "Follow this to the Enlightenment",
          "target": "act5_reason"
        },
        {
          "text": "Go to Spain -- the other superpower",
          "target": "act3_empire"
        },
        {
          "text": "Go to the Thirty Years' War -- the collapse of the old order",
          "target": "act4_war"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "england",
      "vocabulary": [
        {
          "term": "inductive method",
          "definition": "Francis Bacon's approach: start with observations, test through experiment, then draw conclusions; contrasted with arguing from authority"
        },
        {
          "term": "Nullius in verba",
          "definition": "'Take nobody's word for it'; motto of the Royal Society (founded 1660); oldest continuously operating scientific society"
        },
        {
          "term": "Principia Mathematica (1687)",
          "definition": "Newton's masterwork: three laws of motion, universal gravitation; possibly the most important book in the history of science"
        }
      ],
      "figures": [],
      "tags": [
        "england",
        "science"
      ]
    },
    "act3_empire": {
      "title": "The Empire on Which the Sun Never Sets",
      "text": "1492. Three things happen in Spain in a single year: the fall of Granada (ending the *Reconquista*), the *Alhambra Decree* (expelling all Jews), and Columbus sails west.\n\nWithin a generation, Spain controls the largest empire the world has ever seen. Cortes takes the Aztec capital Tenochtitlan (1521) -- a city larger than any in Europe. Pizarro conquers the Inca. Silver pours from the mines of Potosi in such quantities that it reshapes the global economy.\n\nThe *Manila Galleon* carries American silver to China in exchange for silk and porcelain -- the first truly global trade system. The *Columbian Exchange* transforms agriculture on every continent: potatoes, tomatoes, corn, and cacao go east; horses, cattle, and *disease* go west.\n\nBut there is a price. The *mita* system forces indigenous workers into mines where they breathe mercury vapor. An estimated 8 million die at Potosi alone. The *casta* system ranks human beings by race in a hierarchy of 40+ gradations.\n\nAnd all that silver? Philip II goes bankrupt *four times*. Raw extraction is not the same as a real economy.",
      "choices": [
        {
          "text": "Meet Las Casas -- the priest who said no",
          "target": "act3_casas"
        },
        {
          "text": "Meet Cervantes -- the writer who saw through the illusion",
          "target": "act3_quixote"
        },
        {
          "text": "Jump to the Thirty Years' War -- Spain's decline begins",
          "target": "act4_war"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "spain",
      "vocabulary": [
        {
          "term": "Reconquista",
          "definition": "Centuries-long Christian reconquest of Iberia from Muslim rulers, ending with the fall of Granada in 1492"
        },
        {
          "term": "Columbian Exchange",
          "definition": "Transfer of plants, animals, diseases, and people between Americas and the rest of the world after 1492; named by historian Alfred Crosby"
        },
        {
          "term": "Manila Galleon",
          "definition": "Annual ship from Acapulco to Manila (1565-1815); carried New World silver to China; first global trade system"
        },
        {
          "term": "mita",
          "definition": "Inca labor system adapted by Spain for mines; workers descended hundreds of feet underground and breathed mercury vapor; millions died"
        },
        {
          "term": "casta system",
          "definition": "Racial hierarchy of colonial Spanish America; peninsulares > criollos > mestizos > indigenous > enslaved Africans"
        }
      ],
      "figures": [],
      "tags": [
        "spain",
        "empire"
      ]
    },
    "act3_casas": {
      "title": "The Priest Who Said No",
      "text": "Bartolome de las Casas was a Spanish priest who owned enslaved people. Then he read his Bible more carefully.\n\nIn 1542, he publishes *A Short Account of the Destruction of the Indies*: '*I speak of what I myself saw. I was there.*' He describes atrocities committed against indigenous peoples by Spanish colonists. He argues from Christian theology: every human being is made in the *imago Dei* -- the image of God. If that is true, then enslaving them is a sin against the Creator.\n\nAt the Debate of Valladolid (1550-1551), Las Casas faces Juan Gines de Sepulveda, who argues that indigenous peoples are 'natural slaves' (using Aristotle). Las Casas responds: God made all peoples capable of receiving the Gospel. Slavery is a crime against divine law.\n\nHe does not win immediately. The *New Laws* of 1542 limit the worst abuses but are widely ignored. Las Casas dies in 1566, still fighting.\n\nAlex recognizes something: Las Casas is a *prophetic witness from within the system*. He uses the language and theology of the empire to condemn the empire's actions. The most powerful critics of injustice are often insiders who refuse to look away.",
      "choices": [
        {
          "text": "See Don Quixote -- another insider's critique",
          "target": "act3_quixote"
        },
        {
          "text": "Follow prophetic witness to Equiano and the slave trade",
          "target": "act6_expansion"
        },
        {
          "text": "Go to the Enlightenment -- where do natural rights come from?",
          "target": "act5_reason"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "spain",
      "vocabulary": [
        {
          "term": "Bartolome de las Casas",
          "definition": "Spanish priest (1484-1566); former slaveholder turned fierce critic; 'I speak of what I myself saw'; argued from imago Dei against enslaving indigenous peoples"
        },
        {
          "term": "imago Dei",
          "definition": "'Image of God'; every human being has inherent dignity from Genesis 1:27; used by Las Casas, Equiano, and Leo XIII to argue against exploitation"
        },
        {
          "term": "Debate of Valladolid (1550-1551)",
          "definition": "Formal inquiry into whether Spain's conquest was morally just; Las Casas vs. Sepulveda; first major European debate on human rights"
        },
        {
          "term": "prophetic witness",
          "definition": "Using the language and values of a system to condemn that system's actions -- Las Casas, Equiano, Caliban"
        }
      ],
      "figures": [],
      "tags": [
        "spain",
        "casas"
      ]
    },
    "act3_quixote": {
      "title": "The Knight of the Sorrowful Countenance",
      "text": "Miguel de Cervantes fought at the Battle of Lepanto (1571), was wounded, captured by pirates, spent five years in an Algerian prison, and came home to write the first modern novel.\n\n*Don Quixote* (1605/1615): an old man reads so many chivalric romances that he goes mad and believes he is a knight-errant. He attacks windmills, thinking they are giants. He frees prisoners, thinking they are captives. He sees beauty where there is none and honor where there is only dust.\n\nIt is very funny. It is also devastating.\n\nBecause Don Quixote is Spain. A country that lives in the rhetoric of crusade and empire while the ground beneath it shifts. Philip II's bankruptcies. The Armada's defeat. The expulsion of the Moriscos (300,000 skilled people). The silver that flows in and flows out without building anything lasting.\n\n'*The truth,*' Cervantes writes, '*whose mother is history, rival of time, depository of deeds, witness of the past.*'\n\nAlex thinks: ideals matter. But ideals disconnected from reality become their own kind of madness. Don Quixote is noble *and* ridiculous, and Cervantes refuses to let you choose between the two.",
      "choices": [
        {
          "text": "Go to the Thirty Years' War -- ideals vs. reality, writ large",
          "target": "act4_war"
        },
        {
          "text": "Go to the Enlightenment -- reason tries to replace idealism",
          "target": "act5_reason"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "spain",
      "vocabulary": [
        {
          "term": "Don Quixote (1605/1615)",
          "definition": "Cervantes' novel; 'first modern novel'; an old man driven mad by chivalric romances; attacks windmills; figure for Spain itself, living in crusade rhetoric while the world changes"
        },
        {
          "term": "Miguel de Cervantes",
          "definition": "Spanish writer (1547-1616); wounded at Lepanto, imprisoned in Algiers; wrote Don Quixote, the first modern novel"
        }
      ],
      "figures": [],
      "tags": [
        "spain",
        "quixote"
      ]
    },
    "act4_war": {
      "title": "The Window",
      "text": "Prague, 1618. Protestant nobles throw three Catholic officials out of a castle window. They fall seventy feet. (They survive -- Catholics say angels caught them; Protestants say they landed in a dung heap.)\n\nThis is the *Defenestration of Prague*, and it triggers the Thirty Years' War -- the deadliest conflict in European history before the twentieth century.\n\nIt begins as a religious war: Protestants vs. Catholics in the Holy Roman Empire. But it becomes something else. Catholic France, under Cardinal Richelieu, funds *Protestant* armies against Catholic Austria. Why? *Raison d'etat* -- reason of state. National interest now matters more than religious solidarity.\n\nGermany is destroyed. Twenty-five to thirty-three percent of the population dies. The Sack of Magdeburg (1631) kills 20,000 civilians. Schiller writes: '*In less than twelve hours, this fine and populous city was reduced to ashes.*'\n\nWhen it ends, the combatants are so exhausted that they try something new. Instead of a victor's peace, they negotiate a *balanced* peace -- one that includes everyone, assigns no blame, and establishes rules for coexistence.",
      "choices": [
        {
          "text": "See the Peace of Westphalia -- the birth of the modern state",
          "target": "act4_peace"
        },
        {
          "text": "Compare this to WWI -- another war that destroyed a generation",
          "target": "act7_alliances"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "westphalia",
      "vocabulary": [
        {
          "term": "Defenestration of Prague (1618)",
          "definition": "Protestant nobles threw Catholic officials out of a castle window, triggering the Thirty Years' War; from Latin fenestra (window)"
        },
        {
          "term": "Thirty Years' War (1618-1648)",
          "definition": "Last great religious war / first modern war; began as Protestant vs. Catholic, became a contest of national interests; Germany lost 25-33% of its population"
        },
        {
          "term": "raison d'etat",
          "definition": "'Reason of state'; government may act on national interest even against moral or religious principles; Richelieu's justification for Catholic France funding Protestant armies"
        }
      ],
      "figures": [],
      "tags": [
        "westphalia",
        "war"
      ]
    },
    "act4_peace": {
      "title": "The Birth Certificate of the Modern World",
      "text": "The Peace of Westphalia (1648). Two treaties signed simultaneously in Osnabruck and Munster. Historians call it the '*birth certificate of the modern state system.*'\n\nThree principles:\n\n*State sovereignty*: each ruler has supreme authority within their own territory. No emperor, no pope can override them.\n\n*Equality of sovereign states*: all recognized states are legally equal, regardless of size. The Netherlands counts as much as France.\n\n*Non-interference*: no state may meddle in the internal affairs of another.\n\nAlex realizes: these three principles are the *operating system* of the modern world. The United Nations is built on them. International law assumes them. Every passport, every border, every embassy exists because of what was decided in 1648.\n\nBut there is a trade-off. Sovereignty means no external authority can stop a ruler from oppressing their own people. The *balance of power* -- the idea that no single nation should dominate -- works only as long as nations balance each other. When the balance breaks...\n\nHugo Grotius, writing before Westphalia, had already asked: are there rules that bind *all* nations, even in war? '*Natural law governs nations as it governs individuals.*'",
      "choices": [
        {
          "text": "Follow the Enlightenment -- natural law becomes natural rights",
          "target": "act5_reason"
        },
        {
          "text": "See how the balance of power breaks -- Louis XIV, Napoleon, WWI",
          "target": "act7_alliances"
        },
        {
          "text": "Go to the Industrial Revolution -- a different kind of power",
          "target": "act6_industrial"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "westphalia",
      "vocabulary": [
        {
          "term": "Peace of Westphalia (1648)",
          "definition": "'Birth certificate of the modern state system'; established sovereignty, equality of states, and non-interference; included all parties and assigned no blame"
        },
        {
          "term": "sovereignty",
          "definition": "Supreme authority of government over its territory, free from outside control; central principle established at Westphalia"
        },
        {
          "term": "balance of power",
          "definition": "No single nation should dominate all others; conscious goal of European diplomacy after Westphalia; works only as long as nations balance each other"
        },
        {
          "term": "Hugo Grotius",
          "definition": "'Father of international law'; argued natural law governs nations as it governs individuals; even in war, certain things are forbidden"
        }
      ],
      "figures": [],
      "tags": [
        "westphalia",
        "peace"
      ]
    },
    "act5_reason": {
      "title": "The Age of Reason",
      "text": "Descartes: '*Cogito, ergo sum*' -- I think, therefore I am. Doubt everything except the mind that doubts. Newton: mathematics describes the universe. Locke: the mind at birth is a *tabula rasa* -- a blank slate written on by experience.\n\nThese three ideas combine into something explosive: if the universe runs on discoverable laws, and if human reason can discover them, then *everything* can be improved by applying reason -- government, law, education, religion, economics, medicine.\n\nJohn Locke writes the *Second Treatise of Government* (1689): in the state of nature, all people are free and equal. They have *natural rights* -- life, liberty, and property. Government exists to protect these rights. If it fails, the people may replace it.\n\nThis is the *social contract*: government by consent. Not divine right. Not tradition. Not force. *Agreement*.\n\nAlex watches the idea ripple outward: to Jefferson ('*life, liberty, and the pursuit of happiness*'), to the French Declaration of the Rights of Man, to every democratic constitution written since.",
      "choices": [
        {
          "text": "Meet Voltaire -- reason's sharpest voice",
          "target": "act5_voltaire"
        },
        {
          "text": "See the French Revolution -- where reason meets reality",
          "target": "act5_revolution"
        },
        {
          "text": "See the Industrial Revolution -- reason applied to production",
          "target": "act6_industrial"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "enlightenment",
      "vocabulary": [
        {
          "term": "cogito, ergo sum",
          "definition": "'I think, therefore I am'; Descartes' foundational certainty (1637); the starting point of modern philosophy"
        },
        {
          "term": "natural rights",
          "definition": "Rights belonging to every person by nature: life, liberty, property (Locke) / 'life, liberty, pursuit of happiness' (Jefferson)"
        },
        {
          "term": "social contract",
          "definition": "Government formed by agreement among people who consent to be governed; if government breaks the contract, the people may replace it"
        },
        {
          "term": "John Locke",
          "definition": "English philosopher (1632-1704); Second Treatise of Government; natural rights, consent of the governed, right to revolution"
        }
      ],
      "figures": [],
      "tags": [
        "enlightenment",
        "reason"
      ]
    },
    "act5_voltaire": {
      "title": "Cultivate Your Garden",
      "text": "Voltaire is the sharpest pen in Europe. He is also the most dangerous, which is why he has been imprisoned in the Bastille (twice) and exiled to England.\n\nIn 1755, an earthquake destroys Lisbon. Thirty thousand dead. Churches collapse on congregations. Voltaire writes *Candide* (1759): a young man taught by his tutor that this is '*the best of all possible worlds*' is dragged through war, slavery, torture, and natural disaster.\n\nIn Surinam, Candide meets an enslaved man whose hand and leg have been cut off. The man says: '*This is the price at which you eat sugar in Europe.*'\n\nThe novel ends with a strange, quiet sentence: '*We must cultivate our garden.*' Alex puzzles over it. Is Voltaire saying give up on the big questions? Or is he saying: do the work in front of you. Fix what you can. The best of all possible worlds is a lie, but a well-tended garden is not.\n\nThe *Encyclopedie* (1751-1772) -- 35 volumes, 70,000 articles -- tries to put all human knowledge in one place. Banned twice. Condemned by the Pope. Sold 20,000 copies. Ideas are harder to burn than books.",
      "choices": [
        {
          "text": "See the French Revolution -- the Enlightenment's test",
          "target": "act5_revolution"
        },
        {
          "text": "Follow the sugar trail -- Equiano and the slave trade",
          "target": "act6_expansion"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "enlightenment",
      "vocabulary": [
        {
          "term": "Voltaire",
          "definition": "French philosopher (1694-1778); imprisoned, exiled; wrote Candide; fought for religious tolerance and freedom of expression"
        },
        {
          "term": "Candide (1759)",
          "definition": "Voltaire's satirical novel; attacks the idea that 'this is the best of all possible worlds'; 'We must cultivate our garden'"
        },
        {
          "term": "Encyclopedie (1751-1772)",
          "definition": "35 volumes, 70,000 articles, 150 contributors; edited by Diderot and d'Alembert; banned twice, condemned by Pope; attempt to collect all human knowledge"
        }
      ],
      "figures": [],
      "tags": [
        "enlightenment",
        "voltaire"
      ]
    },
    "act5_revolution": {
      "title": "Liberty, Equality, Fraternity",
      "text": "1789. The French Revolution begins. The Declaration of the Rights of Man proclaims: '*Men are born and remain free and equal in rights.*' The Bastille falls. The old regime collapses.\n\nThen the revolution eats its children.\n\nRobespierre and the Committee of Public Safety declare the *Reign of Terror*. More than 17,000 are guillotined. The revolution that began with the Rights of Man ends with a dictator named Napoleon.\n\nAlex asks: what went wrong? The answer may lie in Rousseau's *general will* -- the idea that the community as a whole has a single true interest. If you disagree with the general will, you are not exercising freedom; you are *mistaken about your own freedom*. And the state may force you to be free.\n\nCompare the American Revolution (1776): conservative, grounded in specific English rights, preserving institutions while improving them. The French Revolution was *radical*: tear everything down and rebuild from abstract Reason. One produced a republic that endured. The other produced Napoleon.\n\nIdeas have consequences beyond their authors' intentions. Locke did not intend the Terror. But the Terror is what happened when his ideas were pushed to an extreme he never imagined.",
      "choices": [
        {
          "text": "See the Industrial Revolution -- another transformation",
          "target": "act6_industrial"
        },
        {
          "text": "Jump to WWI -- the final collapse of the old order",
          "target": "act7_alliances"
        },
        {
          "text": "This is the key lesson. Write it down.",
          "target": "end_consequences"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "enlightenment",
      "vocabulary": [
        {
          "term": "French Revolution (1789)",
          "definition": "Began with the Rights of Man, ended with the Terror and Napoleon; radical attempt to rebuild society from abstract Reason"
        },
        {
          "term": "Reign of Terror",
          "definition": "1793-1794; 17,000+ guillotined; the revolution that began with human rights ended in systematic killing"
        },
        {
          "term": "general will",
          "definition": "Rousseau's concept of what the community truly wants; dangerous because it can be used to justify forcing people to be 'free'"
        }
      ],
      "figures": [],
      "tags": [
        "enlightenment",
        "revolution"
      ]
    },
    "act6_industrial": {
      "title": "The Machine Age",
      "text": "Britain, c. 1760. Something new: machines powered by coal and steam that can produce goods faster than any human hand. The *Industrial Revolution* transforms how people live, work, and die.\n\nLondon to Edinburgh: four days by coach in 1800. Nine hours by rail in 1850. Samuel Morse sends the first telegraph message in 1844: '*What hath God wrought?*' Information now travels faster than any human can move.\n\nBut the factories are nightmares. Children work sixteen-hour days. Workers breathe cotton dust until their lungs fail. Wages are barely enough to survive. The 'social question' emerges: how should industrial society respond to poverty and exploitation?\n\nThree answers compete:\n\n*Laissez-faire capitalism*: the market will sort it out. Government should not interfere.\n\n*Socialism* (Marx): the workers must seize the means of production. '*Workers of the world, unite!*'\n\n*Catholic Social Teaching* (Pope Leo XIII): workers have God-given dignity. Both laissez-faire and socialism are wrong. There is a third way.",
      "choices": [
        {
          "text": "Hear Marx vs. Leo XIII -- the great debate",
          "target": "act6_marx"
        },
        {
          "text": "Follow expansion outward -- the Scramble for Africa",
          "target": "act6_expansion"
        },
        {
          "text": "Jump to WWI -- industrial technology meets trench warfare",
          "target": "act7_trenches"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "modern",
      "vocabulary": [
        {
          "term": "Industrial Revolution",
          "definition": "Transformation from agriculture to machine manufacturing, beginning Britain c. 1760; coal, steam, iron; transformed how people live, work, and die"
        },
        {
          "term": "social question",
          "definition": "How should industrial society respond to poverty and exploitation? Three competing answers: capitalism, socialism, Catholic Social Teaching"
        },
        {
          "term": "laissez-faire",
          "definition": "'Let it be'; government should not interfere in the economy"
        }
      ],
      "figures": [],
      "tags": [
        "modern",
        "industrial"
      ]
    },
    "act6_marx": {
      "title": "The Workers and the Pope",
      "text": "Karl Marx, *Communist Manifesto* (1848): '*The history of all hitherto existing society is the history of class struggles.*' The *bourgeoisie* owns the factories. The *proletariat* owns nothing but their labor. Revolution is inevitable.\n\nMarx's diagnosis: accurate. Workers *are* exploited. The gap between rich and poor is obscene. Children *are* dying in mines.\n\nMarx's prescription: catastrophic. When his ideas are tried -- Russia (1917), China (1949), Cambodia (1975) -- the result is not workers' paradise but totalitarian nightmare. The Soviet Union. Mao's Cultural Revolution. The killing fields.\n\nPope Leo XIII, *Rerum Novarum* (1891): '*The condition of the working classes is the pressing question of the hour.*' He agrees with Marx that workers are exploited. He disagrees on the solution.\n\nWorkers are not commodities. They are made in the *imago Dei*. Private property is a natural right -- but so is a *just wage*. Workers have the right to form unions. The state has a duty to protect the vulnerable. Neither laissez-faire nor socialism respects human dignity.\n\nAlex writes in the margins: '*Marx saw the disease. Leo XIII found a better cure.*'",
      "choices": [
        {
          "text": "See expansion and colonialism -- the global dimension",
          "target": "act6_expansion"
        },
        {
          "text": "Jump to WWI -- where all these tensions explode",
          "target": "act7_alliances"
        },
        {
          "text": "The third way is the answer. Write it down.",
          "target": "end_dignity"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "modern",
      "vocabulary": [
        {
          "term": "Communist Manifesto (1848)",
          "definition": "Marx and Engels; 'history of all hitherto existing society is the history of class struggles'; calls for workers to seize means of production"
        },
        {
          "term": "bourgeoisie",
          "definition": "Marxist term for the class that owns the means of production -- factories, land, capital"
        },
        {
          "term": "proletariat",
          "definition": "Marxist term for the working class who own nothing and must sell their labor"
        },
        {
          "term": "Rerum Novarum (1891)",
          "definition": "Pope Leo XIII's encyclical; founding document of Catholic Social Teaching; workers have God-given right to just wages, safe conditions, and unions"
        },
        {
          "term": "just wage",
          "definition": "A wage sufficient for a family to live in reasonable dignity; a moral floor below which no employer may go"
        }
      ],
      "figures": [],
      "tags": [
        "modern",
        "marx"
      ]
    },
    "act6_expansion": {
      "title": "The Price of Sugar",
      "text": "The *triangle trade* circles the Atlantic: European goods to Africa, enslaved people to the Americas, colonial products back to Europe. The *Middle Passage* -- four to eight weeks across the ocean -- kills an estimated 1.8 million people. Twelve million survive it.\n\nOlaudah Equiano, a formerly enslaved man, publishes his *Interesting Narrative* (1789). He writes in the language of his captors and uses both Enlightenment natural rights and Christian *imago Dei* to condemn the trade. Like Las Casas, he is a prophetic witness from within the system.\n\nThe abolition movement combines Christian conscience and Enlightenment reason. William Wilberforce fights for twenty years. Britain abolishes the slave trade in 1807 and slavery itself in 1833. (Compensation is paid to slaveholders. Not to the enslaved.)\n\nMeanwhile, at the Berlin Conference (1884-85), European powers divide Africa among themselves. No African is invited. By 1914, European nations control roughly 84% of the world's land surface.\n\nAlex sees the pattern: Christian conscience both enabled colonialism *and* produced its most effective critics. The same tradition that justified empire also condemned it.",
      "choices": [
        {
          "text": "Go to WWI -- where empire and the balance of power collide",
          "target": "act7_alliances"
        },
        {
          "text": "Prophetic witness is the thread. Follow it.",
          "target": "end_witness"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "modern",
      "vocabulary": [
        {
          "term": "Middle Passage",
          "definition": "Sea journey from West Africa to Americas; 4-8 weeks; ~1.8 million died of ~12 million transported"
        },
        {
          "term": "triangle trade",
          "definition": "Atlantic circuit: European goods to Africa, enslaved people to Americas, colonial products to Europe"
        },
        {
          "term": "Olaudah Equiano",
          "definition": "Formerly enslaved man (c. 1745-1797); Interesting Narrative (1789); used Enlightenment rights and Christian imago Dei to condemn the trade"
        },
        {
          "term": "Berlin Conference (1884-85)",
          "definition": "European powers established rules for colonial division of Africa; no African invited; led to 'Scramble for Africa'"
        }
      ],
      "figures": [],
      "tags": [
        "modern",
        "expansion"
      ]
    },
    "act7_alliances": {
      "title": "The Powder Keg",
      "text": "Europe in 1914: a network of alliances designed to prevent war. Triple Alliance (Germany, Austria-Hungary, Italy) vs. Triple Entente (France, Russia, Britain). If one country is attacked, its allies must respond.\n\nJune 28, 1914: a Bosnian Serb named Gavrilo Princip assassinates Archduke Franz Ferdinand of Austria in Sarajevo. Austria threatens Serbia. Russia mobilizes to protect Serbia. Germany supports Austria. France supports Russia. Britain supports France. In six weeks, a regional crisis becomes a *world war*.\n\nThe alliance system was supposed to *deter* war. Instead, it made a small fire into a continental inferno. Military timetables moved faster than diplomats could negotiate.\n\nGermany's *Schlieffen Plan*: knock out France in six weeks through Belgium, then turn east to face Russia. It fails at the First Battle of the Marne (September 1914). Both sides dig in.\n\nFor the next four years, the Western Front barely moves.",
      "choices": [
        {
          "text": "Enter the trenches",
          "target": "act7_trenches"
        },
        {
          "text": "Skip to the peace -- Versailles vs. Westphalia",
          "target": "act7_peace"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "war",
      "vocabulary": [
        {
          "term": "alliance system",
          "definition": "Network of defense treaties; Triple Alliance vs. Triple Entente; designed to deter war but converted a regional crisis into world war"
        },
        {
          "term": "Schlieffen Plan",
          "definition": "Germany's strategy to knock out France in 6 weeks through Belgium, then face Russia; failed at the First Battle of the Marne (1914)"
        }
      ],
      "figures": [],
      "tags": [
        "war",
        "alliances"
      ]
    },
    "act7_trenches": {
      "title": "No Man's Land",
      "text": "The trenches. Parallel lines of mud, barbed wire, and machine guns stretching from the English Channel to Switzerland. Between them: *No Man's Land*.\n\nJuly 1, 1916: the first day of the Battle of the Somme. British soldiers go 'over the top.' Machine guns cut them down in rows. 57,000 British casualties in a single day. 20,000 dead. The bloodiest day in British military history.\n\nVerdun (1916): ten months. 700,000 dead.\n\nIndustrial technology has made offense impossible and defense impregnable. Machine guns, artillery, barbed wire -- the tools of the factory turned into tools of killing. The technology that built the railroad now builds the trench.\n\nThree writers bear witness:\n\n**Ernst Junger** (*Storm of Steel*): war as test of the human spirit. '*I had never felt more fully alive.*'\n\n**Erich Maria Remarque** (*All Quiet on the Western Front*): '*We are not youth any longer. We believe in such things no longer. We believe in the war.*'\n\n**Wilfred Owen** ('Dulce et Decorum Est'): '*The old Lie: Dulce et decorum est / Pro patria mori.*' Owen is killed November 4, 1918 -- one week before the Armistice. His mother receives the telegram as church bells ring for peace.",
      "choices": [
        {
          "text": "See the peace -- how do you end a war like this?",
          "target": "act7_peace"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "war",
      "vocabulary": [
        {
          "term": "trench warfare",
          "definition": "Opposing armies in parallel trench systems; machine guns and barbed wire made defense impregnable; Western Front barely moved for 4 years"
        },
        {
          "term": "Battle of the Somme (1916)",
          "definition": "57,000 British casualties on the first day alone; 20,000 dead; the bloodiest single day in British military history"
        },
        {
          "term": "Dulce et decorum est pro patria mori",
          "definition": "'It is sweet and fitting to die for one's country'; Owen called it 'the old Lie'; from Horace"
        }
      ],
      "figures": [],
      "tags": [
        "war",
        "trenches"
      ]
    },
    "act7_peace": {
      "title": "Westphalia and Versailles",
      "text": "November 11, 1918. Armistice. Seventeen million dead. Twenty million wounded.\n\nThe Treaty of Versailles (June 28, 1919) is meant to end the war. Instead, it plants the seeds of the next one.\n\nThe *war guilt clause* (Article 231): Germany accepts responsibility for all losses. Most Germans consider it a lie. *Reparations*: 132 billion gold marks -- effectively unpayable. Germany loses territory, colonies, and most of its military. Germany is not invited to negotiate. The treaty is a *diktat* -- dictated, not agreed.\n\nAlex pulls out the notes on Westphalia and compares:\n\n*Westphalia (1648)*: included all parties. Assigned no blame. Established equality of states. Lasted 150 years.\n\n*Versailles (1919)*: excluded the defeated. Assigned total guilt. Humiliated the losers. Collapsed within a generation.\n\nWilson's *Fourteen Points* -- open diplomacy, self-determination, a *League of Nations* -- were idealistic and partly wise. But the League has no army, no enforcement mechanism, and the United States never joins.\n\nThe Weimar Republic -- Germany's first democracy -- is born associated with defeat and humiliation. The conditions for a second war are already assembling.",
      "choices": [
        {
          "text": "The balance of power is the lesson. Write it down.",
          "target": "end_balance"
        },
        {
          "text": "Peacemaking is the lesson. Write it down.",
          "target": "end_peace"
        },
        {
          "text": "The whole arc -- from Elizabeth to Versailles -- is one story.",
          "target": "end_arc"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "war",
      "vocabulary": [
        {
          "term": "Treaty of Versailles (1919)",
          "definition": "War guilt clause, massive reparations, loss of territory; Germany excluded from negotiations; planted seeds of WWII"
        },
        {
          "term": "war guilt clause (Article 231)",
          "definition": "Germany accepts responsibility for all war losses; most Germans considered it a lie; source of lasting bitterness"
        },
        {
          "term": "Fourteen Points",
          "definition": "Wilson's peace proposal: open diplomacy, self-determination, League of Nations; partly wise, partly naive"
        },
        {
          "term": "League of Nations",
          "definition": "International organization for collective security; no army, no enforcement; US never joined; fatal flaw"
        }
      ],
      "figures": [],
      "tags": [
        "war",
        "peace"
      ]
    },
    "end_witness": {
      "title": "The Voice from Within",
      "text": "Alex writes the paper about prophetic witness -- the thread that runs from Las Casas through Equiano through Wilberforce through Leo XIII. People who used the language and values of the system to condemn the system's actions. Insiders who refused to look away.\n\nThe paper argues: the most powerful critics of injustice are not outsiders throwing stones. They are insiders who take the system's own promises seriously -- and hold it accountable when it fails to keep them.\n\nThe teacher writes in the margin: '*This is not the paper I expected. It is much better.*'\n\nAlex remembers Caliban, from Shakespeare's *Tempest*: '*You taught me language; and my profit on't / Is, I know how to curse.*' The oppressed learn the oppressor's language and turn it into a weapon of truth.\n\nSome voices cannot be silenced. Not because they are loud, but because they speak in words the powerful cannot dismiss -- their own.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "modern",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "best"
      ]
    },
    "end_balance": {
      "title": "The Scale That Tips",
      "text": "Alex writes the paper about the balance of power -- the idea born at Westphalia that no single nation should dominate. It worked for 150 years. Then the alliance system turned it into a trap, and the trap sprung in 1914.\n\nThe paper argues: the balance of power is not a solution. It is a *method* -- a way of managing rivalry without war. When it works, the world has peace. When it fails, the world has the Somme.\n\nThe teacher writes: '*You have understood the most important lesson in modern history: systems are only as good as the people who maintain them.*'\n\nAlex thinks about this for years. Every institution -- every democracy, every alliance, every treaty -- is a balance. It requires constant attention, constant adjustment, constant willingness to negotiate. The moment anyone assumes the balance will maintain itself, it begins to tip.\n\nThe modern world began when people stopped trusting one authority and started building systems of *balanced* authority. It stays modern only as long as people keep the balance.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "war",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "best"
      ]
    },
    "end_peace": {
      "title": "How to End a War",
      "text": "Alex writes the paper about peacemaking -- comparing Westphalia and Versailles. The argument: how you end a war determines whether the peace lasts.\n\nWestphalia included everyone. It assigned no blame. It treated all parties as sovereign equals. It lasted 150 years. Versailles excluded the defeated, assigned total guilt, and humiliated the losers. It collapsed within a generation.\n\nThe lesson is not that Germany was innocent in 1918. The lesson is that a peace built on humiliation is not peace. It is a countdown.\n\nThe teacher writes: '*The best paper I have received on this topic. You understood that history is not about memorizing dates. It is about recognizing patterns.*'\n\nAlex carries this forward. In every argument, every conflict, every negotiation -- at school, at work, in life -- the same principle holds: a resolution that humiliates the other side is not a resolution. It is a ceasefire.\n\nPeace is not the absence of war. Peace is the presence of justice, maintained by people who remember what happens when it fails.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "war",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good"
      ]
    },
    "end_consequences": {
      "title": "Ideas Have Consequences",
      "text": "Alex writes the paper about unintended consequences. The thesis: ideas are more powerful than their authors imagine, and more dangerous.\n\nLuther did not intend the Thirty Years' War. Locke did not intend the Terror. Marx did not intend the Gulag. The alliance system was designed to *prevent* war and *caused* the worst one in history.\n\nThis does not mean ideas are bad. It means ideas are *serious*. They have weight. They reshape the world in ways their creators cannot predict. The person who writes a sentence about natural rights may be writing the preamble to a revolution they will never see.\n\nThe teacher writes: '*Excellent. You have discovered what historians call the law of unintended consequences. Now apply it to the present.*'\n\nAlex does. Every political argument, every new technology, every reform -- Alex asks: what will this idea do when it leaves the hands of its maker? What will it look like in fifty years, in a hundred, wielded by people who share the conclusion but not the reasoning?\n\nIt is the most useful question history teaches.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "enlightenment",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good"
      ]
    },
    "end_dignity": {
      "title": "The Image of God",
      "text": "Alex writes the paper about human dignity -- the thread that runs from Genesis ('*imago Dei*') through Las Casas through Leo XIII. The argument that every human being has worth that no market, no state, no ideology can override.\n\nMarx saw the exploitation. His solution was revolution. Leo XIII saw the same exploitation. His solution was dignity: workers are not commodities. They are made in the image of God. Pay them a just wage. Give them safe conditions. Let them form unions. Neither unrestrained capitalism nor totalitarian socialism respects what a person actually is.\n\nThe teacher writes: '*You found the third way. Most students pick a side. You picked the person.*'\n\nAlex carries this forward. In every debate about economics, labor, technology, and power, the same question recurs: does this policy treat people as ends or as means? As images of God or as resources to be optimized?\n\nThe question is older than any of the isms. It is as old as Genesis. And it has never been fully answered.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "modern",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "good"
      ]
    },
    "end_arc": {
      "title": "The Long Revolution",
      "text": "Alex writes the paper about the whole arc -- four hundred years compressed into one question that keeps changing shape.\n\nElizabeth I: authority rests on compromise and survival.\nThe English Civil War: authority rests on law, not divine right.\nWestphalia: authority rests on sovereignty and balance.\nLocke: authority rests on consent.\nThe Enlightenment: authority rests on reason.\nThe French Revolution: reason without wisdom produces terror.\nThe Industrial Revolution: economic power creates new forms of tyranny.\nLeo XIII: dignity is the floor below which no authority may push.\nWorld War I: the balance of power, when it breaks, destroys everything.\n\nThe paper's conclusion: the modern world did not begin once. It began every time someone asked '*by what right?*' and refused to accept '*because I said so*' as an answer.\n\nThe teacher writes nothing in the margin. Instead, at the end of class, the teacher says: '*Alex -- that paper was the best answer to the question I have ever received. And the best part is that you ended with a question, not an answer.*'\n\nThe modern world is still beginning. The question is still being asked. The balance is still being kept -- or not -- by people who remember what happens when it tips.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "war",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "best"
      ]
    }
  },
  "start_node": "start",
  "edges": [
    [
      "start",
      "act2_elizabeth"
    ],
    [
      "start",
      "act3_empire"
    ],
    [
      "start",
      "act4_war"
    ],
    [
      "start",
      "end_surface"
    ],
    [
      "act2_elizabeth",
      "act2_civil_war"
    ],
    [
      "act2_elizabeth",
      "act3_empire"
    ],
    [
      "act2_elizabeth",
      "act2_science"
    ],
    [
      "act2_civil_war",
      "act2_glorious"
    ],
    [
      "act2_civil_war",
      "act5_reason"
    ],
    [
      "act2_glorious",
      "act2_science"
    ],
    [
      "act2_glorious",
      "act5_reason"
    ],
    [
      "act2_glorious",
      "act7_alliances"
    ],
    [
      "act2_science",
      "act5_reason"
    ],
    [
      "act2_science",
      "act3_empire"
    ],
    [
      "act2_science",
      "act4_war"
    ],
    [
      "act3_empire",
      "act3_casas"
    ],
    [
      "act3_empire",
      "act3_quixote"
    ],
    [
      "act3_empire",
      "act4_war"
    ],
    [
      "act3_casas",
      "act3_quixote"
    ],
    [
      "act3_casas",
      "act6_expansion"
    ],
    [
      "act3_casas",
      "act5_reason"
    ],
    [
      "act3_quixote",
      "act4_war"
    ],
    [
      "act3_quixote",
      "act5_reason"
    ],
    [
      "act4_war",
      "act4_peace"
    ],
    [
      "act4_war",
      "act7_alliances"
    ],
    [
      "act4_peace",
      "act5_reason"
    ],
    [
      "act4_peace",
      "act7_alliances"
    ],
    [
      "act4_peace",
      "act6_industrial"
    ],
    [
      "act5_reason",
      "act5_voltaire"
    ],
    [
      "act5_reason",
      "act5_revolution"
    ],
    [
      "act5_reason",
      "act6_industrial"
    ],
    [
      "act5_voltaire",
      "act5_revolution"
    ],
    [
      "act5_voltaire",
      "act6_expansion"
    ],
    [
      "act5_revolution",
      "act6_industrial"
    ],
    [
      "act5_revolution",
      "act7_alliances"
    ],
    [
      "act5_revolution",
      "end_consequences"
    ],
    [
      "act6_industrial",
      "act6_marx"
    ],
    [
      "act6_industrial",
      "act6_expansion"
    ],
    [
      "act6_industrial",
      "act7_trenches"
    ],
    [
      "act6_marx",
      "act6_expansion"
    ],
    [
      "act6_marx",
      "act7_alliances"
    ],
    [
      "act6_marx",
      "end_dignity"
    ],
    [
      "act6_expansion",
      "act7_alliances"
    ],
    [
      "act6_expansion",
      "end_witness"
    ],
    [
      "act7_alliances",
      "act7_trenches"
    ],
    [
      "act7_alliances",
      "act7_peace"
    ],
    [
      "act7_trenches",
      "act7_peace"
    ],
    [
      "act7_peace",
      "end_balance"
    ],
    [
      "act7_peace",
      "end_peace"
    ],
    [
      "act7_peace",
      "end_arc"
    ]
  ]
};
