// Auto-generated by story_graph.py — do not edit by hand
const STORY_DATA = {
  "nodes": {
    "start": {
      "title": "The Final Exam",
      "text": "Theo is seventeen, a high school junior, and terrified. His philosophy class exam is tomorrow: Plato's *Phaedo* -- Socrates' last day alive, his arguments for the immortality of the soul, and the Theory of Forms. He has read it three times and still doesn't understand why Socrates is so calm about dying.\n\nHis notes blur. The desk lamp flickers.\n\nWhen he opens his eyes, he is standing in a stone cell. The air smells of damp and olive oil. A man sits on a low bed, rubbing his ankle where a chain has just been removed. He is old, ugly, barefoot, and radiantly at peace.\n\nA dozen people fill the cell. Some are weeping. The man on the bed is not.\n\n'*Ah,*' he says, noticing Theo. '*Another visitor on my last day. Good. I have been wanting to explain why death is nothing to fear. But first -- why are you crying? You are, you know.*'",
      "choices": [
        {
          "text": "Ask who he is (though you already know)",
          "target": "act1_socrates"
        },
        {
          "text": "Ask why he isn't afraid of dying",
          "target": "act1_calm"
        },
        {
          "text": "Ask about the people in the room -- who are they?",
          "target": "act1_company"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "frame",
      "vocabulary": [
        {
          "term": "Phaedo",
          "definition": "Plato's dialogue recounting Socrates' final hours in prison. Named for the young disciple who narrates the story to Echecrates, a Pythagorean philosopher."
        },
        {
          "term": "Socrates",
          "definition": "Athenian philosopher (469-399 BC). Convicted of impiety and corrupting the youth. Chose to drink hemlock rather than flee, arguing that the examined life requires accepting the law's verdict."
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "entry",
        "frame_story"
      ]
    },
    "act1_socrates": {
      "title": "The Wisest Man in Athens",
      "text": "'*I am Socrates,*' he says, amused. '*Son of Sophroniscus the stonemason. Husband of Xanthippe. The Oracle at Delphi once said I was the wisest man in Athens. Do you know why?*'\n\nHe pauses. '*Because I know that I do not know. Every other man thinks he knows something. I alone understand the depth of my ignorance. That is Socratic ignorance -- and it is the beginning of all philosophy.*'\n\nHe rubs his freed ankle. '*The Athenians convicted me of impiety and corrupting the youth. My friend Crito offered to help me escape. I refused. The laws raised me, educated me, gave me everything. I made an implicit agreement to obey them -- a social contract. Breaking it now would make me a hypocrite. And I would rather die than be a hypocrite.*'",
      "choices": [
        {
          "text": "But WHY aren't you afraid? That's what I need to understand.",
          "target": "act1_calm"
        },
        {
          "text": "Tell me about the people here with you",
          "target": "act1_company"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "setting",
      "vocabulary": [
        {
          "term": "Socratic Ignorance",
          "definition": "'I know that I do not know.' Socrates' foundational insight: true wisdom begins with recognizing the limits of one's knowledge."
        },
        {
          "term": "Oracle at Delphi",
          "definition": "The most important oracle in ancient Greece. The priestess declared Socrates the wisest man in Athens, prompting his lifelong philosophical mission."
        },
        {
          "term": "Social Contract",
          "definition": "The implicit agreement between citizen and state: the citizen obeys the laws in exchange for the state's protection and benefits. Socrates invoked this in the Crito to explain why he would not escape."
        },
        {
          "term": "Elenchus",
          "definition": "The Socratic method of questioning: cross-examining a person's beliefs to expose contradictions and reveal hidden ignorance."
        },
        {
          "term": "Asebeia",
          "definition": "Impiety -- the formal charge brought against Socrates at his trial. He was accused of failing to honor the gods of Athens and of corrupting the youth with his philosophical questioning."
        }
      ],
      "figures": [
        "Socrates",
        "Crito"
      ],
      "tags": [
        "setting",
        "socrates"
      ]
    },
    "act1_calm": {
      "title": "Why the Philosopher Does Not Fear Death",
      "text": "Socrates smiles. '*You want to know why I am calm. Very well. What is death?*'\n\nHe answers his own question: '*Death is the separation of the soul from the body. The body sees, hears, hungers, lusts, ages, decays. The soul thinks. And what does the philosopher spend his whole life doing? Separating his soul from his body -- turning away from bodily pleasures toward truth. Philosophy is the practice of dying.*'\n\nHe uses the Greek phrase: *melete thanatou*.\n\n'*If I have spent seventy years practicing death, why should I fear the performance? The body has always been an obstacle. Every time I tried to think clearly, the body intruded -- hunger, pain, desire. Death frees the soul from all that. It is not a punishment. It is a liberation.*'\n\nTheo feels the argument land. But a voice in his head objects: this only works if the soul survives death. What if it doesn't?",
      "choices": [
        {
          "text": "Ask: but how do you KNOW the soul survives?",
          "target": "act2_arguments"
        },
        {
          "text": "Ask about true virtue -- what does purification look like?",
          "target": "act1_virtue"
        },
        {
          "text": "Challenge him: what if the soul dies with the body?",
          "target": "act1_challenge"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "setting",
      "vocabulary": [
        {
          "term": "Melete Thanatou",
          "definition": "'The practice of dying' -- Socrates' definition of philosophy itself. The philosopher rehearses death by separating the soul from bodily concerns throughout life."
        },
        {
          "term": "Body-Soul Dichotomy",
          "definition": "Plato's fundamental distinction: the body belongs to the visible, changing world of senses; the soul belongs to the invisible, unchanging world of truth and Forms."
        },
        {
          "term": "Dualism",
          "definition": "The metaphysical view that reality consists of two fundamentally different kinds of substance: body (material, mortal, changing) and soul (immaterial, immortal, unchanging). The Phaedo is the foundational text of Platonic dualism."
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "setting",
        "death"
      ]
    },
    "act1_company": {
      "title": "The Witnesses",
      "text": "Socrates introduces the room. '*This is Phaedo -- young, sharp, recently freed from slavery. He will tell this story one day to a Pythagorean named Echecrates. That is the frame narrative: a story within a story, memory preserving truth.*'\n\n'*These are Simmias and Cebes, from Thebes. They studied with the Pythagoreans, who believe in the soul's immortality. But they are honest doubters -- they will challenge my arguments fiercely. Good philosophy needs fierce challengers.*'\n\n'*And this --*' he gestures to a woman being led out, weeping -- '*is Xanthippe, my wife. I asked her to leave because her grief makes it hard for us to think. Some will call me cold for that. I call it focus. Philosophy requires a clear head, especially today.*'\n\nApollodorus, in the corner, is crying openly. Socrates shakes his head gently. '*This is why I sent the women away. Really, Apollodorus -- what are these tears?*'",
      "choices": [
        {
          "text": "Why is Socrates so calm? Ask about philosophy as practicing dying.",
          "target": "act1_calm"
        },
        {
          "text": "Jump to the arguments -- prove the soul survives",
          "target": "act2_arguments"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "setting",
      "vocabulary": [
        {
          "term": "Phaedo",
          "definition": "Young Athenian disciple of Socrates, freed from slavery. He narrates the entire dialogue to Echecrates, making it a twice-told tale: memory of memory."
        },
        {
          "term": "Frame Narrative",
          "definition": "A story within a story. Phaedo tells Echecrates what happened in the cell. This layered structure reminds the reader that we are always receiving truth through human memory."
        },
        {
          "term": "Simmias and Cebes",
          "definition": "Theban students who studied with the Pythagoreans. They are Socrates' chief interlocutors in the Phaedo -- sympathetic but demanding genuine proof."
        },
        {
          "term": "Pythagoreans",
          "definition": "Followers of Pythagoras who believed in the soul's immortality, reincarnation, and the mathematical structure of reality."
        }
      ],
      "figures": [
        "Phaedo",
        "Simmias",
        "Cebes",
        "Xanthippe"
      ],
      "tags": [
        "setting",
        "characters"
      ]
    },
    "act1_virtue": {
      "title": "True Virtue",
      "text": "'*Most people are brave because they fear something worse than battle,*' Socrates says. '*They are temperate because they fear the consequences of excess. They trade pleasures for pleasures, fears for fears. That is not virtue. It is bookkeeping.*'\n\nHe leans forward. '*True virtue is katharsis -- purification. The soul freed from the body's influence. The truly brave person is brave not because he fears punishment but because his soul is clear enough to see what is right. The truly temperate person does not struggle against desire -- he has so thoroughly turned toward truth that desire has lost its grip.*'\n\n'*This is what philosophy does: it purifies. Every hour spent thinking clearly is an hour the soul practices being free of the body. And death is the final purification -- the moment the soul is entirely free.*'",
      "choices": [
        {
          "text": "But this requires the soul to survive! Prove it.",
          "target": "act2_arguments"
        },
        {
          "text": "This 'bookkeeping' critique is devastating. Sit with it.",
          "target": "end_bookkeeping"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "setting",
      "vocabulary": [
        {
          "term": "Katharsis",
          "definition": "Purification. In the Phaedo, the soul's gradual liberation from bodily influence through philosophical practice. True virtue is a form of katharsis."
        },
        {
          "term": "Arete",
          "definition": "Virtue or excellence -- the fullest expression of a thing's nature or function. For Socrates, human arete is the excellence of the soul: living and acting in accordance with wisdom and justice."
        },
        {
          "term": "Sophrosyne",
          "definition": "Self-control, temperance, or moderation -- one of the four cardinal virtues. In the Phaedo, Socrates argues true sophrosyne is not the struggle against desire but the soul's liberation from desire altogether."
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "setting",
        "virtue"
      ]
    },
    "act1_challenge": {
      "title": "The Honest Doubt",
      "text": "Theo speaks before he can stop himself: '*But what if the soul doesn't survive? What if when the body dies, the soul disperses like smoke? Then your whole argument collapses. Philosophy isn't practicing dying -- it's just... ignoring living.*'\n\nThe room goes quiet. Simmias and Cebes exchange a look. They have the same worry.\n\nSocrates, far from being offended, is delighted.\n\n'*Excellent!*' he says. '*That is exactly the right question. You are practicing the elenchus without knowing it -- cross-examining my claim to find the contradiction. Very well. I will give you not one argument but four. Attack each one. If they all fail, you will have earned your doubt. But if even one holds --*'\n\nHe raises an eyebrow. '*Then we have something worth dying for.*'",
      "choices": [
        {
          "text": "Give me the arguments. All of them.",
          "target": "act2_arguments"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "setting",
      "vocabulary": [
        {
          "term": "Dialectic",
          "definition": "Socrates' primary philosophical method: reaching truth through structured dialogue, question and answer, examining and refining positions until contradictions are resolved. Distinct from mere debate, dialectic aims at genuine knowledge rather than victory."
        }
      ],
      "figures": [
        "Socrates",
        "Simmias",
        "Cebes"
      ],
      "tags": [
        "setting",
        "challenge"
      ]
    },
    "act2_arguments": {
      "title": "Four Arguments for Immortality",
      "text": "Socrates holds up four fingers.\n\n'*First: the Argument from Opposites. Everything comes from its opposite -- hot from cold, waking from sleeping, large from small. If the living come from the dead, the dead must come from the living. Death and life are a cycle. The soul must persist between them.*'\n\n'*Second: the Argument from Recollection. We know things we could not have learned from experience -- perfect Equality, perfect Beauty, perfect Justice. We must have known the Forms before birth. If the soul existed before the body, it can exist after.*'\n\n'*Third: the Argument from Affinity. The soul is akin to the invisible, unchanging, divine realm. The body is akin to the visible, changing, mortal realm. Like dissolves with like. The body dissolves. The soul does not.*'\n\n'*Fourth -- the strongest -- comes later. But first: which argument calls to you?*'",
      "choices": [
        {
          "text": "The Argument from Opposites -- explain the cycle",
          "target": "act2_opposites"
        },
        {
          "text": "The Argument from Recollection -- how do we know the Forms?",
          "target": "act2_recollection"
        },
        {
          "text": "The Argument from Affinity -- the soul's kinship with the divine",
          "target": "act2_affinity"
        },
        {
          "text": "Skip to the objections -- I want to see these arguments challenged",
          "target": "act3_objections"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "arguments",
      "vocabulary": [
        {
          "term": "Argument from Opposites",
          "definition": "Socrates' first argument: everything comes from its opposite (hot from cold, life from death). If the living come from the dead, souls must persist between cycles."
        },
        {
          "term": "Argument from Recollection",
          "definition": "Socrates' second argument: we know things (perfect Equality, Beauty) that we could not learn from sensory experience. We must have known the Forms before birth."
        },
        {
          "term": "Argument from Affinity",
          "definition": "Socrates' third argument: the soul is akin to the invisible, unchanging, divine realm, and therefore shares its indestructibility."
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "arguments",
        "overview"
      ]
    },
    "act2_opposites": {
      "title": "The Cycle of Opposites",
      "text": "'*Watch,*' Socrates says. '*Hot comes from cold. Cold from hot. Sleeping from waking. Waking from sleeping. The larger comes from the smaller. There is always a process of generation between opposites.*'\n\nHe draws in the dust: life → death → life → death...\n\n'*If the living come from the dead, there must be a process: dying. And if the dead come from the living, there must be a reverse process: coming back to life. The soul goes somewhere when the body dies, and returns when a new body is born.*'\n\nCebes nods slowly. '*If the process only went one direction -- living to dead, but never dead to living -- eventually everything would be dead. The universe would run down. But it hasn't. Therefore the cycle must be real.*'\n\nTheo sees a weakness: does this really prove the *same* soul returns, or just that *some* life follows death?",
      "choices": [
        {
          "text": "Move to Recollection -- that might answer the identity question",
          "target": "act2_recollection"
        },
        {
          "text": "Jump to the objections -- Simmias and Cebes will find the weakness",
          "target": "act3_objections"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "arguments",
      "vocabulary": [],
      "figures": [
        "Socrates",
        "Cebes"
      ],
      "tags": [
        "arguments",
        "opposites"
      ]
    },
    "act2_recollection": {
      "title": "Learning Is Remembering",
      "text": "Socrates picks up two sticks from the floor.\n\n'*Are these equal?*' he asks.\n\nTheo looks. '*More or less.*'\n\n'*More or less. Exactly. They are approximately equal. But you said 'more or less' because you compared them to something: perfect Equality. Auto to ison -- the Equal itself. Where did you get that standard?*'\n\nHe presses: '*Not from experience. You have never seen two perfectly equal things in the physical world. Every pair of sticks, every pair of stones falls short of perfect Equality. Yet you recognize the shortfall. How can you recognize that something falls short of a standard you have never encountered?*'\n\n'*Answer: you knew the standard before you were born. Your soul encountered the Forms -- perfect Equality, perfect Beauty, perfect Justice -- before it entered the body. Learning is not discovering something new. It is anamnesis -- recollection. You are remembering what you already knew.*'",
      "choices": [
        {
          "text": "This is connected to the Theory of Forms -- explain the Forms",
          "target": "act4_forms"
        },
        {
          "text": "Move to the Argument from Affinity",
          "target": "act2_affinity"
        },
        {
          "text": "I see weaknesses. Show me the objections.",
          "target": "act3_objections"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "arguments",
      "vocabulary": [
        {
          "term": "Anamnesis",
          "definition": "Recollection. Plato's theory that learning is not acquiring new knowledge but remembering what the soul knew before birth, when it dwelt among the Forms."
        },
        {
          "term": "Auto to Ison",
          "definition": "'The Equal itself' -- the perfect Form of Equality. We recognize imperfect equality in the world by comparing it to this perfect standard we knew before birth."
        },
        {
          "term": "Theory of Forms",
          "definition": "Plato's central metaphysical claim: beyond the visible world of change exists an invisible world of perfect, eternal, unchanging realities (Forms) that are the true objects of knowledge."
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "arguments",
        "recollection"
      ]
    },
    "act2_affinity": {
      "title": "The Soul's Kinship",
      "text": "Socrates draws a line in the dust, dividing the world in two.\n\n'*On one side: the visible. Changing, mortal, many, dissoluble. The body belongs here. On the other side: the invisible. Unchanging, immortal, one, indissoluble. The Forms belong here.*'\n\nHe taps the invisible side. '*Where does the soul belong? Can you see a soul? No. Is it changing and many? No -- when it thinks clearly, it grasps unchanging truth. The soul is akin to the invisible, divine, immortal realm. The body is akin to the visible, mortal realm.*'\n\n'*When the body dies, it dissolves -- like dissolving with like. But the soul is not like the body. It is like the Forms. And the Forms do not dissolve.*'\n\nHe adds a haunting image: '*The soul of the philosopher, purified by a lifetime of thinking, departs to the blessed realm of the Forms. But the soul weighed down by bodily attachment -- that soul lingers near the grave, haunting sepulchres, unable to let go of the flesh.*'",
      "choices": [
        {
          "text": "This is beautiful but vulnerable. Show me the objections.",
          "target": "act3_objections"
        },
        {
          "text": "Tell me about the Theory of Forms -- the foundation of all this",
          "target": "act4_forms"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "arguments",
      "vocabulary": [
        {
          "term": "Affinity (Suggeneia)",
          "definition": "Kinship or natural likeness. The soul has affinity with the invisible, unchanging, divine realm of Forms; the body has affinity with the visible, changing, mortal realm."
        },
        {
          "term": "Indissoluble",
          "definition": "Cannot be dissolved or broken apart. Socrates argues the soul, being akin to the unchanging Forms, shares their indestructibility."
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "arguments",
        "affinity"
      ]
    },
    "act3_objections": {
      "title": "The Counterattack",
      "text": "Silence falls. Then Simmias speaks.\n\n'*Socrates, I have an objection. Consider a lyre -- a stringed instrument. When it is tuned, it produces harmony. The harmony is invisible, beautiful, divine. But if you break the lyre, the harmony vanishes. It does not float away to some blessed realm. It simply... stops.*'\n\nHe looks at Socrates steadily. '*What if the soul is like the harmony? What if it is produced by the body the way music is produced by an instrument? When the body dies, the soul does not escape. It ceases.*'\n\nThe room goes cold. Echecrates, hearing this story later, will say this was the moment he nearly lost faith in the argument entirely.\n\nCebes adds his own objection, equally devastating.",
      "choices": [
        {
          "text": "Hear Cebes' objection too -- the Weaver argument",
          "target": "act3_weaver"
        },
        {
          "text": "Can Socrates answer the Harmony objection?",
          "target": "act3_harmony_reply"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "objections",
      "vocabulary": [
        {
          "term": "Harmony Objection (Simmias)",
          "definition": "The soul might be like the harmony of a lyre: produced by the body's arrangement, not existing independently. If the instrument breaks, the music stops. If the body dies, the soul ceases."
        }
      ],
      "figures": [
        "Simmias",
        "Socrates"
      ],
      "tags": [
        "objections",
        "harmony"
      ]
    },
    "act3_weaver": {
      "title": "The Weaver's Cloak",
      "text": "Cebes speaks: '*Even if the soul is not like a harmony -- even if it is an independent thing -- consider this. A weaver makes many cloaks in his lifetime. Each cloak wears out and he weaves another. But eventually the weaver himself dies, leaving one last cloak that outlasts him.*'\n\nHe turns to Socrates. '*What if the soul is like the weaver? It may inhabit many bodies -- reincarnation, as you argue. It may outlast body after body. But that does not prove it is immortal. Perhaps the soul, like the weaver, eventually wears out. Perhaps this body -- yours, today -- is the last cloak, and when you drink the hemlock, the soul dies too.*'\n\nThis is worse than Simmias's objection. Simmias denied the soul's independence. Cebes grants independence but denies immortality. Even a long-lived thing can die.",
      "choices": [
        {
          "text": "These objections are devastating. How does Socrates respond?",
          "target": "act3_harmony_reply"
        },
        {
          "text": "Socrates might be wrong. Maybe the soul DOES die.",
          "target": "act3_misology"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "objections",
      "vocabulary": [
        {
          "term": "Weaver Objection (Cebes)",
          "definition": "Even if the soul outlasts individual bodies (like a weaver outlasts individual cloaks), it might still eventually wear out and die. Longevity is not immortality."
        },
        {
          "term": "Hemlock",
          "definition": "The poison administered to condemned prisoners in Athens. A slow-acting toxin that numbs from the extremities inward. Socrates drank it calmly at sunset."
        }
      ],
      "figures": [
        "Cebes",
        "Socrates"
      ],
      "tags": [
        "objections",
        "weaver"
      ]
    },
    "act3_misology": {
      "title": "The Danger of Giving Up",
      "text": "Something shifts in the room. Doubt spreads like cold water. Even the devoted followers look shaken.\n\nSocrates reads the mood. '*Be careful,*' he says, suddenly serious. '*There is a disease worse than any wrong conclusion. It is called misology -- the hatred of argument itself. It is like misanthropy, the hatred of people.*'\n\n'*The misanthrope trusts everyone, is betrayed, and concludes that all people are worthless. The misologist trusts an argument, finds it flawed, and concludes that all arguments are worthless. Both are cowards who blame the world instead of learning better judgment.*'\n\n'*If my first three arguments have weaknesses, the answer is not to abandon reason. The answer is to reason better. Never hate the logos -- the argument, the word, the rational discourse that makes us human. A flawed argument is an invitation to find a stronger one.*'",
      "choices": [
        {
          "text": "Then find a stronger argument. Show me.",
          "target": "act3_harmony_reply"
        },
        {
          "text": "This warning is profound on its own. Misology is everywhere.",
          "target": "end_misology"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "objections",
      "vocabulary": [
        {
          "term": "Misology",
          "definition": "Hatred of argument or reason. Socrates warns that encountering flawed arguments should not lead to rejecting reason itself -- that is the real intellectual death."
        },
        {
          "term": "Logos",
          "definition": "Word, argument, reason, rational discourse. In Greek philosophy, logos is the faculty that makes humans human -- the capacity for reasoned thought and speech."
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "objections",
        "misology"
      ]
    },
    "act3_harmony_reply": {
      "title": "Socrates Strikes Back",
      "text": "Socrates answers Simmias first.\n\n'*If the soul were a harmony, it could not oppose the body. A harmony cannot lead the instrument -- it follows. But the soul does lead the body. It resists hunger, overrules fear, disciplines desire. The soul commands; the body obeys. That is the opposite of harmony.*'\n\nHe adds: '*And if the soul were a harmony, all souls would be equally harmonious. But they are not. Some souls are virtuous, others vicious. A harmony cannot be more or less a harmony. Therefore the soul is not a harmony.*'\n\nSimmias concedes. The harmony objection falls.\n\n'*But Cebes' objection is harder,*' Socrates admits. '*To answer the weaver, I need a different kind of argument entirely. I need to show you what a cause really is. And that requires --*'\n\nHis eyes light up. '*A story about my own intellectual journey. How I turned from natural science to philosophy. The second sailing.*'",
      "choices": [
        {
          "text": "Tell me about the second sailing",
          "target": "act4_second_sailing"
        },
        {
          "text": "Go directly to the final argument for immortality",
          "target": "act4_final"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "objections",
      "vocabulary": [
        {
          "term": "Tripartite Soul",
          "definition": "Plato's theory (from the Republic) that the soul has three parts: Reason (logistikon), Spirit (thumos), and Appetite (epithumia). These can conflict -- proof the soul is not a mere harmony."
        }
      ],
      "figures": [
        "Socrates",
        "Simmias"
      ],
      "tags": [
        "objections",
        "reply"
      ]
    },
    "act4_second_sailing": {
      "title": "The Second Sailing",
      "text": "Socrates' eyes grow distant.\n\n'*When I was young, I was passionate about natural science. I wanted to know the cause of everything: why does the earth stay in place? Why does fire burn? I read Anaxagoras, who said Mind -- Nous -- arranged all things. I was thrilled. Finally, a thinker who would explain why things are arranged as they are.*'\n\n'*But Anaxagoras disappointed me. He invoked Mind and then explained everything by material causes: earth, air, fire, water. He told me Socrates sits in prison because his bones and muscles are arranged in a sitting position. But that is not the cause! The cause is that Athens condemned me and I judged it right to accept the sentence.*'\n\n'*So I made my deuteros plous -- my second sailing. When the wind fails, the sailor takes up oars. When direct observation of nature failed me, I turned to logoi -- to arguments, words, reasons. I sought truth not in the visible world but in the world of Forms.*'",
      "choices": [
        {
          "text": "Explain the Forms -- what are they?",
          "target": "act4_forms"
        },
        {
          "text": "Go to the final argument for immortality",
          "target": "act4_final"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "forms",
      "vocabulary": [
        {
          "term": "Deuteros Plous",
          "definition": "'Second sailing.' When the wind of direct observation fails, the philosopher takes up the oars of reason. Socrates' turn from natural science to abstract philosophical inquiry."
        },
        {
          "term": "Cause vs. Necessary Condition",
          "definition": "Bones and muscles are necessary conditions for sitting but not the cause. The cause is a judgment. Confusing mechanism with purpose is the error Socrates corrects."
        },
        {
          "term": "Anaxagoras",
          "definition": "Pre-Socratic philosopher who proposed Mind (Nous) as the ordering principle of the universe, but disappointed Socrates by relying on material rather than purposive explanations."
        }
      ],
      "figures": [
        "Socrates",
        "Anaxagoras"
      ],
      "tags": [
        "forms",
        "second_sailing"
      ]
    },
    "act4_forms": {
      "title": "The Invisible World",
      "text": "'*Here is what I believe,*' Socrates says. '*Beyond this visible world of change and decay, there exists an invisible world of perfect, eternal, unchanging realities. I call them the Forms.*'\n\n'*Why is this stick beautiful? Not because of the wood. Because it participates in the Form of Beauty -- Beauty itself, which is perfect, unchanging, and invisible. Why is this pair of sticks equal? Because they participate in the Form of Equality. Why is a just act just? Because it participates in the Form of Justice.*'\n\n'*The visible world is a shadow of the invisible world. Think of the Allegory of the Cave: prisoners chained underground, watching shadows on a wall, believing the shadows are reality. The philosopher breaks free, climbs upward, and sees the sun -- the Form of the Good, the source of all truth and being.*'\n\n'*And the philosopher's duty? To go back down and tell the prisoners what he has seen. Even if they mock him. Even if they kill him.*'",
      "choices": [
        {
          "text": "Now use the Forms to prove immortality -- the final argument",
          "target": "act4_final"
        },
        {
          "text": "The Cave is extraordinary. But Aristotle will object...",
          "target": "act4_aristotle"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "forms",
      "vocabulary": [
        {
          "term": "Participation",
          "definition": "Things in the visible world are beautiful, just, or equal because they 'participate in' or 'partake of' the corresponding Form. The Form is the true reality; the particular is a copy."
        },
        {
          "term": "Allegory of the Cave",
          "definition": "Plato's famous metaphor (Republic, Book VII): prisoners in a cave mistake shadows for reality. The philosopher escapes, sees the sun (Form of the Good), and returns to enlighten others."
        },
        {
          "term": "Form of the Good",
          "definition": "The supreme Form, analogous to the sun: the source of all truth, being, and intelligibility. The philosopher's ultimate object of knowledge."
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "forms",
        "cave"
      ]
    },
    "act4_aristotle": {
      "title": "The Third Man",
      "text": "Theo cannot help himself. '*But Aristotle will argue against this. The Third Man Argument: if a particular man is a man because he participates in the Form of Man, then the Form of Man and the particular man together need a third Man to explain their similarity. And that third needs a fourth. It's an infinite regress.*'\n\nSocrates raises an eyebrow. '*You know Aristotle?*'\n\n'*He was your friend's student. Plato's student.*'\n\n'*Ah. And does this Aristotle solve the problem?*'\n\n'*He says forms are not separate from things. The form of a horse is IN the horse, not in some other world.*'\n\nSocrates considers this. '*Interesting. But if the form is in the horse, and the horse dies, does the form die too? My Forms are eternal because they are separate. His forms are vulnerable because they are embedded. We are back to the same question: does the invisible survive the death of the visible?*'",
      "choices": [
        {
          "text": "Give me the final argument. Answer Cebes' weaver.",
          "target": "act4_final"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "forms",
      "vocabulary": [
        {
          "term": "Third Man Argument",
          "definition": "Aristotle's objection to Plato: if a man and the Form of Man are similar, we need a 'third man' to explain the similarity, leading to infinite regress."
        },
        {
          "term": "Method of Hypothesis",
          "definition": "Socrates' philosophical approach: propose a hypothesis (the Forms), test it for consistency, and if it holds, use it as a foundation for further inquiry."
        },
        {
          "term": "Eudaimonia",
          "definition": "Happiness, flourishing, or well-being -- the highest human good. While Socrates ties it to purity of soul, Aristotle will argue eudaimonia is achieved through virtuous activity in ordinary life, not withdrawal from it."
        },
        {
          "term": "Phronesis",
          "definition": "Practical wisdom -- Aristotle's term for the capacity to discern the right course of action in particular situations. Where Socrates prizes abstract knowledge of the Forms, Aristotle emphasizes this grounded, situational judgment."
        },
        {
          "term": "Golden Mean",
          "definition": "Aristotle's ethical principle: virtue lies between two extremes of excess and deficiency (e.g., courage is the mean between cowardice and recklessness). This contrasts with Plato's view that virtue is absolute purity of soul."
        }
      ],
      "figures": [
        "Socrates",
        "Aristotle"
      ],
      "tags": [
        "forms",
        "aristotle"
      ]
    },
    "act4_final": {
      "title": "The Final Argument",
      "text": "Socrates speaks carefully. This is the argument that matters most.\n\n'*Fire always brings heat. It can never bring cold. Snow always brings cold. It can never bring heat. Three always brings oddness. It can never bring evenness. This is the principle: Forms exclude their opposites.*'\n\n'*Now: what does the soul bring to the body?*'\n\nCebes answers: '*Life.*'\n\n'*And what is the opposite of life?*'\n\n'*Death.*'\n\n'*Then the soul can never admit death. It is athanatos -- deathless. Just as fire cannot become cold and remain fire, the soul cannot become dead and remain a soul. When death approaches, the soul does not die. It withdraws -- departs -- to another realm. It is also anolethros -- indestructible.*'\n\nThe room is silent. The argument is elegant, almost mathematical. But Theo senses a gap: does 'deathless' necessarily mean 'indestructible'?",
      "choices": [
        {
          "text": "It's time. Watch Socrates drink the hemlock.",
          "target": "act5_death"
        },
        {
          "text": "The argument is beautiful but you're not sure it's conclusive",
          "target": "end_doubt"
        },
        {
          "text": "The argument holds. The soul is immortal.",
          "target": "end_convinced"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "forms",
      "vocabulary": [
        {
          "term": "Athanatos",
          "definition": "'Deathless, immortal.' The soul, by its nature, brings life and cannot admit its opposite (death). Therefore it is deathless -- it cannot die."
        },
        {
          "term": "Anolethros",
          "definition": "'Indestructible, imperishable.' Socrates' strongest claim: the soul not only cannot die but cannot be destroyed in any way."
        },
        {
          "term": "Forms Exclude Opposites",
          "definition": "The principle underlying the final argument: fire cannot be cold, snow cannot be hot, three cannot be even. Similarly, the soul (bringer of life) cannot admit death."
        }
      ],
      "figures": [
        "Socrates",
        "Cebes"
      ],
      "tags": [
        "forms",
        "final_argument"
      ]
    },
    "act5_death": {
      "title": "The Hemlock Cup",
      "text": "The sun touches the western hills. The jailer enters, weeping. He has come to know Socrates and calls him '*the noblest, gentlest, and best man who has ever come to this place.*'\n\nHe brings the cup of hemlock.\n\nSocrates takes it calmly. His friends beg him to wait -- the sun has not quite set. He smiles. '*Others delay because they think they gain something. I would only make myself ridiculous, clinging to life when nothing remains.*'\n\nHe drinks. He walks around the room until his legs grow heavy, then lies down. The numbness rises from his feet. His friends are weeping now, all of them, and Socrates rebukes them gently: '*I sent the women away for exactly this reason. Be quiet. Let me die in peace.*'\n\nHis last words: '*Crito, we owe a cock to Asclepius. Pay the debt and do not forget.*'\n\nThen he is still.",
      "choices": [
        {
          "text": "What do his last words mean?",
          "target": "act5_last_words"
        },
        {
          "text": "Sit with the silence. Nothing more needs to be said.",
          "target": "end_silence"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "death",
      "vocabulary": [
        {
          "term": "Asclepius",
          "definition": "Greek god of healing. A rooster was sacrificed to Asclepius after recovery from illness. Socrates' last words suggest death is a cure -- the soul's recovery from the 'illness' of embodiment."
        }
      ],
      "figures": [
        "Socrates",
        "Crito"
      ],
      "tags": [
        "death",
        "hemlock"
      ]
    },
    "act5_last_words": {
      "title": "The Debt to Asclepius",
      "text": "Phaedo leans toward Theo. '*Asclepius is the god of healing. You sacrifice a rooster to him when you recover from an illness. Socrates is saying: death is a healing. The soul's release from the body is a recovery -- a cure for the disease of embodiment.*'\n\nHe pauses. '*Or perhaps he means something simpler. He made a vow and wants it honored. Even in death, he pays his debts. He keeps his word. The social contract holds to the last breath.*'\n\nPhaedo's voice is steady. '*Such was the end of our companion, Echecrates -- a man of whom we may say that of all those we knew in our time, he was the wisest, the most just, and the best.*'\n\nThe cell is empty now. The lamp gutters. And Theo understands something he could not learn from a textbook: Socrates did not prove immortality with arguments. He proved it with his death.",
      "choices": [
        {
          "text": "He proved it with his death. That is the answer.",
          "target": "end_proof"
        },
        {
          "text": "Sit with the silence.",
          "target": "end_silence"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "death",
      "vocabulary": [],
      "figures": [
        "Phaedo",
        "Socrates"
      ],
      "tags": [
        "death",
        "last_words"
      ]
    },
    "end_proof": {
      "title": "The Proof Was the Death",
      "text": "Theo wakes at his desk. The textbook is open to the final pages of the Phaedo.\n\nHe understands now. The four arguments are brilliant but imperfect. Simmias and Cebes found real weaknesses. Aristotle will find more. Two thousand years of philosophers will debate whether any of them work.\n\nBut Socrates did not die because he had a proof. He died because he lived the proof. A man who truly believed the soul was mortal would not have drunk the hemlock with such peace. His calm was not performance. It was the natural expression of a soul that had practiced dying for seventy years.\n\nThe argument is the life. The proof is the death.\n\nTheo picks up his pen and writes his exam answer. He is not afraid anymore.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "death_as_proof"
      ]
    },
    "end_silence": {
      "title": "Such Was the End",
      "text": "Theo wakes at his desk. The room is dark and quiet.\n\nHe does not reach for his notes. He sits in the silence that follows a death -- the particular silence that Phaedo described, that Echecrates heard, that has echoed through twenty-four centuries of readers.\n\n*Such was the end of our companion -- a man of whom we may say that of all those we knew in our time, he was the wisest, the most just, and the best.*\n\nHe will pass the exam. But that is not what matters. What matters is that he sat in a prison cell with a man who was not afraid to die, and he learned something about what it means to live.\n\nThe silence holds. It is enough.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "silence"
      ]
    },
    "end_convinced": {
      "title": "The Soul Is Immortal",
      "text": "Theo wakes at his desk. He believes it. Not with the tentative belief of someone who has read a convincing argument but with the settled conviction of someone who has witnessed a man die without fear.\n\nThe Forms are real. The soul is athanatos. Death is not an ending but a departure -- the soul shedding the body the way a prisoner sheds chains.\n\nHe knows this will not hold up to every philosophical objection. Hume will challenge it. Kant will reframe it. The materialists will deny it. But something in Socrates' calm has planted a seed that no argument can uproot.\n\nHe opens his exam booklet and writes: *The Phaedo is not about proving immortality. It is about showing what a person who believes in immortality looks like when tested.*",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "conviction"
      ]
    },
    "end_doubt": {
      "title": "The Honest Doubter",
      "text": "Theo wakes at his desk, unconvinced but changed.\n\nThe arguments are beautiful. Each one captures something real about consciousness, about knowledge, about the mind's apparent independence from the body. But none of them is conclusive. The harmony objection shook him. The weaver objection shook him more.\n\nAnd yet -- Socrates would not be disappointed. He would say: '*Good. You have practiced the elenchus. You have examined the argument and found it wanting. That is philosophy. That is the examined life.*'\n\nTheo is not sure the soul is immortal. But he is sure of this: the willingness to ask the question -- to sit with the uncertainty, to keep reasoning even when the answers are elusive -- that is what makes a life worth living.\n\nThe unexamined life is not worth living. The examined one might be.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "doubt"
      ]
    },
    "end_misology": {
      "title": "Never Hate the Argument",
      "text": "Theo wakes at his desk with one word ringing: misology.\n\nHe has heard it everywhere without knowing its name. The student who says '*philosophy is pointless.*' The voter who says '*all politicians lie.*' The friend who says '*nothing matters anyway.*' They have been burned by a bad argument, a broken promise, a failed hope -- and they conclude that all arguments, all promises, all hopes are worthless.\n\nSocrates said: that is the real death. Not the hemlock. The hemlock only kills the body. Misology kills the soul.\n\nTheo may not know whether the soul is immortal. But he knows this: he will never stop asking. He will never hate the logos. He will never let a failed argument convince him that argument itself is useless.\n\nThat is not a proof of immortality. It is something better: a reason to live.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "misology"
      ]
    },
    "end_bookkeeping": {
      "title": "Beyond the Ledger",
      "text": "Theo wakes with Socrates' critique lodged in his mind like a splinter.\n\n*Most people are brave because they fear something worse. They trade pleasures for pleasures, fears for fears. That is not virtue. It is bookkeeping.*\n\nHe looks at his own life: the grades pursued for approval, the kindness offered for reciprocity, the rules followed for reward. Bookkeeping. All of it.\n\nTrue virtue, Socrates said, is katharsis -- a soul so clear it sees the right thing and does it without calculation. Not because it fears punishment. Not because it expects reward. Because the purified soul cannot do otherwise.\n\nTheo does not know if his soul is immortal. But he knows it is keeping a ledger, and he wants to stop.",
      "choices": [],
      "is_ending": true,
      "ending_type": "neutral",
      "era": "frame",
      "vocabulary": [],
      "figures": [],
      "tags": [
        "ending",
        "virtue"
      ]
    }
  },
  "start_node": "start",
  "edges": [
    [
      "start",
      "act1_socrates"
    ],
    [
      "start",
      "act1_calm"
    ],
    [
      "start",
      "act1_company"
    ],
    [
      "act1_socrates",
      "act1_calm"
    ],
    [
      "act1_socrates",
      "act1_company"
    ],
    [
      "act1_calm",
      "act2_arguments"
    ],
    [
      "act1_calm",
      "act1_virtue"
    ],
    [
      "act1_calm",
      "act1_challenge"
    ],
    [
      "act1_company",
      "act1_calm"
    ],
    [
      "act1_company",
      "act2_arguments"
    ],
    [
      "act1_virtue",
      "act2_arguments"
    ],
    [
      "act1_virtue",
      "end_bookkeeping"
    ],
    [
      "act1_challenge",
      "act2_arguments"
    ],
    [
      "act2_arguments",
      "act2_opposites"
    ],
    [
      "act2_arguments",
      "act2_recollection"
    ],
    [
      "act2_arguments",
      "act2_affinity"
    ],
    [
      "act2_arguments",
      "act3_objections"
    ],
    [
      "act2_opposites",
      "act2_recollection"
    ],
    [
      "act2_opposites",
      "act3_objections"
    ],
    [
      "act2_recollection",
      "act4_forms"
    ],
    [
      "act2_recollection",
      "act2_affinity"
    ],
    [
      "act2_recollection",
      "act3_objections"
    ],
    [
      "act2_affinity",
      "act3_objections"
    ],
    [
      "act2_affinity",
      "act4_forms"
    ],
    [
      "act3_objections",
      "act3_weaver"
    ],
    [
      "act3_objections",
      "act3_harmony_reply"
    ],
    [
      "act3_weaver",
      "act3_harmony_reply"
    ],
    [
      "act3_weaver",
      "act3_misology"
    ],
    [
      "act3_misology",
      "act3_harmony_reply"
    ],
    [
      "act3_misology",
      "end_misology"
    ],
    [
      "act3_harmony_reply",
      "act4_second_sailing"
    ],
    [
      "act3_harmony_reply",
      "act4_final"
    ],
    [
      "act4_second_sailing",
      "act4_forms"
    ],
    [
      "act4_second_sailing",
      "act4_final"
    ],
    [
      "act4_forms",
      "act4_final"
    ],
    [
      "act4_forms",
      "act4_aristotle"
    ],
    [
      "act4_aristotle",
      "act4_final"
    ],
    [
      "act4_final",
      "act5_death"
    ],
    [
      "act4_final",
      "end_doubt"
    ],
    [
      "act4_final",
      "end_convinced"
    ],
    [
      "act5_death",
      "act5_last_words"
    ],
    [
      "act5_death",
      "end_silence"
    ],
    [
      "act5_last_words",
      "end_proof"
    ],
    [
      "act5_last_words",
      "end_silence"
    ]
  ]
};
