// Auto-generated by story_graph.py — do not edit by hand
const STORY_DATA = {
  "nodes": {
    "start": {
      "title": "The Stoa Steps",
      "text": "Theodore Ernest O'Hare — Theo to everyone who knows him — is supposed to be reading Plato for philosophy class. Instead, he's fighting sleep in the school library.\n\nWhen he opens his eyes, the carpet is gone. He's standing on sun-warmed marble steps. The air smells of olive oil and dust. Men in tunics stride past, arguing in Greek — except Theo can understand every word.\n\nA sign carved in stone reads: ROYAL **STOA** — COURT OF THE ARCHON BASILEUS.\n\nTwo men stand near the entrance. One is young, confident, dressed in a fine cloak — he's lecturing a small crowd about the nature of the gods. The other is older, barefoot, with a face like a satyr: snub nose, bulging eyes, thick lips. He looks amused.\n\nThe barefoot man catches Theo's eye. 'You look confused, young man. That's an excellent start.'",
      "choices": [
        {
          "text": "'Who are you? Where am I?'",
          "target": "act1_meet_socrates"
        },
        {
          "text": "Listen to the young man lecturing about the gods",
          "target": "act1_meet_euthyphro"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "frame",
      "vocabulary": [
        {
          "term": "stoa",
          "definition": "A covered walkway or colonnade in ancient Greek architecture; the Royal Stoa housed Athens's religious court"
        }
      ],
      "figures": [
        "Socrates",
        "Euthyphro"
      ],
      "tags": [
        "entry",
        "frame_story"
      ]
    },
    "act1_meet_socrates": {
      "title": "The Wisest Man in Athens",
      "text": "'I am Socrates,' says the barefoot man, 'and you are at the court of the Archon Basileus, where cases of **impiety** are heard. I am here because a young man named Meletus has charged me with two crimes: corrupting the youth and not believing in the gods of Athens.'\n\nHe says this as calmly as if reporting the weather.\n\n'You don't seem worried,' Theo says.\n\n'Should I be? Either the charges are true and I deserve punishment, or they are false and I have nothing to fear from the truth.' He pauses. 'But I am curious about something. That young man over there — Euthyphro — claims to know exactly what **piety** is. He is prosecuting his own father for murder. Shall we go ask him to define it?'\n\nSocrates's eyes gleam. 'After all, if he knows what piety is, perhaps he can teach me before my trial begins.'",
      "choices": [
        {
          "text": "'Yes — let's hear his definition.'",
          "target": "act1_euthyphro_debate"
        },
        {
          "text": "'Wait — you're on trial for your life and you want to debate definitions?'",
          "target": "act1_why_definitions"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "euthyphro",
      "vocabulary": [
        {
          "term": "impiety",
          "definition": "Lack of reverence for the gods; the formal charge against Socrates was asebeia (impiety)"
        },
        {
          "term": "piety",
          "definition": "Reverence and devotion to the gods; proper religious behavior — what Euthyphro claims to understand perfectly"
        }
      ],
      "figures": [
        "Socrates",
        "Euthyphro",
        "Meletus"
      ],
      "tags": [
        "socrates_intro",
        "charges"
      ]
    },
    "act1_meet_euthyphro": {
      "title": "The Expert on the Gods",
      "text": "The young man speaks with absolute confidence. 'The gods demand justice,' he declares. 'My father bound a laborer and left him in a ditch, where he died. This is murder, and **piety** requires that I prosecute him — even if he is my own father.'\n\nThe crowd murmurs. Prosecuting your own father? Some look impressed by his devotion. Others look appalled.\n\nThe barefoot man — Socrates, someone whispers — approaches. 'Euthyphro! What good fortune that I meet you here. You must be truly wise about the gods if you are so confident in this action. Tell me — what is piety? I need to know before my own trial.'\n\nEuthyphro beams. 'Certainly, Socrates. Piety is doing what I am doing now — prosecuting the wrongdoer.'",
      "choices": [
        {
          "text": "'That sounds like a reasonable answer.'",
          "target": "act1_euthyphro_trap"
        },
        {
          "text": "Watch how Socrates responds to this definition",
          "target": "act1_euthyphro_debate"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "euthyphro",
      "vocabulary": [
        {
          "term": "piety",
          "definition": "Reverence and devotion to the gods; proper religious behavior — the central question Socrates poses to Euthyphro"
        }
      ],
      "figures": [
        "Socrates",
        "Euthyphro"
      ],
      "tags": [
        "euthyphro_intro",
        "definition_attempt"
      ]
    },
    "act1_why_definitions": {
      "title": "Why Definitions Matter",
      "text": "Socrates laughs — a warm, genuine sound. 'You think definitions are trivial? Consider: Meletus says I am impious. Euthyphro says he knows what piety is. But if neither of them can define it clearly, how can one accuse and the other prosecute?'\n\nHe sits on the steps. 'This is the **Socratic method**, though I would never call it that myself. I ask questions. Not to trap people, but because I have discovered that most people — including me — use words every day without knowing what they mean.'\n\nHe looks at Theo seriously. 'Piety. Justice. Courage. Virtue. Everyone uses these words. Almost no one can define them. And a word you cannot define is a word that can be used against you.'\n\n'Now — shall we test Euthyphro's claim?'",
      "choices": [
        {
          "text": "'All right. Let's hear what he says.'",
          "target": "act1_euthyphro_debate"
        },
        {
          "text": "'But some things are obvious without definitions. Piety is just... being good.'",
          "target": "act1_euthyphro_trap"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "euthyphro",
      "vocabulary": [
        {
          "term": "Socratic method",
          "definition": "A form of inquiry using questions to test ideas, expose contradictions, and reach deeper understanding — Socrates's signature approach"
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "socratic_method",
        "definitions"
      ]
    },
    "act1_euthyphro_debate": {
      "title": "The Definition Crumbles",
      "text": "Socrates turns to Euthyphro. 'You say piety is prosecuting wrongdoers. But I asked for a definition — what is piety itself? You've given me an example, not a definition.'\n\nEuthyphro tries again: 'Piety is what is dear to the gods.'\n\n'But the gods disagree,' Socrates says gently. 'What is dear to Zeus may be hateful to Hera. So the same act would be both pious and impious. That cannot be right.'\n\nEuthyphro shifts: 'Then piety is what all the gods love.'\n\nSocrates leans forward. 'Ah — but here is the real question. Is something pious because the gods love it? Or do the gods love it because it is pious?'\n\nThis is the **Euthyphro dilemma** — and Theo watches Euthyphro's confidence crack like old pottery.",
      "choices": [
        {
          "text": "'What's the difference? Both sound the same.'",
          "target": "act1_dilemma_explained"
        },
        {
          "text": "'I think the gods love things because they're already good.'",
          "target": "act1_dilemma_explained"
        },
        {
          "text": "Stay quiet — this is getting interesting",
          "target": "act2_trial_begins"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "euthyphro",
      "vocabulary": [
        {
          "term": "Euthyphro dilemma",
          "definition": "Does God love the good because it is good, or is it good because God loves it? A foundational problem in philosophy of religion"
        }
      ],
      "figures": [
        "Socrates",
        "Euthyphro"
      ],
      "tags": [
        "euthyphro_dilemma",
        "definition_failure"
      ]
    },
    "act1_euthyphro_trap": {
      "title": "The Confident Answer",
      "text": "Theo nods along with Euthyphro. Piety is obvious — it's doing the right thing, honoring the gods, being good. Why make it complicated?\n\nSocrates watches Theo with something like disappointment. 'You remind me of Euthyphro before I began asking questions. He was certain too. Certainty is comfortable. But is it true?'\n\nHe turns back to Euthyphro and, with a few gentle questions, demolishes the young man's confidence entirely. Every definition Euthyphro offers has a flaw. Every certainty dissolves.\n\n'This state of confusion,' Socrates says, 'the Greeks call **aporia**. It is uncomfortable. But it is the beginning of wisdom — because only the person who knows they don't know will bother to search.'",
      "choices": [
        {
          "text": "'Maybe I was too quick to agree with Euthyphro.'",
          "target": "act1_dilemma_explained"
        },
        {
          "text": "'Confusion isn't wisdom. Euthyphro was at least trying to do the right thing.'",
          "target": "end_euthyphro_trap"
        },
        {
          "text": "Decide Socrates is just a troublemaker who tears things down",
          "target": "end_unexamined"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "euthyphro",
      "vocabulary": [
        {
          "term": "aporia",
          "definition": "A state of puzzlement or impasse reached through questioning — Socrates saw this confusion as the necessary first step to real understanding"
        }
      ],
      "figures": [
        "Socrates",
        "Euthyphro"
      ],
      "tags": [
        "aporia",
        "certainty_vs_questioning"
      ]
    },
    "act1_dilemma_explained": {
      "title": "The Fork in the Road",
      "text": "Socrates holds up two fingers. 'Path one: the gods love what is pious because it is already pious. That means goodness exists independently of the gods — they recognize it but don't create it. The gods are not the source of morality.\n\n'Path two: a thing becomes pious because the gods love it. That means morality is arbitrary — the gods could declare anything good or evil, and we would have to obey.'\n\nHe watches Theo. 'Neither path is comfortable. The first undermines divine authority. The second makes justice meaningless. This is why **philosophy** is dangerous — not because it gives wrong answers, but because it reveals that the easy answers were never right.'\n\nA bell sounds from the courthouse. 'Ah,' Socrates says. 'My trial is about to begin. Will you come watch?'",
      "choices": [
        {
          "text": "'I wouldn't miss it.'",
          "target": "act2_trial_begins"
        },
        {
          "text": "'This dilemma applies to modern religion too, doesn't it?'",
          "target": "act2_trial_begins"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "euthyphro",
      "vocabulary": [
        {
          "term": "philosophy",
          "definition": "Literally 'love of wisdom' — Socrates practiced it not as an academic subject but as a way of life, examining every assumption"
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "dilemma_explained",
        "transition_to_trial"
      ]
    },
    "act2_trial_begins": {
      "title": "Five Hundred and One",
      "text": "The courtroom is an open-air amphitheater packed with 501 citizens serving as **jurors**. There are no lawyers — Socrates must defend himself. Meletus, the young prosecutor, reads the charges:\n\n'Socrates is guilty of corrupting the youth and of not believing in the gods the city believes in, but in other new divinities.'\n\nSocrates stands. He does not beg, weep, or bring his children to plead for sympathy — as defendants usually do. Instead, he speaks calmly:\n\n'I will tell you the truth, and nothing but the truth. I know that this plain speaking may cost me my life. But I would rather die speaking the truth than live by flattering you.'",
      "choices": [
        {
          "text": "Listen to Socrates explain the Oracle's prophecy",
          "target": "act2_oracle"
        },
        {
          "text": "Listen to Socrates cross-examine Meletus",
          "target": "act2_cross_examine"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "apology",
      "vocabulary": [
        {
          "term": "jurors",
          "definition": "In Athenian democracy, juries of 501 citizens decided guilt and punishment — no judge, no lawyers, just citizen justice"
        }
      ],
      "figures": [
        "Socrates",
        "Meletus"
      ],
      "tags": [
        "trial_begins",
        "apology"
      ]
    },
    "act2_oracle": {
      "title": "The Oracle's Riddle",
      "text": "Socrates tells the jury about his friend Chaerephon, who went to the **Oracle at Delphi** and asked: 'Is anyone wiser than Socrates?' The Oracle answered: No.\n\n'I was baffled,' Socrates says. 'I knew I was not wise. So I went to the politicians, the poets, the craftsmen — anyone with a reputation for wisdom — and questioned them. I discovered something disturbing: they all thought they knew things they didn't actually know.'\n\n'The Oracle was right, but not the way you'd think. I am wisest only because I know that I know nothing. This is **Socratic ignorance** — real wisdom begins when you stop pretending to know what you don't.'\n\nSome jurors nod thoughtfully. Others scowl.",
      "choices": [
        {
          "text": "'That's brilliant — real humility as the foundation of knowledge.'",
          "target": "act2_gadfly"
        },
        {
          "text": "'But if you know nothing, how can you teach anyone anything?'",
          "target": "act2_gadfly"
        },
        {
          "text": "Side with the scowling jurors — this is arrogant false modesty",
          "target": "act2_join_accusers"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "apology",
      "vocabulary": [
        {
          "term": "Oracle at Delphi",
          "definition": "The most important oracle in ancient Greece, where the priestess Pythia spoke prophecies from the god Apollo"
        },
        {
          "term": "Socratic ignorance",
          "definition": "The recognition that true wisdom begins with admitting what you do not know — 'I know that I know nothing'"
        }
      ],
      "figures": [
        "Socrates",
        "Chaerephon"
      ],
      "tags": [
        "oracle",
        "socratic_ignorance"
      ]
    },
    "act2_cross_examine": {
      "title": "Turning the Tables",
      "text": "Socrates turns to Meletus. 'You say I corrupt the youth. Tell me — who improves them?'\n\n'The laws,' says Meletus.\n\n'And who else?' 'The jurors.' 'And the assembly?' 'Yes.' 'So every Athenian improves the youth — except me, the one man who corrupts them? How remarkable. By that logic, all horse trainers ruin horses, and only one man in Athens can train them properly.'\n\nThe crowd laughs. Meletus flushes.\n\n'This,' Socrates murmurs to Theo in the gallery, 'is **elenchus** — cross-examination. I take my opponent's claim and show where it leads. If it leads to absurdity, the claim was false. I don't need to prove my innocence. I only need to show that my accuser doesn't know what he's talking about.'",
      "choices": [
        {
          "text": "'That's a devastating technique.'",
          "target": "act2_gadfly"
        },
        {
          "text": "'But humiliating Meletus won't win over the jury.'",
          "target": "act2_gadfly"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "apology",
      "vocabulary": [
        {
          "term": "elenchus",
          "definition": "The Socratic method of cross-examination: testing a claim by drawing out its logical consequences until it contradicts itself"
        }
      ],
      "figures": [
        "Socrates",
        "Meletus"
      ],
      "tags": [
        "cross_examination",
        "elenchus"
      ]
    },
    "act2_gadfly": {
      "title": "The Gadfly of Athens",
      "text": "Socrates's voice rises. 'I am the **gadfly** sent by the god to this city — this great and noble horse that is sluggish and needs to be stirred up. I sting you with questions. I wake you from your comfortable sleep.'\n\n'If you kill me, you will not easily find another gadfly. You will go back to sleep. And you will sleep until someone else comes along to disturb you — if anyone ever does.'\n\nHe pauses. 'Some of you want to know why I don't just stop. Why I don't live quietly and keep my questions to myself. The answer is simple: **the unexamined life is not worth living**. I would rather die questioning than live in silence.'\n\nThe courtroom is silent. Then the vote begins.",
      "choices": [
        {
          "text": "Watch the verdict — what will the jury decide?",
          "target": "act2_verdict"
        },
        {
          "text": "'Would you really rather die than stop asking questions?'",
          "target": "act2_verdict"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "apology",
      "vocabulary": [
        {
          "term": "gadfly",
          "definition": "A fly that bites livestock to keep them moving — Socrates called himself Athens's gadfly, stinging the city out of complacency"
        },
        {
          "term": "the unexamined life is not worth living",
          "definition": "Socrates's most famous declaration: a life lived without questioning, reflection, and self-knowledge has no value"
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "gadfly",
        "examined_life",
        "climax"
      ]
    },
    "act2_join_accusers": {
      "title": "The Popular View",
      "text": "The scowling jurors have a point, Theo thinks. Socrates embarrasses people in public. He questions their beliefs. He makes the powerful look foolish. No wonder they want him silenced.\n\nA juror leans over to Theo. 'He says he's wise because he knows nothing. But he obviously thinks he's smarter than all of us. That's not humility — that's arrogance wrapped in a riddle.'\n\nThe juror has a point too. But then Theo remembers Euthyphro — so certain he was right, so easily demolished. Is the juror any different? Is Theo?",
      "choices": [
        {
          "text": "'Maybe the juror has a point. Socrates IS annoying.'",
          "target": "end_mob_justice"
        },
        {
          "text": "Say nothing — just watch and take notes",
          "target": "end_silent_juror"
        },
        {
          "text": "'Wait — am I doing exactly what Socrates warned about? Accepting without questioning?'",
          "target": "act2_verdict"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "apology",
      "vocabulary": [],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "mob_mentality",
        "critical_moment"
      ]
    },
    "act2_verdict": {
      "title": "Guilty",
      "text": "The vote is 280 to 221. Socrates is found guilty.\n\nUnder Athenian law, both sides now propose a penalty. Meletus proposes death. Socrates could propose exile — the jury would almost certainly accept. Instead, he proposes free meals at the public hall, like an Olympic champion.\n\nThe jury is furious. In the penalty vote, even more jurors vote for death: 360 to 141.\n\nSocrates accepts the sentence calmly. 'The hour of departure has arrived, and we go our ways — I to die, and you to live. Which is better, only the god knows.'\n\nHe is led to prison. Theo follows, stunned.",
      "choices": [
        {
          "text": "Go to the prison — there's still time before the execution",
          "target": "act3_prison"
        },
        {
          "text": "'He could have saved himself! Why didn't he just apologize?'",
          "target": "act3_why_no_apology"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "apology",
      "vocabulary": [],
      "figures": [
        "Socrates",
        "Meletus"
      ],
      "tags": [
        "verdict",
        "death_sentence",
        "transition"
      ]
    },
    "act3_prison": {
      "title": "The Prison at Dawn",
      "text": "Socrates's cell is a simple room. Dawn light filters through a high window. His friend Crito sits beside him, face drawn with worry.\n\n'Socrates, please,' Crito begs. 'I've bribed the guards. A ship is ready. You can escape to Thessaly. Your friends have arranged everything.'\n\nSocrates sits up. He doesn't look like a man about to die. He looks like a man about to have a conversation.\n\n'Crito, my old friend. Should we do what you suggest simply because we can? Or should we first ask whether it is right?'\n\n'But you've been condemned unjustly!' Crito protests.\n\n'That may be true. But does an injustice done to me justify me doing injustice in return? Is it ever right to do wrong?'",
      "choices": [
        {
          "text": "'Crito is right — escape! The trial was unfair.'",
          "target": "act3_escape_argument"
        },
        {
          "text": "'Socrates is right — two wrongs don't make a right.'",
          "target": "act3_laws_speak"
        },
        {
          "text": "'This is the hardest question yet.'",
          "target": "act3_laws_speak"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "crito",
      "vocabulary": [],
      "figures": [
        "Socrates",
        "Crito"
      ],
      "tags": [
        "prison",
        "escape_debate",
        "crito"
      ]
    },
    "act3_why_no_apology": {
      "title": "The Price of Integrity",
      "text": "Socrates smiles. 'You want to know why I didn't grovel? Bring my wife and children to weep? Propose exile?\n\n'Because that would mean my entire life was a lie. I spent seventy years telling Athenians that virtue matters more than comfort, that truth matters more than popularity. If I abandoned those principles to save my skin, every conversation I ever had would become meaningless.'\n\nHe looks at Theo. 'The **examined life** demands **consistency** — not perfection, but the courage to live by what you believe, especially when the cost is high. A philosophy that you abandon under pressure was never really yours.'",
      "choices": [
        {
          "text": "'That's the bravest thing I've ever heard.'",
          "target": "act3_prison"
        },
        {
          "text": "'But dead philosophers can't teach anyone. Isn't survival worth more?'",
          "target": "act3_escape_argument"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "crito",
      "vocabulary": [
        {
          "term": "examined life",
          "definition": "A life lived with constant self-reflection and questioning — Socrates's core principle, worth dying for"
        },
        {
          "term": "consistency",
          "definition": "Living according to your stated principles, even when it's costly — Socrates refused to contradict his life's work to save himself"
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "integrity",
        "examined_life"
      ]
    },
    "act3_escape_argument": {
      "title": "The Case for Freedom",
      "text": "Crito presses his case: 'Think of your sons. They need their father. Think of your friends — we'll be blamed for not saving you. Think of your teaching — how can you teach if you're dead?'\n\nThese are powerful arguments. Practical. Human. Every instinct says: run.\n\nSocrates listens patiently. 'You argue from consequences — what will happen if I stay. But I must argue from principles — what is right. Tell me, Crito: should we care about the opinion of the many, or only the opinion of the wise?'\n\n'The wise,' Crito admits.\n\n'And is it ever right to do injustice, even in response to injustice?'\n\n'...No.'\n\n'Then we must ask: would escaping be an injustice?'",
      "choices": [
        {
          "text": "'How could escaping be unjust? The trial was rigged!'",
          "target": "act3_laws_speak"
        },
        {
          "text": "'I see where this is going. He'll say escaping breaks the social contract.'",
          "target": "act3_laws_speak"
        },
        {
          "text": "Side with Crito — philosophy is fine, but survival comes first",
          "target": "end_escape_artist"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "crito",
      "vocabulary": [],
      "figures": [
        "Socrates",
        "Crito"
      ],
      "tags": [
        "escape_debate",
        "consequences_vs_principles"
      ]
    },
    "act3_laws_speak": {
      "title": "The Voice of the Laws",
      "text": "Socrates closes his eyes. 'Imagine the Laws of Athens could speak. What would they say to me?\n\n'They would say: Socrates, we raised you. We educated you. We gave you seventy years of freedom. You had every opportunity to leave Athens if you disagreed with us. But you stayed. You accepted our protection. And now, because the verdict went against you, you want to break us?\n\n'If every citizen obeyed only the laws he liked, there would be no laws at all.'\n\nThis is the **social contract** — the unwritten agreement between citizen and city. By living in Athens and accepting its benefits, Socrates agreed to accept its judgments, even unjust ones.\n\nTheo's mind reels. 'But what about unjust laws? Don't we have a duty to resist them?'",
      "choices": [
        {
          "text": "'Socrates is right. You can't pick and choose which laws to follow.'",
          "target": "act3_synthesis"
        },
        {
          "text": "'But Thoreau and Martin Luther King broke unjust laws! Weren't they right?'",
          "target": "act3_civil_disobedience"
        },
        {
          "text": "'This is too abstract. A man's life is at stake.'",
          "target": "act3_final_choice"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "crito",
      "vocabulary": [
        {
          "term": "social contract",
          "definition": "The implicit agreement between citizens and their society: you receive protection and order, and in return you accept the community's laws and judgments"
        }
      ],
      "figures": [
        "Socrates",
        "Crito"
      ],
      "tags": [
        "laws_personified",
        "social_contract"
      ]
    },
    "act3_civil_disobedience": {
      "title": "The Exception",
      "text": "Socrates nods slowly. 'You raise a question my philosophy does not easily answer. I believe in the Laws. But I also believe in justice. What happens when they conflict?\n\n'In the Apology, I told the jury: if you order me to stop philosophizing, I will disobey. I will obey the god rather than you. So even I admit there are limits to obedience.'\n\n'But here is the distinction: I disobey openly. I accept the punishment. I do not sneak away in the night like a criminal. A man who breaks a law secretly is a fugitive. A man who breaks a law openly, and accepts the consequences, is making an argument.'\n\nHe pauses. 'Centuries from now, others will face this same question. And they will choose differently than I do. That does not make them wrong. It means the question is genuinely hard.'",
      "choices": [
        {
          "text": "'So there's no single right answer?'",
          "target": "act3_final_choice"
        },
        {
          "text": "'You've given me more questions than answers, Socrates.'",
          "target": "act3_synthesis"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "crito",
      "vocabulary": [],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "civil_disobedience",
        "open_disobedience"
      ]
    },
    "act3_synthesis": {
      "title": "The Examined Life",
      "text": "The sun is rising higher. The guards will come soon.\n\nSocrates turns to Theo. 'You have watched me question Euthyphro's certainty, defend myself before the jury, and debate Crito about escape. What have you learned?'\n\nTheo thinks. Three dialogues. Three lessons:\n\nFrom Euthyphro: **definitions** matter — you cannot live by principles you cannot define.\n\nFrom the Apology: the examined life requires courage — the **gadfly** stings because the city needs waking.\n\nFrom Crito: justice is not just a word — it demands **consistency**, even unto death.\n\n'You have learned to question,' Socrates says. 'That is the beginning.'",
      "choices": [
        {
          "text": "'I want to live the examined life — questioning everything.'",
          "target": "end_examined_life"
        },
        {
          "text": "'I want to be a gadfly — asking the uncomfortable questions.'",
          "target": "end_gadfly"
        },
        {
          "text": "'I believe in the social contract — justice through law, even imperfect law.'",
          "target": "end_just_citizen"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "synthesis",
      "vocabulary": [
        {
          "term": "definitions",
          "definition": "For Socrates, defining your terms is the foundation of clear thinking — you cannot live by a principle you cannot explain"
        },
        {
          "term": "gadfly",
          "definition": "Socrates's metaphor for the philosopher's role: stinging complacent society into awareness, even at personal cost"
        },
        {
          "term": "consistency",
          "definition": "Matching your actions to your principles — Socrates chose death over hypocrisy"
        }
      ],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "synthesis",
        "three_lessons",
        "convergence"
      ]
    },
    "act3_final_choice": {
      "title": "Dawn in the Cell",
      "text": "The hemlock will be brought soon. Crito weeps. Socrates is calm.\n\n'Theo,' he says. 'You have heard the arguments. The Laws say I must stay. My friends say I should go. My own philosophy says I must be consistent.\n\n'But you are young, and the question is yours now, not mine. When you face injustice — and you will — will you obey the law and work to change it from within? Or will you break it openly and accept the cost?\n\n'There is no comfortable answer. There never was. That is what makes it a question worth asking.'",
      "choices": [
        {
          "text": "'I'll work within the system, like you chose to.'",
          "target": "end_just_citizen"
        },
        {
          "text": "'Sometimes breaking the law is the only moral choice.'",
          "target": "end_escape_artist"
        },
        {
          "text": "'I don't know yet — but I'll keep asking the question.'",
          "target": "end_examined_life"
        }
      ],
      "is_ending": false,
      "ending_type": null,
      "era": "crito",
      "vocabulary": [],
      "figures": [
        "Socrates",
        "Crito"
      ],
      "tags": [
        "final_choice",
        "convergence"
      ]
    },
    "end_examined_life": {
      "title": "The Beginning of Wisdom",
      "text": "Theo wakes at his desk, Plato's dialogue still open. But the words are different now — they pulse with the voice of a barefoot man who chose death over silence.\n\nHe picks up his pen and writes: 'The examined life is not comfortable. It means questioning everything — your beliefs, your assumptions, even the things you think you know for certain. It means being confused, and sitting with that confusion instead of running from it.'\n\nHe writes about Euthyphro's shattered certainty, Socrates's refusal to grovel, Crito's agonized loyalty.\n\nThe essay ends: 'Socrates did not die for his answers. He died for his questions. And the questions are still alive.'\n\nHis philosophy teacher reads it twice.",
      "choices": [],
      "is_ending": true,
      "ending_type": "best",
      "era": "frame",
      "vocabulary": [],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "ending",
        "best",
        "examined_life"
      ]
    },
    "end_gadfly": {
      "title": "The Sting of Questions",
      "text": "Theo wakes at his desk with Socrates's challenge ringing in his ears: who will be the next gadfly?\n\nIn class the next day, the teacher explains the social contract. Theo raises his hand. 'But what about when the laws are unjust? Socrates said he'd disobey an order to stop philosophizing. Doesn't that undermine his own argument in the Crito?'\n\nThe teacher blinks. The class stirs. Someone mutters 'here we go.'\n\nGood. The city was sleeping. Theo stung it.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "ending",
        "good",
        "gadfly_legacy"
      ]
    },
    "end_just_citizen": {
      "title": "Justice Within the Law",
      "text": "Theo wakes at his desk, haunted by Socrates's final argument. The social contract is real. Laws must be respected — not because they are perfect, but because the alternative is chaos.\n\nHe writes his essay about Crito's prison debate, about the voice of the Laws, about why Socrates accepted a death sentence he knew was unjust.\n\n'Justice is not revenge,' Theo writes. 'It is the commitment to a system that can correct its own mistakes — if its citizens have the courage to work within it.'\n\nIt is a careful, measured essay. Socrates would appreciate the reasoning, even if he might push back on the conclusions.",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [
        "Socrates",
        "Crito"
      ],
      "tags": [
        "ending",
        "good",
        "social_contract"
      ]
    },
    "end_escape_artist": {
      "title": "The Higher Law",
      "text": "Theo wakes at his desk, certain of one thing: Socrates should have escaped. Some laws are wrong. Some systems are broken. And sometimes the most moral act is to break the rules.\n\nHe writes about Thoreau, about King, about every person who chose conscience over compliance. He acknowledges Socrates's argument — and respectfully disagrees.\n\n'Socrates was right that we owe something to the laws that raised us. But he was wrong that we owe them our lives. A law that kills the innocent has already broken the contract.'\n\nIt is a bold essay. It earns a B-plus and a note: 'Strong argument. Socrates would have enjoyed cross-examining you.'",
      "choices": [],
      "is_ending": true,
      "ending_type": "good",
      "era": "frame",
      "vocabulary": [],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "ending",
        "good",
        "civil_disobedience"
      ]
    },
    "end_euthyphro_trap": {
      "title": "The Comfortable Certainty",
      "text": "Theo wakes at his desk and writes his essay quickly. Piety is obvious. Justice is obvious. The good guys win. The bad guys lose. Philosophy just makes everything more confusing than it needs to be.\n\nHe gets an A-minus. He never thinks about Socrates again.\n\nSomewhere in Athens, a barefoot philosopher shakes his satyr's head. Another Euthyphro — so certain, so comfortable, so wrong.",
      "choices": [],
      "is_ending": true,
      "ending_type": "neutral",
      "era": "frame",
      "vocabulary": [],
      "figures": [
        "Socrates",
        "Euthyphro"
      ],
      "tags": [
        "ending",
        "neutral",
        "false_certainty"
      ]
    },
    "end_silent_juror": {
      "title": "The Spectator",
      "text": "Theo wakes at his desk. He watched the trial. He heard the arguments. He saw a man choose death over compromise. And he... took notes.\n\nHis essay is competent. It summarizes the dialogues accurately. It doesn't take a position. It doesn't ask a question. It doesn't sting.\n\nSocrates would say: you observed, but you did not participate. You learned the words but not the music. The examined life is not a spectator sport.",
      "choices": [],
      "is_ending": true,
      "ending_type": "neutral",
      "era": "frame",
      "vocabulary": [],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "ending",
        "neutral",
        "passive_observer"
      ]
    },
    "end_mob_justice": {
      "title": "The Voice of the Crowd",
      "text": "Theo wakes at his desk and writes: 'Socrates was guilty. He undermined public morality, confused the youth, and showed disrespect for democratic institutions. The jury was right to convict.'\n\nIt's the safe answer. The popular answer. The answer that would have gotten 280 votes in an Athenian court.\n\nTheo gets an A. His teacher writes 'Well-reasoned!' in the margin.\n\nTwenty-four centuries later, the world still remembers the name of the man who was condemned. Nobody remembers the names of the jurors.",
      "choices": [],
      "is_ending": true,
      "ending_type": "bad",
      "era": "frame",
      "vocabulary": [],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "ending",
        "bad",
        "mob_justice"
      ]
    },
    "end_unexamined": {
      "title": "The Closed Mind",
      "text": "Theo wakes at his desk. That dream was weird. Some old Greek guy who asked too many questions and got himself killed for it. What a waste.\n\nHe closes the book. Writes a generic essay. Gets a B.\n\nThe unexamined life goes on. Comfortable. Unquestioned. Exactly as the 280 jurors preferred it.",
      "choices": [],
      "is_ending": true,
      "ending_type": "bad",
      "era": "frame",
      "vocabulary": [],
      "figures": [
        "Socrates"
      ],
      "tags": [
        "ending",
        "bad",
        "unexamined_life"
      ]
    }
  },
  "start_node": "start",
  "edges": [
    [
      "start",
      "act1_meet_socrates"
    ],
    [
      "start",
      "act1_meet_euthyphro"
    ],
    [
      "act1_meet_socrates",
      "act1_euthyphro_debate"
    ],
    [
      "act1_meet_socrates",
      "act1_why_definitions"
    ],
    [
      "act1_meet_euthyphro",
      "act1_euthyphro_trap"
    ],
    [
      "act1_meet_euthyphro",
      "act1_euthyphro_debate"
    ],
    [
      "act1_why_definitions",
      "act1_euthyphro_debate"
    ],
    [
      "act1_why_definitions",
      "act1_euthyphro_trap"
    ],
    [
      "act1_euthyphro_debate",
      "act1_dilemma_explained"
    ],
    [
      "act1_euthyphro_debate",
      "act2_trial_begins"
    ],
    [
      "act1_euthyphro_trap",
      "act1_dilemma_explained"
    ],
    [
      "act1_euthyphro_trap",
      "end_euthyphro_trap"
    ],
    [
      "act1_euthyphro_trap",
      "end_unexamined"
    ],
    [
      "act1_dilemma_explained",
      "act2_trial_begins"
    ],
    [
      "act2_trial_begins",
      "act2_oracle"
    ],
    [
      "act2_trial_begins",
      "act2_cross_examine"
    ],
    [
      "act2_oracle",
      "act2_gadfly"
    ],
    [
      "act2_oracle",
      "act2_join_accusers"
    ],
    [
      "act2_cross_examine",
      "act2_gadfly"
    ],
    [
      "act2_gadfly",
      "act2_verdict"
    ],
    [
      "act2_join_accusers",
      "end_mob_justice"
    ],
    [
      "act2_join_accusers",
      "end_silent_juror"
    ],
    [
      "act2_join_accusers",
      "act2_verdict"
    ],
    [
      "act2_verdict",
      "act3_prison"
    ],
    [
      "act2_verdict",
      "act3_why_no_apology"
    ],
    [
      "act3_prison",
      "act3_escape_argument"
    ],
    [
      "act3_prison",
      "act3_laws_speak"
    ],
    [
      "act3_why_no_apology",
      "act3_prison"
    ],
    [
      "act3_why_no_apology",
      "act3_escape_argument"
    ],
    [
      "act3_escape_argument",
      "act3_laws_speak"
    ],
    [
      "act3_escape_argument",
      "end_escape_artist"
    ],
    [
      "act3_laws_speak",
      "act3_synthesis"
    ],
    [
      "act3_laws_speak",
      "act3_civil_disobedience"
    ],
    [
      "act3_laws_speak",
      "act3_final_choice"
    ],
    [
      "act3_civil_disobedience",
      "act3_final_choice"
    ],
    [
      "act3_civil_disobedience",
      "act3_synthesis"
    ],
    [
      "act3_synthesis",
      "end_examined_life"
    ],
    [
      "act3_synthesis",
      "end_gadfly"
    ],
    [
      "act3_synthesis",
      "end_just_citizen"
    ],
    [
      "act3_final_choice",
      "end_just_citizen"
    ],
    [
      "act3_final_choice",
      "end_escape_artist"
    ],
    [
      "act3_final_choice",
      "end_examined_life"
    ]
  ]
};
